### ISSUE TITLE
Keyboard actions seem off

### ISSUE THREAD

**Issue by zslabs** [jshjohnson/Choices#1]
Hi,
Appreciate all the hard work going on here! Noticed something a little odd when interacting with the dropdowns with my keyboard; when I attempt to filter a list, the current selected position seems to jump around a bit.

![screenflow](https://cloud.githubusercontent.com/assets/1018402/15948853/33685f46-2e71-11e6-8ec7-4be7c6fc7b88.gif)

The above is with remote sources, but I've also seen this happen with `Multiple Select Input`. Thanks!

**Comment by jshjohnson** [comment]
Thanks for the heads up, I'm looking into this now.

**Comment by jshjohnson** [comment]
Resolved in new version
