### ISSUE TITLE
Events

### ISSUE THREAD

**Issue by vegarringdal** [jshjohnson/Choices#101]
Is it possible to:

* know when someone opens the dropdown
* know when someone selects a item in a dropdown
* know when they try and search and then populate result from what ever result you get from server side?

I though there was a callbackOnChange event and callbackOnSearch before

**Comment by jshjohnson** [comment]
Hey,

There are still events for search and change, see here: https://github.com/jshjohnson/Choices/blob/master/README.md#events

There is not however an event for opening a drop down. If people want it, it would be simple to add

**Comment by vegarringdal** [comment]
sorry, over looked that somehow
