### ISSUE TITLE
Question: how to work with large data sets? 

### ISSUE THREAD

**Issue by nenad007** [jshjohnson/Choices#102]
We have around 5'000 data records who the user can (multi) select. 

When Choices fetch the data we had limit the API to 200 as more will slow down. 
Is there a solution that Choices aside from Populate the Initial dataset will POST the entered value (if it not exist in the pre-populated data) to the API and show the results it got back from API?

**Comment by jshjohnson** [comment]
Hi @nenad007,

Could you give me an example of your code highlighting what you're trying to achieve please?

Thanks

**Comment by SlyNet** [comment]
How to handle a case where the amount of items that are fetched from remote server is too large? So client will never have a full set of items that he is choosing from, but should be able to find a needed item?
For now we are using such code 

```
    const control = new choises(this.$el, {
        duplicateItems: false
    })

    this.$el.addEventListener("search", (ev) => {
        control.ajax(async (callback) => {
              fetch(url)
                .then(function(response) {
                    response.json().then(function(data) {
                        control.setChoices([], 'value', 'label')
                        callback(data, 'value', 'label');
                    });
                })
        })
    })
```

To be able to update update options as user types. Is it supposed to be that way?

**Comment by vegarringdal** [comment]
You could just fetch data as user searches and limit it to 10-30..

Played around with Aurelia and gist here with search on Choices (dunno if its any help)
https://gist.run/?id=5f8a6e9ce948dffc2f4798d6f525fb20

**Comment by jshjohnson** [comment]
I believe @vegarringdal has answered the question. Please ask me to re-open this if not.

Thanks
