### ISSUE TITLE
Feature: Custom noResultsText / noChoicesText per element

### ISSUE THREAD

**Issue by lewishowles** [jshjohnson/Choices#106]
It would be a nice touch in something I'm creating to be able to customise the verb based on some attribute of each item - for example 'No ingredients to choose from', 'No courses to choose from'.

I could loop through all selects and instantiate Choices manually, but I imagine this probably isn't super efficient.

I'm thinking perhaps allowing these two options to be functions which take the element as a parameter so we can build whatever string we require would be awesome.

**Comment by jshjohnson** [comment]
This has been implemented as of [version 2.7.1](https://github.com/jshjohnson/Choices/releases/tag/v2.7.1) 👍
