### ISSUE TITLE
change event is raised with old selected value when remove button used

### ISSUE THREAD

**Issue by SlyNet** [jshjohnson/Choices#108]
If value is selected and remove button is used than `change` event is raised but with old value selected.

How to determine that value was actually removed? 
Here is an example: https://jsfiddle.net/hedgic/m44fggL1/2/ Try to select value and then remove it. Expected result is to have `null` in `value` of `ev.detail.value` but I'm receiving an old value

**Comment by jshjohnson** [comment]
The value should be of the item removed. This issue has been raised before though so I'm beginning to think it should just be null... I'll look into it

**Comment by SlyNet** [comment]
Is there a flag or any other event to know that value actually was removed, not selected?

**Comment by jshjohnson** [comment]
The [`removeItem`](https://github.com/jshjohnson/Choices#removeitem) event is triggered when an item is removed. [`highlightItem`](https://github.com/jshjohnson/Choices#highlightitem) is triggered when a item is selected/highlighted.
