### ISSUE TITLE
loading state is not reset if callback receives empty array

### ISSUE THREAD

**Issue by SlyNet** [jshjohnson/Choices#109]
In this [example](https://jsfiddle.net/hedgic/adh3d3x8/1/) "Loading" text is never hidden from drop down. A workaround is to pass `[0]`

**Comment by jshjohnson** [comment]
Hi @SlyNet,

This has been resolved as of [version 2.7.2](https://github.com/jshjohnson/Choices/releases/tag/v2.7.2).

Thanks
