### ISSUE TITLE
Support for HTML in options

### ISSUE THREAD

**Issue by haggen** [jshjohnson/Choices#110]
Is it possible to use HTML when adding options? For instance, a `<br>` for multi-line labels?

**Comment by jshjohnson** [comment]
Hi @haggen,

Could you give me an example of how you envisage doing this?

Thanks

**Comment by KeironLowe** [comment]
I know this is closed, but one example are superscript tags. We need to have a registered symbol superscripted but at the minute it's being stripped out of the option.
