### ISSUE TITLE
Can we set the dropdown to body?

### ISSUE THREAD

**Issue by vegarringdal** [jshjohnson/Choices#112]
Can we set the dropdown to body?

So if used in a small dialog that scrolls it wont be hidden
Or a container that have overflow set to hidden.

**Comment by vegarringdal** [comment]
Anything new on this one ?

**Comment by jshjohnson** [comment]
Hey @vegarringdal,

It's not something I had planned on doing as the structure of the HTML needs to be very strict for Choices to work. I'll consider it if enough people ask for it and re-open this issue.

Thanks

**Comment by vegarringdal** [comment]
ok, well if you get bored then you have challenge waiting :-)
Wanted to try and use it inside a table/grid, but didnt go well when popup got hidden by the overflow

Lets hope this is something other need to then :-)

**Comment by virajsoni06** [comment]
@jshjohnson @vegarringdal I'll +1 to this.

This is important when it comes to card based layouts. I am facing an issue where the UI elements are in card format with horizontal scroll, border radius, etc for which we had to add `overflow: hidden`

In doing so, the Choices dropdown gets hidden behind the card.

**Comment by ArielGueta** [comment]
+1

**Comment by kivils** [comment]
+1

**Comment by jurajk** [comment]
👍

**Comment by EvaOva** [comment]
****

**Comment by EvaOva** [comment]
+1

**Comment by Psyphant** [comment]
+1

**Comment by muenchris** [comment]
> +1
> My solution was to set `position: fixed;` at the `.choices__list--dropdown` element and generating the `top` value dynamically depending on the position of the select.

can you share code how you did this? I need to do the same for my solutions
Thanks

**Comment by kuanyen** [comment]
> +1
> My solution was to set `position: fixed;` at the `.choices__list--dropdown` element and generating the `top` value dynamically depending on the position of the select.

![Screenshot_20210701_093719](https://user-images.githubusercontent.com/20762725/124051915-f99cb380-da4f-11eb-8c97-36f227ae2928.png)
Cannot solve my problem in this way... `z-index` issue? ... :crying_cat_face:

**Comment by seijikun** [comment]
In case anyone is still interested. Here is my solution:
https://github.com/seijikun/Choices/commit/71dffcd2aa587880096c94b4053e305058185488
