### ISSUE TITLE
Can we use datalists with text inputs?

### ISSUE THREAD

**Issue by stlsixers** [jshjohnson/Choices#113]
Can we use datalists with text inputs?

http://www.w3schools.com/tags/tag_datalist.asp

**Comment by jshjohnson** [comment]
Not currently, although would look to implement this if enough people request it!

**Comment by faizanakram99** [comment]
@jshjohnson 

It would be handy, yes. 

Is there an alternative of input type=text with an autocomplete list for the time being ?

**Comment by marceloverdijk** [comment]
+1
