### ISSUE TITLE
Autofill a choices single select

### ISSUE THREAD

**Issue by thejmsill** [jshjohnson/Choices#115]
I'm trying to use the wonderful Choices for a credit card payment page and/or address page. Is there a way to have the autofill enabled? 

Thanks!

**Comment by jshjohnson** [comment]
Hey @thejmsill,

Are you using a text input or a select box for the credit card/address fields?

Thanks

**Comment by thejmsill** [comment]
I was using select box ... typically it's the date, country or province/state dropdowns.

**Comment by jshjohnson** [comment]
Using [`setValueByChoice`](https://github.com/jshjohnson/Choices#setvaluebychoicevalue) should achieve what you're looking for!

**Comment by benjaminprojas** [comment]
@jshjohnson I am wondering if this has to do with the browser autofill? I am having the issue where I select an address from the browser autofill and it does not update the select box for state/province or country for that matter.

![image](https://cloud.githubusercontent.com/assets/962530/23757016/92d6e1a0-04b3-11e7-96b3-df36ea732934.png)

Would love to see this supported.

**Comment by jshjohnson** [comment]
You're right; it's being caused by browser autofill. Without disabling autocomplete entirely on inputs, I'm not sure of a clean solution to this problem 👎

**Comment by benjaminprojas** [comment]
@jshjohnson I'd like to bring up this issue again as its a big cause for concern for our usage of Choices.js and almost a deal breaker.  Choices.js is perfect for us except this one issue.

You can see by the following screen recording that I believe this is a simple fix: http://cloud.supportally.com/163g1T2X1907

I believe only two (simple) things need to be done to make this work:

1. All the options need to be added to the select box whether they are selected or not.  Adding a custom template for those options would be good as well.
2. Choices.js needs to listen to the changes on that select box and trigger the appropriate selection methods to change the selected items.

Thoughts?

**Comment by jshjohnson** [comment]
Hey @benjaminprojas,

I'm going to investigate this for you! Will provide updates soon

**Comment by benjaminprojas** [comment]
Thanks @jshjohnson! I was able to get a workaround by using some custom Javascript to follow my two steps above and its working for me now. but would be nice if it was native :)

**Comment by SampsonCrowley** [comment]
sorry for the bump but i agree with @benjaminprojas I never understood why choices felt the need to clear out the original select instead of just setting the selection to the right option in the background

**Comment by ingmferrer** [comment]
I'm looking to solve this same issue.

**Comment by benjaminprojas** [comment]
@jshjohnson @SampsonCrowley @ingmferrer 

Sorry for the delay in writing back about this! This is how I implemented it:

First, when I initialize the dropdown, I add the `callbackOnInit` option.

```js
let states = new Choices($('.states')[0], {
	itemSelectText: '',
	shouldSort: false,
	placeholder: true,
	placeholderValue: 'Choose State',
	removeItems: true,
	search: true,
	callbackOnInit: choicesInitCallback
});
```

My callback function basically adds all the options that were removed back in and looks like this:

```js
choicesInitCallback() {
	resetSelect(this);
}

resetSelect = (choices) => {
	let html = '',
		selected = '';

	$.each(choices.choiceList.children, function(i, v) {
		selected = $(v).data('value') == $(choices.element).val() ? ' selected' : '';
		html += '<option value="' + $(v).data('value') + '"' + selected + '>' + $(v).text().trim() + '</option>';
	});
	$(choices.element).html(html);
}
```

Then I needed to detect the auto fill changing the element and update it in Choices as well as reset the select once that has finished:

```js
$('.states').on('change', onSelectStateChange);
onSelectStateChange = (event) => {
	states.setValue([
		{
			value: $(event.target).val(),
			label: $(event.target).find('option[value="' + $(event.target).val() + '"]').text()
		}
	]);
	resetSelect(states);
}
```

It's been a while since I did this, so things may have changed, but I hope that helps!

**Comment by SampsonCrowley** [comment]
I had to end up writing my own components for this functionality. It's a MUCH more complicated issue than it looks like at the surface. If I don't forget, I'll post the way I solved this later
