### ISSUE TITLE
how can I add  one group‘s choices（eg this group has 3 chioces ） 

### ISSUE THREAD

**Issue by yangjiebeijing** [jshjohnson/Choices#118]
hi， i want to add them by one time ，could i click the group to add them？

**Comment by jshjohnson** [comment]
Hi, 

Do you want to add the group of choices programmatically?

Thanks

**Comment by yangjiebeijing** [comment]
both programmatically and by mouse

**Comment by jshjohnson** [comment]
Hi @yangjiebeijing,

There is not currently a way to _select_ an entire group of choices. It is possible to _add_ a group of choices though. See the second example [here](https://github.com/jshjohnson/Choices#setchoiceschoices-value-label-replacechoices).

Thanks
