### ISSUE TITLE
Feature request: itemList container

### ISSUE THREAD

**Issue by zslabs** [jshjohnson/Choices#119]
Hey!
Wanted to get your thoughts on making the area in which `itemList` (or `.choices__list--multiple`) is appended to configurable. Right now, the input cursor jumps around with items that you select from the search-box, which can be a bit distracting. I think it'd be great if we could either pass through a container or intercept it somehow via the init function to append these to an outside area so that the regular input size is not impacted. Let me know watcha think. Thanks!

**Comment by benunternaehrer** [comment]
Came across the same problem... If you want to have the items below the input field you can do this with css (using flex and flex order). Looks sth. like this:
```
.choices-wrapper-div {
    position: relative;
    .choices__inner {
        display: flex;
        flex-direction: column;
        padding-left: 14px;
        padding-right: 14px;
        background-color: transparent;
        overflow: visible;
        // this is the background for the input field
        &::after {
            content: '';
            display: block;
            position: absolute;
            background-color: white;
            top: 0;
            left: 0;
            width: 100%;
            height:  50px;
            z-index: -1;
        }
    }
    .choices__input {
        order: -1;
    }
    .choices__list {
        &--dropdown {
            position: absolute;
            left: 0;
            width: 100%;
            z-index: 2;
            height: 200px;
            top: 50px;
        }
    }
    .choices__list--multiple {
        margin-left: -14px;
        margin-right: -14px;
    }
}

```

**Comment by jshjohnson** [comment]
Going to close this for now - will re-open if more people request it. Thanks

**Comment by marcelaerts** [comment]
Would be good option.
