### ISSUE TITLE
Usage in another React application?

### ISSUE THREAD

**Issue by th3fallen** [jshjohnson/Choices#12]
Any chance you've used this inside another react+redux application? if so how? i've tried importing it and using it htat way but i get unexpected token inport errors?

**Comment by jshjohnson** [comment]
Hi @th3fallen,

Did you manage to get this working? If there is anything I can add to the documentation to make this easier, let me know.

Thanks

**Comment by th3fallen** [comment]
@jshjohnson thanks for the response, yes i did but in Bootstrap 4 beta it's styles explode (get MASSIVE) the form and text are huge and i couldnt sort out why so i had to move to another lib. sad yours was damn near perfect.

**Comment by jshjohnson** [comment]
The styling would have been inheriting from Bootstrap causing the issues. I may produce a Bootstrap version of the CSS in the future if enough people want it.

Thanks

**Comment by th3fallen** [comment]
Yep, i'll star and keep an eye on it, if you do i'll be all over it. Thanks for the help man

**Comment by jshjohnson** [comment]
I have just pushed a tweak to the CSS that may resolve your font sizing issue! Check it out when you get a chance, I would be interested to know whether it solves your problem.

**Comment by th3fallen** [comment]
I both love and hate you now, love that it's fixed now. and hate you because i now have to rewrite this component lol thank you so much.
