### ISSUE TITLE
Feature Request: Ability to disable filter of choices without removing the input

### ISSUE THREAD

**Issue by manelmadeira** [jshjohnson/Choices#120]
Hi,

I would like to request to add a settings flag to disable the choices filtering when typing the search input but continue to emit the search event.

I'm using the on search event to search on an API endpoint.

Thanks,
Manuel Madeira

**Comment by jshjohnson** [comment]
Hey, 

This would be really easy to implement, I would be happy to review a pull request!

Thanks
