### ISSUE TITLE
Fails when server imports choices. "Document is not defined" when import.

### ISSUE THREAD

**Issue by Dankovk** [jshjohnson/Choices#124]
`ReferenceError: document is not defined` comes when try to import in my server-side React app. The initializing and all logic comes in Client part (ComponentDidMount), but scripts aren't transpiling.

**Comment by jshjohnson** [comment]
Hi @Dankovk, could you send over the full error please?

Thanks

**Comment by connor-baer** [comment]
I'm having the same issue with a next.js app. 

Here's my (shortened) code: 

```js
import { Component } from 'react';
import Choices from 'choices.js';
import PropTypes from 'prop-types';

export default class SubmissionForm extends Component {
  static propTypes = {
    countries: PropTypes.arrayOf(PropTypes.object).isRequired,
  };

  constructor(props) {
    super(props);
    this.state = {
      isSubmitted: false
    };
  }

  componentDidMount() {
    if (typeof document === 'undefined') {
      return;
    }
    const choicesOptions = {
      maxItemCount: 3,
      duplicateItems: false,
      itemSelectText: 'Press Enter to select'
    };

    const countries = new Choices(this.countries, choicesOptions);
  }

  render() {
    return (
      <select
        label="Which country are you from?"
        name="countries"
        placeholder="Add a country..."
        ref={select => {
          this.countries = select;
        }}
        multiple
        required
      >
        {countries.map((country, i) => (
          <option key={i} value={country.name}>
            {country.name}
          </option>
        ))}
      </select>
    );
  }
}
```

The full error: 
```
ReferenceError: document is not defined
    at ~/user/project/node_modules/choices.js/assets/scripts/dist/choices.min.js:4:1713
    at Object.Array.from.Array.from.e (~/user/project/node_modules/choices.js/assets/scripts/dist/choices.min.js:4:1863)
    at t (~/user/project/node_modules/choices.js/assets/scripts/dist/choices.min.js:2:324)
    at Object.a.id (~/user/project/node_modules/choices.js/assets/scripts/dist/choices.min.js:2:1186)
    at t (~/user/project/node_modules/choices.js/assets/scripts/dist/choices.min.js:2:324)
    at Object.<anonymous> (~/user/project/node_modules/choices.js/assets/scripts/dist/choices.min.js:2:465)
    at t (~/user/project/node_modules/choices.js/assets/scripts/dist/choices.min.js:2:324)
    at ~/user/project/node_modules/choices.js/assets/scripts/dist/choices.min.js:2:432
    at ~/user/project/node_modules/choices.js/assets/scripts/dist/choices.min.js:2:437
    at _580‍.r.i (~/user/project/node_modules/choices.js/assets/scripts/dist/choices.min.js:2:81)
```

**Comment by jshjohnson** [comment]
@connor-baer Is your application also server side rendered? I have used Choices in React with a near identical setup to yours and it worked fine! 👍

**Comment by connor-baer** [comment]
@jshjohnson Yes, Next.js does server-side rendering.

I tried removing all code related to Choices except for the import statement and it still throws the same error. It appears that Choices runs some logic when imported? Not sure how that's even possible. So a fix for this could be to check if `document` is defined before running that logic.

**Comment by heardy** [comment]
Hi @jshjohnson, I am having the same problem as above. This is due to Choices requiring a DOM to work so it won't currently run on node without modification.

Given the radio silence does this mean you are not going to support running Choices on the server for isomorphic apps? or do you need some more information?

Where the issues lie is in a couple of internal libs that are imported in the main file (https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/choices.js). When the modules are loaded they both execute code that talks to the DOM. (There are likely more instances but these are 2 that I found after a quick skim of the code).

```
/* from https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/lib/polyfills.js#L126 */

CustomEvent.prototype = window.Event.prototype;
```

```
/* from https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/lib/utils.js#L480 */

let tmpEl = document.createElement('div');
```

Hope this helps. Let me know if you require more information.

Cheers

**Comment by fernandoagarcia** [comment]
@Dankovk 'document is not defined' means that your react app is trying to run front-end code via the server. 
```

if (process.browser) {
// run client side code here.
}
```

**Comment by heardy** [comment]
@fernandoagarcia The import `import Choices from 'choices.js';` is what is loading/executing the problematic code therefore the only way around it without modifying Choices is to load the module dynamically.

```
if (canUseDom) {
  var Choices = require('Choices.js');
}
```

However, loading the module like this is not ideal, and also as the app requires the DOM to setup, I am not sure how this would work.

Either way this feels like a workaround rather than a solution.

**Comment by fernandoagarcia** [comment]
@heardy what should go inside your if statement is the initialization of ChoiceJs not the import. However I need the full code to better help you. The component has to be in the dom then initialized. I currently use this with Nuxt and it works the same way. Also be aware of the component lifecycle when initializing as well. But again I need to see the full code. Do you have a repo?

**Comment by jshjohnson** [comment]
I have no problem supporting this, I just don't have an isomorphic setup to test it's working properly. Would be good to get some PR's in to tackle the issue and then get somebody to test it's actually working! 👍

**Comment by heardy** [comment]
@jshjohnson I have put together a repo for a very simple Choices isomorphic version.

https://github.com/heardy/choices-isomorphic-example

@fernandoagarcia above example might do better at demonstrating the problem then my words.

Note: Been moving house so a bit exhausted and sleep deprived. Hope it all works and is clear 😛

**Comment by wag110894** [comment]
Having this same issue. Is there a workaround or a fix available for this issue?
