### ISSUE TITLE
Need access to showDropdown

### ISSUE THREAD

**Issue by benjaminprojas** [jshjohnson/Choices#125]
Hey! I noticed the new event `showDropdown` and I could really use this feature, however npm is showing the latest version is 2.7.2 which doesn't have that event.  Any ETA on when that will be updated?

Thanks!

**Comment by benjaminprojas** [comment]
Just realized that the `showDropdown` event is not even in 2.7.5. Do you have an eta for the next release here/@npm?

**Comment by jshjohnson** [comment]
Hi @benjaminprojas,

Apologies, I've just pushed a release with these events included. See [here](https://github.com/jshjohnson/Choices/releases/tag/v2.7.6).

Thanks

**Comment by benjaminprojas** [comment]
Thank you! Much appreciated :)
