### ISSUE TITLE
Ability to trigger event on click/enter - single select

### ISSUE THREAD

**Issue by benjaminprojas** [jshjohnson/Choices#126]
I am trying to trigger an event if an option is clicked/enter key is pressed - even if the value has not changed.  Currently I am running it on `hideDropdown` but this has the downside of firing every time you close the dropdown, even if you don't select an option.  Looking through the code, it would probably need to trigger an event inside the `_handleChoiceAction` method. Let me know if that makes sense?

I think this might only make sense for a single select dropdown since in a multiselect you would always trigger a change event (I believe).

In that case it could easily go in the `if` statement here: https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/choices.js#L1031

**Comment by jshjohnson** [comment]
Hey @benjaminprojas,

Apologies for the delay. Just to clarify, you would like an event for single select boxes that runs when any option is chosen?

Thanks

**Comment by benjaminprojas** [comment]
@jshjohnson no worries!

Yes, something that will get triggered even if its not changing the value.

**Comment by jshjohnson** [comment]
This has been added to [version 2.7.7](https://github.com/jshjohnson/Choices/releases/tag/v2.7.7). See here: https://github.com/jshjohnson/Choices#choice

Thanks

**Comment by benjaminprojas** [comment]
Fantastic! Thanks @jshjohnson

**Comment by jshjohnson** [comment]
No problem, let me know if you have any issues
