### ISSUE TITLE
Bug: iOS 9.0 doesn't listen to keyup

### ISSUE THREAD

**Issue by veiico** [jshjohnson/Choices#129]
As the title states, **iOS 9.0 doesn't listen to keyup event (native problem)**. This means that search field doesn't work on new iPhones. Simple solution to this is to add 'keypress' event listener to call '_onKeyUp' function (which I've tested and works) or replace 'keyup' event with it (main script line 1236).

Will fork for now, but please keep that in mind and try to fix it for other users :)

**Comment by veiico** [comment]
P.S. Keep in mind that if taking the change 'keyup' event to 'keypress' event, search starts to search on third key rather than the second inputted key.

**Comment by jshjohnson** [comment]
Hmmm, don't know whether to make this configurable or be opinionated about it

**Comment by jshjohnson** [comment]
I've found no issues on iOS version 10.x.x (Apple may have fixed this) so closing this issue. 👍
