### ISSUE TITLE
Export react component

### ISSUE THREAD

**Issue by th3fallen** [jshjohnson/Choices#13]
Not sure if this would be possible but it'd be SUPER cool if you exported a react component as well.

**Comment by jshjohnson** [comment]
Could you possibly give me an example of what you're looking for? Not overly familiar with wrapping an existing library in React. If you could maybe give me a feature list, I could look into it!

Thanks,

**Comment by DaBs** [comment]
This should not be part of the choices component itself, but rather a plugin for it, like choices-react or something along those lines. Exporting a React component is way too specific, and I have a feeling that the reason the author made this without jQuery was to get out of making it library agnostic.

**Comment by th3fallen** [comment]
i would disagree @DaBs especially considering this plugin is built with react/redux

**Comment by syropian** [comment]
@th3fallen Sifting through the code, and looking at the package.json file, it uses redux, but not React. It would make much more sense to write a custom React component that wraps this lib, instead of exporting it from the base lib. That way if people also want to make VueJS, Angular, Ember, etc components that use it, they aren't pulling in any needless React dependencies.

**Comment by th3fallen** [comment]
ah i misread my apologies guys, yep totally agree then should be a separate package.

**Comment by mikefrancis** [comment]
@jshjohnson Yo - does `choices-react` or something like that exist?

**Comment by jshjohnson** [comment]
@mikefrancis Not AFAIK!

**Comment by mxmtsk** [comment]
I was searching for a react component too, I thought I might leave this as a quick and dirty starting point for others if you really wanna use it in react. It works well for my case.

```Javascript
  componentDidMount() {
    this.choices = new Choices('.js-choice-remove', {
      removeItemButton: true,
    });
  }

  componentWillUnmount() {
    // Remove event listener
    this.choices.destroy();
  }
```

**Comment by mikefrancis** [comment]
We ended up using https://github.com/paypal/downshift for React - it's pretty good.

**Comment by NetanelBasal** [comment]
I created an Angular component that take care to a lot of things out of the box and new fresh style. https://github.com/NetanelBasal/nb-choices
