### ISSUE TITLE
enable or disable with external input

### ISSUE THREAD

**Issue by totti2007** [jshjohnson/Choices#131]
hi
how can disable or enable a dropdown select with a button in html code?

**Comment by jshjohnson** [comment]
Hi, there is information about the disable method [here](https://github.com/jshjohnson/Choices#disable).

If you wanted to manage it via clicking a button, you could do something like this:

```js
const button = document.querySelector('button');
let isActive = true;

button.addEventListener('click', () => {
  if (isActive) {
    choices.disable();
  } else {
    choices.enable();
  }
});
```
