### ISSUE TITLE
Not requiring Enter

### ISSUE THREAD

**Issue by tobireif** [jshjohnson/Choices#134]
On https://joshuajohnson.co.uk/Choices/ in the first example, creating a new item requires hitting Enter. Is it possible to instead have a setting where (each new string cannot contain spaces but) new items get created when Space is pressed?

**Comment by jshjohnson** [comment]
That is not currently possible but I'll happily review a pull request if you want to have a go at it 👍

**Comment by jshjohnson** [comment]
Going to close this for now - will re-open if more people request it. Thanks.

**Comment by HMAZonderland** [comment]
To bump it, I would like this to.
