### ISSUE TITLE
custom JSON

### ISSUE THREAD

**Issue by cmnstmntmn** [jshjohnson/Choices#136]
hey, is there a way to pass a custom json to Choices? an item looks this way:

```json
  id: 21,
  code: 1231
  name: 'Name'
```

**Comment by jshjohnson** [comment]
Hi @cmnstmntmn,

Could you give me some more information as to what you are trying to achieve? I think you're refereeing to the [`setChoices()`](https://github.com/jshjohnson/Choices#setchoiceschoices-value-label-replacechoices) method, by let me know.

Thanks
