### ISSUE TITLE
Add callback for when tag is selected and/or edited

### ISSUE THREAD

**Issue by th3fallen** [jshjohnson/Choices#14]
Would be super cool if there was a callback for when a tag was clicked so that someone could then trigger the edited state.

**Comment by jshjohnson** [comment]
Adding a callback for when an item is highlighted/unhighlighted (i.e. clicked) would be really simple to implement. Adding a callback for when an item is being edited is slightly tricker but theoretically still possible. I'll look into this shortly.

**Comment by jshjohnson** [comment]
I have added two new callbacks as of version 1.0.50:

On highlight: https://github.com/jshjohnson/Choices#callbackonhighlightitem
On unhighlight: https://github.com/jshjohnson/Choices#callbackonunhighlightitem

**Comment by th3fallen** [comment]
Man you're the best! but sadly the callbacks dont seem to be firing?

```
initChosen() {
    Object.assign({}, {
      ...this.props,
      callbackOnHighlightItem: this.onHighlight,
    });
    new Choices('.chosen-tag', { ...this.props });
  }

  onHighlight(k, v) {
    console.log('im a highligher');
    console.log(k, v);
  }
```

I can see the redux action firing but no callback is fired. am i missing something?

**Comment by jshjohnson** [comment]
Hmm, it's working for me. If you go to the [demo](https://joshuajohnson.co.uk/Choices/) page, open the console and click the items in the first input box, they should be firing (you may need to clear your cache to see the updated demo page). 

Are you getting any errors at all?

**Comment by jshjohnson** [comment]
Looking back at your code: you're assigning this.props and the callback to an empty object which is not passed to Choices. It seems you're only passing this.props?

**Comment by th3fallen** [comment]
good god..... man it sucks being stupid... lol that's exactly it...
