### ISSUE TITLE
Sort Selected Items Alphabetically

### ISSUE THREAD

**Issue by BackuPs** [jshjohnson/Choices#142]
Hi

Is is possible to sort the selected items alphabetically?  So if one selects from a drop down list London, Brussels, Amsterdam the select items appear as  Amsterdam, Brussels, London?

And how about having the selected items not in order of the list of selectable items?

suppose my ul li has  Amsterdam ,Brussels, London,  But the items are selected in London, Amsterdam, Brussels?

How do i set the selected items back in the order they where selected but keep the list of selectable items still alphabetically?

**Comment by jshjohnson** [comment]
Sure! 

See [here](https://github.com/jshjohnson/Choices#sortfilter) for information about the sortFilter config option.

Thanks
