### ISSUE TITLE
Bundling errors from mixing ES6 import/export and CommonJS module.exports

### ISSUE THREAD

**Issue by synapticism** [jshjohnson/Choices#144]
I am experimenting with importing ES6 source files from Choices into an environment setup for tree-shaking with Babel/Webpack. This is accomplished by *not* transforming CommonJS modules and relying solely on native ES6 import/export statements. Unfortunately Choices still has two `module.exports` calls in the source leading to the standard error message:

```Uncaught (in promise) TypeError: Cannot assign to read only property 'exports' of object '#<Object>'```

You'll find those `module.exports` calls [here](https://github.com/jshjohnson/Choices/blob/5c04638beff8d1f8ce0910db501880cf811c7c6d/assets/scripts/src/store/index.js#L164) and [here](https://github.com/jshjohnson/Choices/blob/64fd957b569bdbfb24231174c03d8308526955ca/assets/scripts/src/choices.js#L2306). With reference to [this thread](https://github.com/webpack/webpack/issues/4039) the problem appears to be that the two styles appear in the same file. Not mission critical but thought you should be aware. Thanks for the great work on this package!

**Comment by jshjohnson** [comment]
Hey @synapticism,

I think the real issue here is that you're including the source files rather than the compiled output. I think if I produce a compiled ES6 version of choices for each release, this should resolve your issue. 

I'll get this thread posted with progress
Thanks

**Comment by synapticism** [comment]
Yes, that's true, I tried compiling from source... this has the advantage of being able to knockout the polyfill bundle, or would if everything else were working ;)

Optimally this project would allow for compilation from ES6 source + tree-shaking to eliminate any unused features... but I understand that's much easier said than done, and this lib is already ahead of the curve in many respects!

**Comment by jshjohnson** [comment]
Hey @synapticism - would you mind testing out the `feature/es6-version` branch. Would be good to get some feedback.

Thanks

**Comment by synapticism** [comment]
I'll take a closer look later on but at first glance this is working fine! 👍

**Comment by tinovyatkin** [comment]
I think polyfills should be added at Webpack bundling level (maybe via concatenation if you want to), but not at the es6 source. Also, don't see the need to build separated ES6 version as you already have one and sources are included in your NPM distribution - just `export` the class will fix this issue.

**Comment by jshjohnson** [comment]
Closing this as I don't really think it's necessary :) The source file is the es6 version.
