### ISSUE TITLE
Option to let Choices fail silently?

### ISSUE THREAD

**Issue by danbruegge** [jshjohnson/Choices#146]
Can there be an option to let Choices fail silently if there is not element to select?

https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/choices.js#L193

I'll use Choices not on all pages. On every page with no `select` element, it throws the error message.

Regards, Dan

**Comment by jshjohnson** [comment]
As of [version 2.8.2](https://github.com/jshjohnson/Choices/releases/tag/v2.8.2), there is now a `silent` [config option](https://github.com/jshjohnson/Choices#silent) to suppress console messages :)
