### ISSUE TITLE
Allow search prevention for multi-select

### ISSUE THREAD

**Issue by ojensen5115** [jshjohnson/Choices#147]
I note that the 'search' option is only relevant to non-multi-select choices. This is a feature request to remove this restriction. It is particularly cumbersome when there are a relatively small number of options.

Currently I work around this as follows:

    var choices = new Choices(elem);
    choices.input.parentNode.removeChild(choices.input)

but it seems non-ideal to do have to do this outside of the Choices code.

**Comment by jshjohnson** [comment]
In your example, are you using a single select input?

**Comment by ojensen5115** [comment]
My use case involves a multi-select with a small number of options. The 'search' option (https://github.com/jshjohnson/Choices#search) is relevant for single-select inputs only, and thus is ignored for multi-select inputs. But it's a bit silly to have a text search when there are only e.g. 10 options.

**Comment by jshjohnson** [comment]
Ah ha! You have highlighted an issue in my documentation :D 

A search still works for a multiple select - see the example with the label 'Options from remote source' [here](https://joshuajohnson.co.uk/Choices)

**Comment by ojensen5115** [comment]
Searching does indeed work for multiple selects, but the configuration option is ignored and it's what I'm trying to *disable* (In the example you point to, I can still type to search). I have a small number of options in a multiselect, and I do not want the user to be able to type to search, so I pass `search: false` into the config. However, the user is still able to type to search. The only way I have found for removing the ability to search on a multiselect is via removing the search input field through DOM manipulation.

**Comment by jshjohnson** [comment]
Unfortunately if you remove the search input, you lose a lot of functionality (like deleting items, selecting all items etc) since the input is the only way (currently) of figuring out what Choices instance is in focus. 

That's why we have this at the beginning of `_onKeyDown`:
```js    
if (e.target !== this.input && !this.containerOuter.contains(e.target)) {
  return;
}
```

**Comment by ojensen5115** [comment]
Indeed, it's a hacky workaround, which is why I am hoping for a "right way" to prevent searching on multi-selects within Choices.

That being said, based on your description it sounds like this feature would be more work than it's worth. In my case my workaround is "good enough" (with a small number of options, being able to e.g. select-all isn't super important), so I'm happy to continue using it rather than hoping for official support.

**Comment by jshjohnson** [comment]
Going to close this as it's a big bit of work for not much benefit! Ill probably revisit this when/if I do a major rewrite. Thanks
