### ISSUE TITLE
Enable firing of 'change' event on text-input choices

### ISSUE THREAD

**Issue by ojensen5115** [jshjohnson/Choices#148]
Currently, the 'search' event is not triggered if the element passed to Choices is a text-input field, as `_handleSearch` is only called if `this.isTextElement` is false.

I'm trying to construct a Choices element on a text-input field which pulls suggestions from a remote server. My workaround for now is to attach a `keyup` event listener to the `.choices__input--cloned` child, but it would be more convenient to be able to listen for the search event.

**Comment by jshjohnson** [comment]
Hi @ojensen5115,

Although this is a small change, I think it would make the naming of the event a bit confusing. I'm wondering whether we should rename 'search' to just 'input' which would relate to all input types.

Either way, this is a simple change so I would be happy to review a pull request :)

Thanks

**Comment by jshjohnson** [comment]
Closing for now - will reopen if more people request it.

Thanks

**Comment by BeebBenjamin** [comment]
I would like this feature, 7 years later...
