### ISSUE TITLE
Off-by-one error on searchFloor?

### ISSUE THREAD

**Issue by ojensen5115** [jshjohnson/Choices#149]
I notice that if I do not pass in a searchFloor (and thus it defaults to 1), the search event fires only after the second character. More generally, when I pass a searchFloor of *n*, my search event fires only after *n+1* characters have been typed. Could this be an off-by-one error?

**Comment by jshjohnson** [comment]
Hi @ojensen5115,

Choices will only search if the search value is _greater_ than the search floor. Do you think this should be changed to greater _or_ equal to the search floor?

Thanks

**Comment by ojensen5115** [comment]
I think greater or equal would be more intuitive, for two reasons:

- The name searchFloor implies (to me) that it is the lowest number of characters which will trigger a search, which is not how it is implemented now.
- The default searchFloor of 1 results in (AFAIK) undocumented behavior of "search on" only searching when there are at least *two* characters.

That being said, if this was a conscious decision then I have no strong feelings one way or the other. But if it remains a strictly-greater check, then I would recommend changing the default search floor from 1 to 0, or documenting that by default search does not trigger until at least two characters are input.

**Comment by jshjohnson** [comment]
I have changed the behaviour in [version 2.8.2](https://github.com/jshjohnson/Choices/releases/tag/v2.8.2) so the searchFloor is greater _or_ equal to :)
