### ISSUE TITLE
[Select] Brower freezing with a large dataset of values

### ISSUE THREAD

**Issue by Aiso786** [jshjohnson/Choices#152]
Hello guys, We have an issue with a Select receiving a large amount of values (700 rows). It takes some time for the Select to render and meanwhile the browser is freezing.

Do you have an idea ? I have tried to look into the code. Disabling the sort in the configuration helps a little bit but the browser is still freezing.

Thank you very much for your help.

**Comment by jshjohnson** [comment]
Hi,

700 rows is a lot to show! That is always going to take a browser a long time to load. I would try fetching the results based on what a user is searching for.

Thanks

**Comment by Aiso786** [comment]
Hi, thanks for your reply 👍
