### ISSUE TITLE
Placeholder width

### ISSUE THREAD

**Issue by adammockor** [jshjohnson/Choices#154]
I got problems with computing placeholder width. See image below.

![screenshot 2017-05-03 16 47 56](https://cloud.githubusercontent.com/assets/1824790/25666543/1b3d16b6-3021-11e7-9381-78df5940f72a.png)

Problem is in `getWidthOfInput` function returning wrong value, because it's getting width from span attached directly to body element, not inside of choices container.

I can imagine 2 different solutions to this problem. Both can be implemented simultaniously.

1. Expose `setInputWidth(width)` to userland with optional width parameter, which can override computed value. So user can set width manualy after `callbackOnInit` for example.

2. Call `_setInputWidth` after input is mounted to DOM (now it's called before mounting in `_createInput`). When input is mounted we can get actual css with `window.getComputedStyle(this.input)` and apply to `testEl`. [Somthing like here](https://github.com/JedWatson/react-input-autosize/blob/master/src/AutosizeInput.js#L71).

I can PR this, but please tell me @jshjohnson which solution you prefer, or if you can think of something different.

**Comment by jshjohnson** [comment]
Oooo, solution 2 sounds sweet!

**Comment by jshjohnson** [comment]
Merged into placeholder feature branch
