### ISSUE TITLE
Option to prevent form submit on enter?

### ISSUE THREAD

**Issue by haheute** [jshjohnson/Choices#156]
Does Choices have an option to prevent form submit on enter?
When adding tags to a tag list, if a user accidently presses enter, the form is submitted without tags (or with some missing).

I have tried to add a function to my page, but it did not affect the `choices__input`s, since they are dynamically added to the page (?).
thanks for help

**Comment by jshjohnson** [comment]
Hi @haheute,

What type of input are you using? As a multiple select or a text input require the user to press enter to add items.

Thanks

**Comment by haheute** [comment]
Hi, yes it is a text input. Just thought one could add items with enter, but not submit the form when pressing enter while the cursor is in the input / the "press enter to add .." message is not visible. not sure
