### ISSUE TITLE
Multiple select limit not working properly

### ISSUE THREAD

**Issue by rajasimon** [jshjohnson/Choices#157]
I copied below code from https://joshuajohnson.co.uk/Choices/ 

```

<select name="choices-multiple-remote-fetch" id="choices-multiple-remote-fetch" multiple></select>


  var multipleFetch = new Choices('#choices-multiple-remote-fetch', {
    placeholder: true,
    placeholderValue: 'Pick an Strokes record',
    maxItemCount: 5,
  }).ajax(function(callback) {
    fetch('https://api.discogs.com/artists/55980/releases?token=QBRmstCkwXEvCjTclCpumbtNwvVkEzGAdELXyRyW')
    .then(function(response) {
      response.json().then(function(data) {
        callback(data.releases, 'title', 'title');
      });
    })
    .catch(function(error) {
      console.error(error);
    });
  });
```

The limit is not working. I installed this choices package using yarn. This installed 2.8 but I realised the example website uses 2.7 so I degraded to 2.7 and then also not working. But how come website select limit working?

**Comment by jshjohnson** [comment]
Hi! 

When you say not working, what do you mean? The maxItemCount should only let you select 5 items from the choices available, is that not working for you?

Thanks

**Comment by rajasimon** [comment]
I can select more than 5 items from the list. But it suppose to select only 5 item.

**Comment by jshjohnson** [comment]
Hi @rajasimon,

Apologies - it appeared a pull request caused an issue with this feature. I have pushed a new [version](https://github.com/jshjohnson/Choices/releases/tag/v2.8.1) that should resolve your problem. 

Thanks
