### ISSUE TITLE
Press to select not shown on initial click

### ISSUE THREAD

**Issue by freeman-g** [jshjohnson/Choices#159]
Hello, thanks for the plugin!

I've written a small Vue.js wrapper for choices.js and it is nearly working, however, when I click my example select, the `press to select` listener/label is not shown for the first item, therefore the user cannot hit the enter key and select the first item.

Additionally, if the user performs a search, the top result from the search also does not have the press to select label show.

I thought that should be a default behavior?

Here's a screenshot:

![image](https://cloud.githubusercontent.com/assets/495886/26078981/3b5db2a8-398f-11e7-97d7-ab105c649219.png)

Here's my vue.js wrapper code (Using ES6 + Webpack):

```
<template>
  <select ref="choices">
    <option selected disabled>This is a placeholder</option>
    <option value="1">Option 1</option>
  </select>
</template>

<script>
  import Choices from 'choices.js'

  export default {
    name: 'Choices',
    mounted: function () {
      var element = this.$refs['choices']
      // eslint-disable-next-line no-unused-vars
      var choices = new Choices(element, {})

      element.addEventListener('input', e => {
        this.$emit('input', e.target.value)
      })
    }
  }

</script>

<style src="choices.js/assets/styles/css/choices.min.css"></style>
```

Note:  If I hover my mouse of the the options, then I do see the `press to select` label.

**Comment by freeman-g** [comment]
Ok - my npm installed version of Choices.js was 2.8.0.  I noticed the latest commit message for 2.8.1, which I didn't find on npm yet, so I ran `npm install choices.js@2.7.8` and this resolved my issue.

**Comment by jshjohnson** [comment]
@freeman-g Apologies - there was a bug with version 2.8.0 that was resolved the day after! Please open source your Vue wrapper, I'll link to it from this repo. I'm sure people would use it :)

**Comment by Wisdom132** [comment]
thanks.this post was helpful

**Comment by Wisdom132** [comment]
I cant dynamically add options to the choicejs.
I am getting my information from a backend which i try to dynamically add to the option.

this is my choicejs
`mounted: function() {
    var element = this.$refs["choices"];
    var elements = this.$refs["choices2"];
    var choices = new Choices(element, {});
    var choices2 = new Choices(elements, {});

    element.addEventListener("input", e => {
      this.$emit("input", e.target.value);
    });
    elements.addEventListener("input", e => {
      this.$emit("input", e.target.value);
    });
  }
};`

and this is how i try to loop through my data
` <select ref="choices2">
                <option selected disabled>Categories</option>
                <option v-for="category in categories" :value="category.name" :key="category.id">{{category.name}}</option>
              </select>
            </div>`

but nothing is showing.
