### ISSUE TITLE
Don't commit built files in the repo

### ISSUE THREAD

**Issue by rstacruz** [jshjohnson/Choices#161]
Files like `assets/scripts/dist/choices.js` (and company) are needed to be rebuilt every time. This should not be the case.

## Fix

- Add `files` in package.json to whitelist all the files needed, but do NOT include `assets/scripts/dist/` in it.

- Add a `scripts.prepublish` in package.json to run `npm run js:build` (and whatever else is needed)

- Add `assets/scripts/dist/` to `.gitignore`

- Remove the files using `git rm -rf --cached assets/scripts/dist`

## What it does

The files will not be in the Git repository anymore.

They are, however, uploaded to npm. Just run `npm publish` and it will build the files and upload them to the npmjs.com registry.

**Comment by ojensen5115** [comment]
If the dist files are removed from the repo, what would be the best way for those who aren't using node to get the built files?

**Comment by jshjohnson** [comment]
/\ @ojensen5115 What he said

**Comment by ojensen5115** [comment]
I believe there is an option in Github to offer binary release downloads. If you wanted to remove the distfiles from the repo, you could put them there.

It'd be an extra step in your build process, and forgetting to update your binary release would mean that people downloading them would silently get an older version unless they thought to compare version numbers with the source code. I think it just comes down to whether keeping the built files out of the repo is worth it to you.

**Comment by jshjohnson** [comment]
I'm going to close this I can forsee me forgetting to do binary releases and I think it might confuse some people! Thanks

**Comment by rstacruz** [comment]
> If the dist files are removed from the repo, what would be the best way for those who aren't using node to get the built files?

@jshjohnson @ojensen5115 this is what unpkg.com is for. It's a CDN for files uploaded to npm (eg, your built files). For instance, React's is hosted over at:

> https://unpkg.com/react@15.3.1/dist/react.min.js

**Comment by rstacruz** [comment]
...by the way, I'm asking this because it'd be much easier for us who would occasionally maintain forks of Choices. We can't always easily contribute our fixes back, because PR's here should not have the dist files rebuilt.
