### ISSUE TITLE
Document use for dynamically filled options

### ISSUE THREAD

**Issue by ojensen5115** [jshjohnson/Choices#162]
The use case here is where you don't want to load all of the options (there may be tens of thousands), but you want to load options via ajax request when the user searches (similar to Select2's `ajax` option, and contrasting with Choices' `ajax` option which AFAIK only supports initial load of options). I believe this is a reasonably common use case, and found the method by which to accomplish this to be somewhat confusing, so I'm sharing my approach.

The key steps:

- Set up a listener on the `search` event to perform an ajax request which calls `.setChoices` on the results.
- In spite of listening for the `search` event, we must also *set searchChoices to false*. Basically, you don't want Choices to itself search the results sent back by the backend API, because it may (will) screw up the ordering: each newly created element will have the same default threshold, and because you are inside a search event, Choices will force a sort using this threshold as the ordering parameter. This sort will mostly be the identity operation for short lists, but will occasionally place elements arbitrarily.
- You will need to implement your own version of de-duplication if you need it. See https://github.com/jshjohnson/Choices/issues/150 for details.

The code:

```javascript
var config = {
    placeholderValue: 'Start typing a [whatever]',
    shouldSort: false,
    searchFloor: 2,        // or whatever value makes sense for your data / API
    searchChoices: false,  // see bullet point 2 above
    duplicateItems: false  // this is ignored, see bullet point 3 above
};

// Construct the Choices object.
var choices = new Choices(elem, config);

// Some config and bookkeeping for API calls.
var apiUrl = '...';
var lookupDelay = 100;
var lookupTimeout = null;
var lookupCache = {};

// Function to perform the API lookup.
var serverLookup = function() {
    // we can't use choices.currentValue because this is blank if we set searchChoices
    // to false. Instead we use the actual input field's value.
    var query = choices.input.value;
    if (query in lookupCache) {
        populateOptions(lookupCache[query]);
    } else {
        // Ajax query and results parsing depends on your API structure and how
        // you make AJAX calls in your codebase.
        ajax.post(apiUrl, {query: query}, function(event) {
            var results = event.target.getResponseJson();
            lookupCache[query] = results;
            populateOptions(results);
        }
};

// Function to actually populate the results from the API lookup.
var populateOptions = function(options) {
    // We have to cull duplicates ourselves here, because Choices doesn't do it for
    // us. There's probably a better way of doing this, but here's the easy way:
    var toRemove = [];
    for (var i = 0; i < choices.currentState.items.length; i++) {
        var item = choices.currentState.items[i];
        if (item.active) {
            toRemove.push(item.value);
        }
    }
    var toKeep = [];
    for (var i = 0; i < options.length; i++) {
        // However you check if an array contains something in your codebase.
        if (!array_contains(toRemove, result.id)) {
            toKeep.push(result);
        }
    }
    // Now actually set the (de-duped) results.
    choices.setChoices(toKeep, 'id', 'text', true);
};

// Trigger an API lookup when the user pauses after typing.
elem.addEventListener('search', function(event) {
    clearTimeout(lookupTimeout);
    lookupTimeout = setTimeout(serverLookup, lookupDelay);
});

// We want to clear the API-provided options when a choice is selected.
elem.addEventListener('choice', function(event) {
    choices.setChoices([], 'id', 'text', true);
});
```

**Comment by jshjohnson** [comment]
Hey, is there anything I could change/implement that would make this process easier?

**Comment by ojensen5115** [comment]
Unless you wanted to support this operation natively by building it into the plugin, probably the easiest thing thing to implement would be just to document this.

For those implementing this themselves, or for you in case you choose to implement it inside the plugin: another optimization that didn't make it into my above writeup above would be to prevent an API call on a sub-search of an incomplete result set. That is, if you receive max 20 results from the API and your search for "abcd" yields fewer than 20 results, then you can skip the API  call for "abcde" and just do the filter locally.

**Comment by sedatsevgili** [comment]
The way @ojensen5115 suggested works perfectly. However, if you have a custom template defined in callbackOnCreateTemplates, you have to call _createTemplates and render methods after setting choices like this:

```javascript
choices.setChoices(toKeep, 'id', 'text', true);
choices._createTemplates();
choices.render();
```

I know calling _createTemplates is a little hack but it works. If anyone knows more legal solution to render after this autocomplete process, i will be glad to see.

**Comment by Spone** [comment]
If you're using @ojensen5115 snippet above, be warned that in the current version of Choices.js, the following doesn't clear the choices:

`choices.setChoices([], 'id', 'text', true);`

see #545

**Comment by Spone** [comment]
If you're using @ojensen5115 snippet above, be warned that in the current version of Choices.js, the following doesn't clear the choices:

`choices.setChoices([], 'id', 'text', true);`

see #545

**Comment by 7even-ux** [comment]
Can someone help me regarding @ojensen5115  snippet. I try to use it and i am getting an error  " Cannot read property 'getResponseJson' of undefined". Or if you have other snippet to use for big amount of data from json.
 `var serverLookup = function() {
    // we can't use choices.currentValue because this is blank if we set searchChoices
    // to false. Instead we use the actual input field's value.
    var query = choices.input.value;
    if (query in lookupCache) {
        populateOptions(lookupCache[query]);
    } else {
        // Ajax query and results parsing depends on your API structure and how
        // you make AJAX calls in your codebase.
        $.post(apiUrl, {query: query}, function(event) {
            var results = event.target.getResponseJson();
            lookupCache[query] = results;
            populateOptions(results);
        }
)}
};`
