### ISSUE TITLE
Multiple pre-selected values in "Multiple select input"

### ISSUE THREAD

**Issue by benjick** [jshjohnson/Choices#165]
Is this possible? I see the ones using `<input type="text"` has the option of using `preset` to specify multiple chosen items, but I need to do this with the `<select>` version

**Comment by ojensen5115** [comment]
IIRC Choices handles this for you the simple way: just make your option have the `selected` attribute before constructing the Choices around your select.

**Comment by jshjohnson** [comment]
Hi @benjick,

There are three ways of doing this (one being the method @ojensen5115 mentioned):

- https://github.com/jshjohnson/Choices#choices
- https://github.com/jshjohnson/Choices#setchoiceschoices-value-label-replacechoices
