### ISSUE TITLE
Autocomplete for large dataset that delegate search to backend via Ajax

### ISSUE THREAD

**Issue by vanduynslagerp** [jshjohnson/Choices#169]
First of all, thanks for Choices, it's a great library !

Currently the Ajax option allow to preload data in the select, but I didn't find a way to create an Autocomplete/Typeahead feature that delegate the search to the backend via Ajax. Something similar to [typeahead.js](https://twitter.github.io/typeahead.js/) or to the "Remote source" exemple of [selectize.js](http://selectize.github.io/selectize.js/).

In case of a very large dataset, it's not practical to preload everything, so ideally we should be able to trigger an Ajax request, with the search input value as a parameter and display the results to the user.

Would you consider adding such feature to the library ?
Or would recommend to listen on the `search ` event, make the Ajax call, clear the choices and call `setChoices` with the Ajax call results ?

**Comment by jshjohnson** [comment]
Hey @vanduynslagerp,

Thanks! There is a good write-up here for handling this use case: https://github.com/jshjohnson/Choices/issues/162

**Comment by vanduynslagerp** [comment]
Thanks a lot! That answer my question.
Any plan to add such feature to Choices in a more integrated way ?

**Comment by jshjohnson** [comment]
If you have a particular thoughts for handling this, it would be really useful if you could comment on [this thread](https://github.com/jshjohnson/Choices/issues/162) with your opinions. I guess it makes more sense to develop a solution based around what the people want 👍.
