### ISSUE TITLE
Email example bug

### ISSUE THREAD

**Issue by holloway** [jshjohnson/Choices#17]
On https://joshuajohnson.co.uk/Choices/ under "Email addresses only" type the following

a@a.aa

the "Hit enter to" will appear, but just hit backspace to make the text input look like

a@a.a

And the "Hit enter to" will still be there but hitting enter won't do anything which is a bit confusing.

**Comment by jshjohnson** [comment]
This has been resolved as of version 1.0.52. 

Thanks!
