### ISSUE TITLE
Support for HTMLCollection

### ISSUE THREAD

**Issue by Vinorcola** [jshjohnson/Choices#171]
Make your constructor support HTMLCollection (returned by document.getElementByXXX() functions).
Currently, it seems to only support array of elements ;)

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCollection

**Comment by jshjohnson** [comment]
Closing for now - will reopen if more people request it.

Thanks

**Comment by chrisrowe** [comment]
I'm using `const choiceSelects = Array.from(document.getElementsByClassName('choices-select'))` to pass an array of elements, although that doesn't seem to work either.
