### ISSUE TITLE
Pasting from context menu does not work

### ISSUE THREAD

**Issue by Remcoman** [jshjohnson/Choices#174]
When i trigger a paste by right clicking on the choices.js text input and clicking paste, choices.js does not register it as a change and as a result no dropdown will be shown. Is this on purpose? It seems kinda strange.

**Comment by jshjohnson** [comment]
Hey @Remcoman, 

I agree that in this situation the dropdown should probably show. This would be pretty simple to change, we would just need to toggle the dropdown within the `_onPaste` method. I'd be happy to review a pull request!
