### ISSUE TITLE
Passing attributes from html data

### ISSUE THREAD

**Issue by kjugi** [jshjohnson/Choices#182]
Is there any support for `data` attributes from HTML? I want to pass the values on specific `select` item and only to it. Can't do it in JS by passing `id` or other attribute b/c it must me reusable element. And to all, I'm passing default values or same classes too. Can I in another way pass element 2 times or in 2 different ways? 

The best way is to pass `data` attributes to `select` and when calling `Choices` with default values add this custom one if existing and pass as parameters too.

If want some code can prepare something or show concept

**Comment by jshjohnson** [comment]
You can't currently add custom properties via HTML but as of [version 2.8.6](https://github.com/jshjohnson/Choices/releases/tag/v2.8.6), you can pass custom properties to [items](https://github.com/jshjohnson/Choices#items)/[choices](https://github.com/jshjohnson/Choices#choices) via JS . Will re-open this if more people request this.

**Comment by sergonius** [comment]
It would be nice if the plugin allowed passing additional classes at least. `<select class="item item--variation">....</select>` after initialised with `.item` selector will lose `item--variation`.

**Comment by ChristopherRobinSuperStar** [comment]
It is very nessesary and convenient to pass data-attributes. Please, add it.

**Comment by ericmuijs** [comment]
Can this one be reopened? It would like to have HTML data attribute support.

**Comment by valtermedeiros** [comment]
This is a must, especially if you are working with Livewire, PHP and Alpine.JS. It's a lot cleaner, I might push to this repo.

**Comment by pravin** [comment]
+1 to support this!
