### ISSUE TITLE
Allow choices property on text input

### ISSUE THREAD

**Issue by drcongo** [jshjohnson/Choices#183]
I'm trying to use Choices as a tags input, so the user can add new items to the input as in the first few examples on your demo page, but they can also select from existing options like the later examples on that page. As far as I can work out, Choices only does one or the other though and the `choices` property does nothing on a text input. Is this correct?

**Comment by jshjohnson** [comment]
Hey @drcongo, this is correct. There is an open PR for adding custom items to a multiple select inputs which would have been good for this situation but there has been issues in its implementation. See progress [here](https://github.com/jshjohnson/Choices/pull/190).

Thanks

**Comment by drcongo** [comment]
@jshjohnson Thanks for the info. I'd imagine using a text input for this kind of functionality would make way more sense than doing it on a multi-select though. Certainly if my backend (Flask / Django etc.) is expecting to validate the data coming back from the form, it'll be checking the data against the options it sent to the select to ensure there's nothing rogue in there.
