### ISSUE TITLE
Custom properties on selected items

### ISSUE THREAD

**Issue by JayKid** [jshjohnson/Choices#185]
Hi @jshjohnson,

Thanks for this awesome library, especially when it comes to the accessibility features 😍

However, when using the multiple-select with VoiceOver and going over the already selected items it just reads out "Remove Items" n times but not to what item the buttons actually correspond to.

This could be solved by creating a custom template with `aria-label="Remove item ${data.value}"` but one might need other data to use in the custom templates. The flexibility is there in the template but not when adding an item/choice as the reducer will handpick the attributes, not allowing for custom defined ones to go into the item/choice state.

I want to add other accessibility related attributes. I could create a PR that extends the reducers to take a `customProperties` attribute of the item that aggregates all properties defined by the user in an object so that they don't mix with the library ones.

What would you think?

**Comment by jshjohnson** [comment]
Hey @JayKid - this sounds like a great idea! Will happily review a PR

**Comment by JayKid** [comment]
@jshjohnson I'm on it :)

**Comment by jshjohnson** [comment]
FYI - as of version 2.8.5, the value is passed to an aria label like you suggested :)

**Comment by jshjohnson** [comment]
This has now been merged into version [2.8.6](https://github.com/jshjohnson/Choices/releases/tag/v2.8.6) 💯
