### ISSUE TITLE
Search unusable slow in IE 11

### ISSUE THREAD

**Issue by Yatekii** [jshjohnson/Choices#187]
Hi!

So I know I shouldn't be using as browser disguised crap but my company leaves me no choice.

First of all on IE 11 a polyfill for Object.assign() is required. That one was easy.
Then suddenly search works. But abysmally slow (1-2 seconds latency until the list is adjusted).
I first thought it's the forEach() which is 5-10 times slower in IE than in Chrome according to [benchmarks](https://jsperf.com/fast-array-foreach).
But in reality it seems having something to do with the .innerHTML according to the profiler:

![image](https://user-images.githubusercontent.com/529795/27472505-e4cc91da-57fb-11e7-9c70-068a06f51f0e.png)

I tried to do a profile in chrome too to see how it behaves. Funnily enough, as soon as I put on the profiler over there it too gets really slow; so that profile wouldn't be accurate.

When I started using Choices.js I already wondered how to have my own filtering function since using regexFilter didn't work at all (I guess it's only applied when selecting a Choice). Sadly it seems to have no docs how this is done. So I digged in the source and found a huuuuuuuge search algorithm/lib, which instantly made me discard that thought. I guess it is a problem of the bundler and in the sources it would be actually really easy to patch. I will have a look at it as soon as I have convinced my boss to use nodejs instead of that crap from Microsoft.

So because the buildup of the items list was so slow I tried to limit the number of results returned. Funnily enough the search seems to always return the entire list of choices in reordered fashion and not just .*<input>.* which makes no sense to me since it returns results that aren't even close to a match ...
Sadly this was really hard without having node here.
So I just limited the number of results:

```
	      for (var i = 0; i < 10; i++) {
	          var choice = choices[i];
	          var dropdownItem = _this3._getTemplate('choice', choice);
	          var shouldRender = _this3.passedElement.type === 'select-one' || !choice.selected;
	          if (shouldRender) {
	              choicesFragment.appendChild(dropdownItem);
	          }
	      }
	      //choices.forEach(function (choice) {
	      //  var dropdownItem = _this3._getTemplate('choice', choice);
	      //  var shouldRender = _this3.passedElement.type === 'select-one' || !choice.selected;
	      //  if (shouldRender) {
	      //    choicesFragment.appendChild(dropdownItem);
	      //  }
	      //});
```
This is not really nice and it would be awesome if there was some params to limit search results or even patch the search algorithm.

Besides some minor issues like this one Choices.js is really great, thanks for it!

Best regards
Yatekii

**Comment by jshjohnson** [comment]
Hi @Yatekii,

As of version 2.8.5, there is a now a [`searchResultLimit`](https://github.com/jshjohnson/Choices#searchresultlimit-4) which limits the amount of choices that are rendered - similar to your example :) 

FYI - Choices uses [Fuse](http://fusejs.io/) to manage search/filtering. You can pass Fuse config options to Choices via `fuseOptions` when you initialise. 

Thanks!
