### ISSUE TITLE
Trim displayed option

### ISSUE THREAD

**Issue by rolandtoth** [jshjohnson/Choices#188]
Is it possible to trim the displayed option's label? 

I have a select where indentation is set with non-breaking spaces, which looks fine in the options list but they are not needed when they are selected. Currently I do a simple replace in the core but it's not nice.

Ideally a new feature 'trim' or 'removeWhitespace' would be the best but perhaps it's possible with otherwise too.

**Comment by jshjohnson** [comment]
Hey @rolandtoth,

How are you adding options to Choices - via HTML or via the JS config? 

Thanks

**Comment by rolandtoth** [comment]
Via HTML, using Choices on an existing select tag.

**Comment by jshjohnson** [comment]
Personally, I think this should probably be handled before you pass data to Choices. I'm going to close this for now but will re-open if somebody else requests a similar feature. Thanks.
