### ISSUE TITLE
Doesn't work with huge amount of  data

### ISSUE THREAD

**Issue by jh88** [jshjohnson/Choices#189]
Here is an [exmaple](https://jsfiddle.net/hzey9yv8/5/), it only works with the small file. When I change to the bigger one, it just freezes.

**Comment by jshjohnson** [comment]
Hey @jh88,

Thanks for highlighting this - it certainly helped me pinpoint some performance bottlenecks. I am experimenting with the ability of "bulk" adding choices to reduce the browser workload which would stop this freeze. With that said, adding 4000+ elements to the page is always going to be slow to render. 

Thanks

**Comment by jshjohnson** [comment]
In the next release, there is the ability to limit the amount of Choices rendered which should hopefully significantly improve the performance. I'll post a comment when that release is launched.

**Comment by mikolajgrzyb** [comment]
Hey, @jshjohnson, 

I recently played with choices.js and noticed huge render issues even with 260 items. 
It's probably due to 1 by 1 addition of the choices (seen it in ajaxCallback function). What seems to be lacking is some 'bulkAddChoices' redux action that will just hit once the store and produce only one state change event. That will greatly increase rendering speed. 

I like the plugin very much and can't wait for the next release. Do you know when can we expect it? 

Cheers!

**Comment by jshjohnson** [comment]
Hey @mikolajgrzyb @jh88

The ability to [limit the amount of rendered Choices](https://github.com/jshjohnson/Choices#renderchoicelimit) was made available in [version 2.8.11](https://github.com/jshjohnson/Choices/releases/tag/v2.8.11).

I'm definitely going to look into bulk adding choices soon as quite a few people have requested it!

**Comment by mikolajgrzyb** [comment]
@jshjohnson Thanks, I missed that!

**Comment by MaksimShakavin** [comment]
Hi @jshjohnson ,
+1 for bulk adding choices. When I add 25 choices with replace option it calls render method 26 times, and even more, if some of them are selected. It takes 20 seconds! for IE to process this DOM modifications.

**Comment by wojciechczerniak** [comment]
+1 to reopen this issue

@jshjohnson  `renderChoiceLimit` is a nice addition but the UX looks odd. Only 10 (any number here) items are on the list. Are more not available to? Or they didn't load correctly? There is no scroll bar to indicate more options. 

I agree that 4000+ elements have to be handled in another way. But I've got 250 elements and this shouldn't create such a problem. After all it's just a country list in the shipping address. It's not that long list :confused:

**Comment by jshjohnson** [comment]
@wojciechczerniak @MaksimShakavin There is an open [PR](https://github.com/jshjohnson/Choices/pull/236) that resolves this issue but it won't go out until the next release (actively being worked on!)

**Comment by wojciechczerniak** [comment]
I've already tried that PR. It helps with performance but have other issues. Check my comment on the PR.

**Comment by alvarotrigo** [comment]
Select2 seems to deal properly with 400 items. 
Choices seems to lag a bit when selecting the option. It takes about 1 second to close the select box once selected.

Can it be related with the DOM structure too?

Select2 looks like this:
![image](https://user-images.githubusercontent.com/1706326/73284446-df283000-41f4-11ea-8415-434016af32c0.png)

While Choices like this:
![image](https://user-images.githubusercontent.com/1706326/73284476-eb13f200-41f4-11ea-9360-f8bc352a8143.png)
