### ISSUE TITLE
Mimicking Checkbox Behavior

### ISSUE THREAD

**Issue by vilav** [jshjohnson/Choices#19]
Hi there,

Choices looks like what I've been looking around for so long! Thanks for making it.
There are multi-select dropdowns, is there a way to have those options within a multiselect to be checkboxes instead of the current DIVs under a <select> tag?

Thanks!

**Comment by jshjohnson** [comment]
Thanks, I'm glad you like it! 

Currently there isn't a way to show checkboxes but it is certainly something I could add to the roadmap if people want it. My only reservation is that it doesn't follow the same behaviour as standard select boxes (which Choices attempts to follow as close as possible).

**Comment by vilav** [comment]
+1, Thanks Johnson! The reason I asked is that there's existing plugins out there that use checkboxes as inputs for things like sorting and filtering. And I find that Choices has very good UX to use along  with and solve the multi-faceted filtering experience.

Here's an example of a plugin called MixItUp. Works pretty well, though combined with Choices, it could elevate the filtering experience especially when there's more than a few selection options:

http://codepen.io/vlvgfx/pen/LkBoGz

**Comment by jshjohnson** [comment]
Closing as I think this should be it's own project built on top of Choices, rather than being part of Choices out the box.
