### ISSUE TITLE
Update readme regarding setValueByChoice

### ISSUE THREAD

**Issue by JayKid** [jshjohnson/Choices#192]
I wanted to set several options at once in a multiple select via the `setValueByChoice` method and by reading the docs I understood that it was not possible. However, when I went to modify the library to enable that, I saw that in the annotations of the method that it is possible indeed.

So I created a PR where I updated the readme for other people not to run into the same "problem" and open issues : )

Sorry for the nitpicking in advance!

**Comment by jshjohnson** [comment]
Thanks! Merged
