### ISSUE TITLE
How to get choices from external js file

### ISSUE THREAD

**Issue by Ruslan03492** [jshjohnson/Choices#194]
How to get choices from external js file?
For example Selectize.js element have property `$(this)[0].selectize` and i can work with object.
How to work with Choices object?

**Comment by jshjohnson** [comment]
Hey!

It depends how you have loaded Choices. If you have just put the script tag on your page, you will be able to access it via `window.Choices`, otherwise you will need to import it into a JS file e.g `import Choices from 'choices.js'.

Thanks

**Comment by jshjohnson** [comment]
If instead you want the object for a particular instance, you would do this:

```js
var example = new Choices(el);

console.log(example); // instance object here
```

**Comment by Ruslan03492** [comment]
Thanks, but how to call a specific choice?

**Comment by Ruslan03492** [comment]
Thanks! I am used.
```
var choices = new Choices('#' + index, value);
if (choices.initialised) {
   window.choiceObjects[index] = choices;
}
```
