### ISSUE TITLE
How to get choices from external js file

### ISSUE THREAD

**Issue by Ruslan03492** [jshjohnson/Choices#195]
Thanks, but how to call a specific choice from simple js (not react oe angular)?
I did this in one file:
```
var example = new Choices(el);
console.log(example); // instance object here
```
How to make it in another .js file? For example:
`example.showDropdown();`

**Comment by jshjohnson** [comment]
Hey,

I'm not entirely sure what you mean. If you need access to choices within a JS file, you would need to install it via npm (see the read me), and then import it at the top of your file

```import Choices from 'choices.js'```

**Comment by Ruslan03492** [comment]
I need the ability to change the current object in another js file
`var example = new Choices(el);`

**Comment by jshjohnson** [comment]
I'm still not really understanding your question, could you provide me more code detailing the issue please?

**Comment by grzegorztomasiak** [comment]
Well, Ruslan wants to instantiate Choices in .js file and then get that instance in another, however this is not Choices specific question but more architectural.

**Comment by jshjohnson** [comment]
Ah I see! Sorry. 

I agree, this is an architectural question. A Choices instance (like any other variable) is assigned to the enclosing scope it is within. If you must access it globally, assign the instance to the window (I wouldn't advise this though).
