### ISSUE TITLE
setValue doesn't pass along the custom properties when provided an object

### ISSUE THREAD

**Issue by JayKid** [jshjohnson/Choices#196]
Hi again @jshjohnson,

I discovered this while using the newly introduced custom properties. Basically, I introduced one parameter too much in a call to `_addItem` from `_addChoice` (here: https://github.com/jshjohnson/Choices/pull/191/commits/0b3cf1a355957194cb2a1cde8f5e4cd21d9111ab#diff-27edd04b91c69d5ee4cfac4012766ef7R2202) so the former doesn't get the custom properties and can't set them in the newly created item.

I created a PR which fixes that and contains a test to prevent it from happening again, sorry!

**Comment by jshjohnson** [comment]
Merged! Thanks
