### ISSUE TITLE
Input with autocomplete and custom value?

### ISSUE THREAD

**Issue by bartlenaerts** [jshjohnson/Choices#200]
Hi,

is it possible to have a `Choices` element with options added to it but also the possibility to enter a free value if it is not available in the list of options?

To describe it a little more, I'd like to start typing in a `Choices` component and a dropdown with predefined options is shown. I can select an option in the dropdown. But if the option I want is not there, the text that I typed in the `Choices` should be submitted to the form.

Thanks for your reply.

Bart

**Comment by jshjohnson** [comment]
Hey @bartlenaerts,

Currently that isn't possible but it has been requested before. There is a feature branch for it but it's proven more complicated than I expected!

Thanks

**Comment by miguelmota** [comment]
@bartlenaerts did you find an alternative that can do what you've described? I'm needing same feature

**Comment by bartlenaerts** [comment]
No sorry, no solution yet. We are using aurelia and are looking to build our own 'choices' as a native aurelia plugin.
