### ISSUE TITLE
Is there a CDN that hosts the JavaScript and CSS files?

### ISSUE THREAD

**Issue by ryanbuening** [jshjohnson/Choices#201]
Just wondering if a CDN is available for Choices. Thanks.

**Comment by jshjohnson** [comment]
Hey @ryanbuening,

Not as fair as I am aware. However it looks like Choices is going to be added to cdnjs.com [soon](https://github.com/cdnjs/cdnjs/pull/11493). 

Thanks

**Comment by dmreagan** [comment]
It's on [unpkg](https://unpkg.com/choices.js@2.8.11/).

**Comment by thangkieu** [comment]
Just wondering if a CDN is available for Choices CSS. Many thanks

**Comment by dmreagan** [comment]
https://unpkg.com/choices.js@3.0.4/assets/styles/css/
