### ISSUE TITLE
Choices.js will not update a value property which has been set on a text input before the plugin instance is created

### ISSUE THREAD

**Issue by jamin87** [jshjohnson/Choices#205]
I'm writing part of an interface which generates form elements using`document.createElement()`. Some of the form inputs will have existing values which are set using the `value` property (`inputDOMElement.value = 'some value'`).

This seems to work fine for `<select>` elements without any problems. With `<input type="text">` elements the plugin seems to render the existing value as an item just like it's supposed to but when you make a change to the items in the field and hit the submit button for the form none of the new changes reach the server.

I think I've tracked this down to Choices.js not overriding the original `value` property which is set when the element is created. The HTML `value` attribute is updated correctly, just not the DOM element `value` property.

**Comment by jshjohnson** [comment]
Hey, 

I've pushed a potential fix to this in [version 2.8.9](https://github.com/jshjohnson/Choices/releases/tag/v2.8.9). Let me know if the issue persists and I'll re-open this issue.

Thanks
