### ISSUE TITLE
Add Keycode value to the Events: choice, change...

### ISSUE THREAD

**Issue by oWallyson** [jshjohnson/Choices#207]
In a normal event call like below:
element.addEventListener('choice', function(event) {
  // do something creative here...
  console.log(event.detail.id);
  console.log(event.detail.value);
  console.log(event.detail.label);
  console.log(event.detail.groupValue);
}, false);

Is it possible to also include the keycode in the event.detail object like this:

element.addEventListener('choice', function(event) {
  // do something creative here...
  console.log(event.detail.id);
  console.log(event.detail.value);
  console.log(event.detail.label);
  console.log(event.detail.groupValue);
 **console.log(event.detail.keycode);**
}, false);

I would love to know when a user has hit the "enter" key when selecting a choice.  After looking through the code it doesn't seem too difficult; adding keycode to the triggerEvent/triggerChange.

Thanks

**Comment by jshjohnson** [comment]
Hey!

I'd be happy to review a pull request for this. Sounds like a good idea.

Thanks

**Comment by jshjohnson** [comment]
This will be in the next release 👍
