### ISSUE TITLE
Missing hideDropdown(), showDropdown(), toggleDropdown, 

### ISSUE THREAD

**Issue by rasben** [jshjohnson/Choices#210]
Apologises if I'm misunderstanding something here, but I dont seem to be able to use the following functions on my `select multiple`:

```
choices.hideDropdown()
choices.showDropdown()
choices.toggleDropdown()
```

They dont seem to be defined:

`console.log(choices)`
![screen shot 2017-07-19 at 13 32 10](https://user-images.githubusercontent.com/12376583/28364945-e611ca2a-6c86-11e7-9e9b-8a295e4b5fb3.png)

**Comment by jshjohnson** [comment]
Hey @rasben,

That is odd. Could you please let me know what version you are using and send me your config.

Thanks

**Comment by rasben** [comment]
(NPM)
`"choices.js": "^2.8.7",`

```
  const select = element.querySelector('select');

  const choices = new Choices(select, {
    removeItemButton: true,
    maxItemCount: 0,
    resetScrollPosition: false,
    noResultsText: '{{ control.multiChoice.noResultsText | translate }}',
    noChoicesText: '{{ control.multiChoice.noChoicesText | translate }}',
    itemSelectText: '{{ control.multiChoice.itemSelectText | translate }}',
    // eslint-disable-next-line arrow-body-style
    addItemText: (value) => {
      return `{{ control.multiChoice.addItemTextPrefix | translate }} <b>"${value}"</b>`;
    },
    // eslint-disable-next-line arrow-body-style
    maxItemText: (maxItemCount) => {
      return `{{ control.multiChoice.maxItemTextPrefix | translate }} ${maxItemCount} {{ control.multiChoice.maxItemTextSuffix | translate }}`;
    },
  });
```

Just see the {{ 'whatever'|translate }} as strings :)

Thanks for quick answer @jshjohnson

**Comment by jshjohnson** [comment]
Ah! I know why. 

The methods you mentioned are assigned to the Choices class (Choices.prototype) instead of the instance. Methods like destroy, disable, render etc are binded to that particular instance.

Thanks

**Comment by jshjohnson** [comment]
Thanks for raising this though, really only `render` needs to be binded to the instance!

**Comment by rasben** [comment]
Thanks for the super quick answer @jshjohnson , I'll look into the prototype thing :)

Why would i only need to bind render? All the settings im sending along are options to the element..?

**Comment by jshjohnson** [comment]
Sorry, I worded that badly! You wouldn't need to bind anything. I mean the library should only bind `render` as it is needed for Redux to do its thing :)

**Comment by rasben** [comment]
Ahh! Got it :) Thanks!

**Comment by jshjohnson** [comment]
By the way, you can still call hideDropdown etc like this:

`instance.hideDropdown()` 

You don't need to do:

`instance.prototype.hideDropdown`

**Comment by rasben** [comment]
What is `instance` in this case? Sorry if im being daft @jshjohnson

**Comment by jshjohnson** [comment]
Not a daft question :) 

Your instance is where you initiate Choices like the following:

```
var instance = new Choices():

instance.hideDropdown();
instance.hightlightAll(); // etc
```

**Comment by rasben** [comment]
I feel like we've gone full circle now - the original issue was that i couldnt do just that?

E.g.
`const choices = new Choices(select, { BLA BLA }); `

`choices.hideDropdown()` did nothing?

**Comment by jshjohnson** [comment]
Haha. It may have done nothing because the dropdown was already closed?

If you look at the source of the demo [page](https://joshuajohnson.co.uk/Choices/), you can see how these methods are being called.

There is also more info [here](https://github.com/jshjohnson/Choices#methods).

**Comment by rasben** [comment]
...I'm the biggest idiot in the world..

I was binding hideDropdown() to be when you clicked on the choices element.. but of course that is bound to toggle by the core code..

derp.. I fixed it by making a psuedo element

Sorry for the roundabout discussion :)

Btw i'm really impressed with this module - it's so well rounded and awesome!
Here's my final result (with the offending close button :))

![screen shot 2017-07-19 at 15 07 25](https://user-images.githubusercontent.com/12376583/28368878-311c17dc-6c96-11e7-8b1c-82531f62d01e.png)

Thank you again!

**Comment by jshjohnson** [comment]
No worries - Looks good man!
