### ISSUE TITLE
Uncaught TypeError: Cannot read property 'keyCode' of undefined

### ISSUE THREAD

**Issue by benjaminprojas** [jshjohnson/Choices#212]
This seems to only happen on multiselect boxes that are initialized without any selections. This issue happens on your demo site and I am also experiencing it myself. The following screencast shows it happening.

http://cloud.supportally.com/16322Y273Z1h

**Comment by chekovsky** [comment]
This also happen with predefined options. Steps do simulate this issue using the demo site:

1: Go to the **Options from remote source (XHR) & remove button** example
2: Select one of the options
3: Click the "x" button to remove the selected option
4: Try to select another option (this will throw the error)

The example above is using ajax, but a simple select with predefined options will trigger the error as well.

**Comment by jshjohnson** [comment]
I've pushed a fixed in [version 2.8.10](https://github.com/jshjohnson/Choices/releases/tag/v2.8.10) - sorry everyone!

**Comment by benjaminprojas** [comment]
Thanks @jshjohnson! will test this out tonight.

**Comment by chekovsky** [comment]
Hi @jshjohnson !

Can you publish 2.8.10?

Thanks!

**Comment by jshjohnson** [comment]
Done!
