### ISSUE TITLE
Object.assign is not available in IE and older browsers

### ISSUE THREAD

**Issue by JayKid** [jshjohnson/Choices#213]
Hi Josh,

I found this out while looking at error logs (IE..)
 
I created a PR that adds the MDN polyfill for Object.assign() to your set of polyfills,

Cheers :)

**Comment by acoiro** [comment]
@jshjohnson You probably want to add `Object.assign` to "Features used in Choices" at https://github.com/jshjohnson/Choices#browser-compatibility

**Comment by jshjohnson** [comment]
@acoiro Done!
