### ISSUE TITLE
Can we have the possibility to render only the N first choices?

### ISSUE THREAD

**Issue by flaviooliveri** [jshjohnson/Choices#215]
The idea is to limit the number of choices in the dropdown. Render only the first, for example, 20 and use the search for the rest. I have 400 choices and it's really slow but I can use something like that. I did a hack in the renderChoice method but it would be nice to have support for it with an option.

**Comment by jshjohnson** [comment]
Hey - I've just pushed this feature in master, it will be included in the next release :) I'll comment when that's launched.

**Comment by flaviooliveri** [comment]
Thanks!
