### ISSUE TITLE
Single select without a default selected option

### ISSUE THREAD

**Issue by rafaelrenanpacheco** [jshjohnson/Choices#217]
Hi there!

This issue actually talks about two issues. The first one is about setting up Choices.js to not pre-select a default option. For example, if I have the following select:

```html
<select placeholder="Search">
  <option value="one">One</option>
  <option value="two">Two</option>
  <option value="three">Three</option>
</select>
```

The result will be the first value to be pre-selected by choices.js, without a option to say otherwise, like this:

![screenshot from 2017-07-24 15-11-16](https://user-images.githubusercontent.com/12160864/28537782-6cec5368-7082-11e7-9940-a26d953d08c0.png)

Let's say this is an optional field, so it must not be pre-selected. The solution I found was to call `removeActiveItems()` on the select, which worked to empty the selected option, but resulted in a placeholder bug. After removing the active item, the select component did not show the placeholder anymore, like this:

![screenshot from 2017-07-24 15-14-23](https://user-images.githubusercontent.com/12160864/28537914-d1d81226-7082-11e7-849b-5afcbcd70cff.png)

Also, if the select component has no option to select, the placeholder is not shown as well.

The only way to show the input placeholder is to remove the active item by pressing the "Remove" button with a pre-selected option. This way the placeholder shows as expected:

![screenshot from 2017-07-24 15-16-19](https://user-images.githubusercontent.com/12160864/28538005-15e39f9e-7083-11e7-97f0-7de1be58f98a.png)

Is there a way to setup choices.js to not pre-select any options? Also, how to always show a placeholder, even if there is not option to select from?

Best regards,
Rafael Pacheco.

**Comment by sergonius** [comment]
Yeah, the placeholder only shows in the search input when the Choices is opened up which is not expected behaviour IMO.

**Comment by rafaelrenanpacheco** [comment]
Perfect, thank you very much 😁
