### ISSUE TITLE
Having empty choices array in settings produces weird results

### ISSUE THREAD

**Issue by sergonius** [jshjohnson/Choices#220]
I store default settings in a `defaultSettings` variable (all available settings) and when I call Choices I merge them with the passed settings.
The `choices` option in `defaultSettings` is an empty array.

What happens is that all the choices are in some way combined for all instances except one.
It took me a while to figure it out and the outcome is quite weird.

Simple test case:

```pug
select
  option(value="1") One
select
  option(value="2") Two
select
  option(value="3") Three
```

```javascript
new Choices('select', { choices: [] });
```

**Comment by jshjohnson** [comment]
This sounds like a bug, let me investigate 👍
