### ISSUE TITLE
Option as part of a multi-select has defaultSelected set to true even though the value is not selected by default

### ISSUE THREAD

**Issue by tomalexhughes** [jshjohnson/Choices#221]
I have a multi-select that uses Choices. 

When I select values from the multi-select the options are generated with a defaultSelected property set to true.

I want the option to become selected, with a defaultSelected value of false, to indicate that the value is now selected but was not originally selected.

Even with selected set to false within my array of choices, they are still rendered with defaultSelected as true.

Is this a bug, or am I missing a setting that can be used?
```

    for (let i = 0; i < this.data.length; i++) {
      choices.push({value: this.data[i].Id, label: this.data[i].Name, selected: false})
    }

    field.setChoices(choices, 'value', 'label', true);
```

**Comment by jshjohnson** [comment]
Hey - did you find a solution to your problem?
