### ISSUE TITLE
Why doesn't Choices.js select the "selected" item?

### ISSUE THREAD

**Issue by matthew-dean** [jshjohnson/Choices#225]
When passing in a `<select>` element to Choices, the item that is selected doesn't actually show up. Instead it seems to add placeholder text from an associated label as an item in the dropdown?

For example:
![screen shot 2017-08-14 at 3 12 34 pm](https://user-images.githubusercontent.com/414752/29294203-0c5d63d4-8103-11e7-907c-2571bdc97a87.png)
"Country" is not one of my options. It's just on the associated label. "Canada" is pre-selected but it doesn't show by default. How do I prevent "Country" from being added to the dropdown, and also prevent it from being pre-selected?

**Comment by jshjohnson** [comment]
Hey, could you please send me the HTML of your select box and your Choices config?

Thanks

**Comment by jshjohnson** [comment]
I think I have the bug causing your pre-selected option to not be selected but I'm baffled as to how your label is being added to the choice list!

**Comment by matthew-dean** [comment]
@jshjohnson I'll see if I can pull together a test case.

**Comment by matthew-dean** [comment]
Never mind, this was a weird behavior caused by a float labels library. See: https://github.com/geminilabs/float-labels.js/issues/9

**Comment by pryley** [comment]
@matthew-dean see: https://github.com/geminilabs/float-labels.js/issues/9#issuecomment-323543729
