### ISSUE TITLE
Call this._handleLoadingState(false) inside requestAnimationFrame callback

### ISSUE THREAD

**Issue by marzubov** [jshjohnson/Choices#226]
I've noticed(especially on mobile Safari) that sometimes loading text doesn't disappear.

After some debugging, I've found that `this._handleLoadingState(true)` could run after ajax callback which calls directly `this._handleLoadingState(false)`.
Calling ajax callback inside `requestAnimationFrame` fixed an issue.

What do you think about calling `this._handleLoadingState(false)` inside `requestAnimationFrame` it should remove the possibility of calling `this._handleLoadingState(true)` after `this._handleLoadingState(false)`.

**Comment by jshjohnson** [comment]
Hey @marzubov,

Do you mean like this?

```js
requestAnimationFrame(() => {
  this._handleLoadingState(true);
  fn(this._ajaxCallback());
  this._handleLoadingState(false);
});
```

**Comment by marzubov** [comment]
Hi @jshjohnson,

In your example, `this._handleLoadingState(false);` is redundant, because the loading state will be shown and then will be removed instantly.

I was thinking about updating [this line](https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/choices.js#L1406) to something like this:
```js
requestAnimationFrame(() => {
  this._handleLoadingState(false);
});
```
