### ISSUE TITLE
Why not provide a file without sourcemap?

### ISSUE THREAD

**Issue by lion-man44** [jshjohnson/Choices#228]
Since sourcemap does not need it in the production, I think that it should provide a file that does not contain it.

For example:
Provide sourcemap `assets/scripts/dist/choices.js`
Not provide sourcemap `assets/scripts/dist/choices.min.js`

```js
// webpack.config.prod.js
var config = {
  devtool: minimize ? false : 'cheap-module-source-map',
  entry: [
  ...
```

**Comment by jshjohnson** [comment]
Hey @lion-man44,

Makes sense, would you mind submitting a PR for this? I'll be happy to review it :)

**Comment by lion-man44** [comment]
@jshjohnson 
OK, sent you PR :)
https://github.com/jshjohnson/Choices/pull/230 

Please review 😃

**Comment by lion-man44** [comment]
This issue is closing.
If there is a problem, please reopen it.
