### ISSUE TITLE
Can't select text with a mouse

### ISSUE THREAD

**Issue by cjwelborn** [jshjohnson/Choices#23]
I saw your post on [/r/coolgithubprojects](https://www.reddit.com/r/coolgithubprojects/comments/4viu8h/choicesjs_a_vanilla_js_customisable_select/). I noticed on your [demo page](https://joshuajohnson.co.uk/Choices/), using `Chrome 52.0.2743.82`, that selecting text doesn't work with the mouse. I can use the keyboard (shift + arrow keys), and `Select All` from the context menu, but the only mouse functionality available is `focus`. It won't even move the cursor around between characters.

**Comment by jshjohnson** [comment]
Good spot, thanks. I'll look into this ASAP

**Comment by jshjohnson** [comment]
This has been resolved as of version 1.1.0. Thanks!
