### ISSUE TITLE
There is a way to clear any selection made?

### ISSUE THREAD

**Issue by pateketrueke** [jshjohnson/Choices#231]
I have a native `<select>`, when I pick an option I store the value and reset its `selectedIndex`, just because the first element is just a placeholder with no value.

I tried to achieve the same with Choices, but I didn't found yet any method to clear the selection, everything else is fine. 👍 

Edit: even a method for selecting the placeholder would be enough too. Or an option for disabling Choices from changing anything (but keep the events for capture `choice`, etc.)

**Comment by jshjohnson** [comment]
Hi @pateketrueke,

Could you comment with your Choices setup so I can get a better understanding of what you mean please :)

**Comment by pateketrueke** [comment]
Well, I did this:

```js
const $select = document.querySelector('select');
$select.addEventListener('change', e => {
  console.log(e.target.value); // do domething with the value
  e.target.selectedIndex = 0; // the first <option> is just a aplceholder
});
```

I tried to replicate the same with Choices but I have no luck.

**Comment by jshjohnson** [comment]
So are you just trying to reselect the placeholder choice (first element in dropdown) after each selection?

**Comment by pateketrueke** [comment]
That's exactly what I'm looking for...

**Comment by jshjohnson** [comment]
You could use [`setValueByChoice`](https://github.com/jshjohnson/Choices#setvaluebychoicevalue) if you know the value of the placeholder. 

I would be happy to review a pull request where this method could also take an index!
