### ISSUE TITLE
Hide/Show/Toggle not working

### ISSUE THREAD

**Issue by Nuuou** [jshjohnson/Choices#237]
Simple toggle demo, using Choices 3.0.2 and the choices.css file:
https://codepen.io/Nuuou/pen/PKBWQg/

Clicking on the "Toggle" button above the `select-multiple` field should simply toggle the dropdown. However, nothing appears to happen.

I've also tested this with the `hideDropdown()` and `showDropdown()` methods, and neither seem to work either.

Am I missing something obvious, or is this an actual bug?

**Comment by jshjohnson** [comment]
Hi @Nuuou,

Hmm, this looks to be a bug. Let me investigate

**Comment by 0190** [comment]
It does work if you wrap the `toggleDropdown()` in a setTimeout function. Same for `hideDropdown()` and `showDropdown()`.

https://codepen.io/0190/pen/QqJzvp

**Comment by Nuuou** [comment]
That certainly is interesting. It's as though the `toggleDropdown()` logic isn't correctly checking whether or not the dropdown is actually "open", so it's always trying to re-open it. Dunno for sure though!

To demonstrate slightly, I've added custom toggle logic. You're right that a `setTimeout()` is needed for this to work properly.
https://codepen.io/Nuuou/pen/jGJadR

**Comment by renatodeleao** [comment]
Also having same behaviour. @Nuuou  and @0190 thanks for your workarounds: it feels _dirty_ to use timeouts for this, but it works as a patch for now 👍.

**Comment by renatodeleao** [comment]
Just an add-on to the case: Programmatic opening also doesn't trigger focus on search input, thus disabling keyboard interaction.

You can add  `choicesInstance.input.focus()` after the `choicesInstance.showDropdown()` but then you can't close it by pressing the `toggle` button again.

Test: https://codepen.io/ohsimtabem/pen/aqwXPG

As a workaround, adding `pointer-events: none` to `toggle` and then remove it on `hideDropdown` event does the trick

Demo: https://codepen.io/ohsimtabem/pen/RQgvqm

**Comment by ingmferrer** [comment]
Same issue. Thanks for the workaround.

I hope this get fixed soon @jshjohnson
