### ISSUE TITLE
Mistake url: Polyfill example used for the demo 😇

### ISSUE THREAD

**Issue by retyui** [jshjohnson/Choices#239]
https://github.com/jshjohnson/Choices#browser-compatibility
plz update example url 💪
![](https://pp.userapi.com/c836736/v836736266/61f70/JRlS8sJKHhY.jpg)
```js
/* No polyfills found for current settings */
```

**Comment by jshjohnson** [comment]
Hey @retyui,

Polyfill.io only loads polyfills if your browser requires them! :)

**Comment by retyui** [comment]
omg 
it is amazing 😍😍😍
