### ISSUE TITLE
Get customProperties from AJAX request

### ISSUE THREAD

**Issue by MaksimShakavin** [jshjohnson/Choices#242]
First of all, thanks for the awesome library on ES6 without JQuery. It is a pleasure to work with its API. 
I faced a problem with customProperties. I use it with each choice to display some additional description. Is it possible to  get from AJAX response not only the value and label, but also this custom property?

Thanks

**Comment by MaksimShakavin** [comment]
I found out myself, that I can pass customProperties as a result attribute in ajax_callback

**Comment by gmask** [comment]
Here's an example using Laravel:

```
public function exampleFunction()
{
    $customerQuery = Customer::select('id', 'name', 'city', 'state')
        ->where('name', 'LIKE', '%' . request('q') . '%')
        ->get();

    $customers = $customerQuery->map(function ($customer) {
        return [
            'id' => $customer->id,
            'name' => $customer->name,
            'customProperties' => [
                'city' => $customer->city,
                'state' => $customer->state,
            ],
        ];
    });

    return response()->json($customers);
}
```
