### ISSUE TITLE
Why is the TypeScript definition file not included in the NPM package?

### ISSUE THREAD

**Issue by nbokmans** [jshjohnson/Choices#243]
As the title says. I am adding `choices.js` `^3.0.2` to my package json but the typescript definition file is missing. I can see it exists on this Github. Currently I have to manually add the TS defintinion file to my project and include a reference to that in my script. 

I would like the node package manager to actually include the typescript definition file. The `package.json` seems to point to the typescript definition file, so I assume the file is not supposed to be missing from the package.

**Comment by jshjohnson** [comment]
Ah good spot, i'm happy to review a PR to fix this 👍
