### ISSUE TITLE
Flipping is not working in IE11

### ISSUE THREAD

**Issue by MaksimShakavin** [jshjohnson/Choices#246]
Dropdown don't flip in IE, because IE don't support window.scrollY
https://github.com/jshjohnson/Choices/blob/2c4a74496a2236217a588363952ccdea8d7e98d1/assets/scripts/src/choices.js#L762

I created a[ pull request](https://github.com/jshjohnson/Choices/pull/244), that fixes this issue.

**Comment by jshjohnson** [comment]
Closing as PR has been merged - this will go out in the next release :)
