### ISSUE TITLE
Templates as pure functions

### ISSUE THREAD

**Issue by adammockor** [jshjohnson/Choices#250]
In my opinion, template functions should not use `this`, but everything should by passed via function arguments.

Because if you want to add style attribute to `choiceList` e.g., there is no way to mimmic default behavior of `choiceList` template, because there is no `this.isSelectOneElement` available when you passing function to `callbackOnCreateTemplates`.

**Comment by jshjohnson** [comment]
This will be implemented in the next release - you can track it here: https://github.com/jshjohnson/Choices/pull/227 👍
