### ISSUE TITLE
Hide placeholder when something is selected in multiple-select

### ISSUE THREAD

**Issue by 0190** [jshjohnson/Choices#251]
I'm looking for an option to show placeholder on multiple-select, but only when nothing is chosen. It could be a default value that is only present when user haven't selected anything. I looked through the docs, examples and other issues and haven't found anything. Is something like this possible?

(and thanks for an awesome plugin!)

**Comment by miguelfrmn** [comment]
@mklimkin0190 try something like this:

```
window.addEventListener('load', function() {
    const element = document.querySelector('#choice');
    const choices = new Choices(element);
    element.addEventListener('change', function() {
        let inputElm = choices.input.element;
        if (this.value) {
            inputElm.placeholder = '';
        } else {
            inputElm.placeholder = 'Me es indiferente';
            inputElm.style.minWidth = inputElm.placeholder.length + 'ch';
        }
    });
});
```
