### ISSUE TITLE
renderSelectedChoices doesn't working with groups

### ISSUE THREAD

**Issue by NetanelBasal** [jshjohnson/Choices#253]
Hey,

I am trying to use the group option with `renderSelectedChoices` set to `always`, and it's not working. 

```js
 choicesGroup = [ {
    label: 'Group one',
    id: 1,
    choices: [
      {value: 'Child One', label: 'Child One'},
      {value: 'Child Two', label: 'Child Two'},
    ]
  },
    {
      label: 'Group two',
      id: 2,
      choices: [
        {value: 'Child Four', label: 'Child Four'}
      ]
    } ];

this.choices.setChoices(choicesGroup, this.valueKey, this.labelKey, true);

```

When I select an item, it disappears from the list. I can confirm it is working with the following example:

```js
const choices = [
  {value: 'One', label: 'Label One'},
  {value: 'Two', label: 'Label Two'},
  {value: 'Three', label: 'Label Three'},
];
this.choices.setChoices(choices, this.valueKey, this.labelKey, true);

```

It seems there is a bug when using groups or I am missing something? 
Thanks.

**Comment by maximmig** [comment]
I confirm this bug. I'll create a PR to fix it as soon as my current PR gets accepted or rejected. Thanks!

**Comment by m-grzybek-first10** [comment]
Did someone pick this up ?

**Comment by m-grzybek-first10** [comment]
I could give it a go

**Comment by jshjohnson** [comment]
I believe this has now been resolved 👍
