### ISSUE TITLE
Add CSS class to a selected item

### ISSUE THREAD

**Issue by NetanelBasal** [jshjohnson/Choices#258]
Hey,

I need to add specific style to the **selected** item in the list. There is a way to do this? I didn't found any special class for this. 

Maybe something like this:
`<div class="choices__item choices__item--selected"></div>`

I think it's essential functionality.

**Comment by jshjohnson** [comment]
Hi, what kind of input are you using (text/select)?

**Comment by NetanelBasal** [comment]
Simple selects. There is no way to style the **active** choice in the list.

**Comment by jshjohnson** [comment]
This is possible if you pass a custom template for an `item`. See here: https://github.com/jshjohnson/Choices#callbackoncreatetemplates

All data related to the selected item is passed through as an object.

**Comment by NetanelBasal** [comment]
What I mean is something like that by default. 

```js
  choice: (data) => {
        return template(`
          <div class="${data.selected ? 'choices__is-selected' : ''}" }> ${data.label}
          </div>
        `);
   },
```

So I can style the active element.

```css
.choices__is-selected {
   ...
}
```

**Comment by ylemberg** [comment]
Ah gotcha, yes agreed I think it would be preferred to be set up that way in the `classNames` config object
