### ISSUE TITLE
TypeScript definitions not included with npm, though fix seems to have been merged

### ISSUE THREAD

**Issue by nerfpops** [jshjohnson/Choices#260]
Just installed 3.0.2 but Index.d.ts is not included.

Is the fix part of an upcoming release?

**Comment by zackschuster** [comment]
yes. the original types weren't being shipped, but @yannicsmeets helpfully [fixed that](https://github.com/jshjohnson/Choices/commit/3ab9bca6e68a8b3d9763c9403e3dbdcac9f9ea4e). we're just waiting on @jshjohnson to ship the next release.
