### ISSUE TITLE
Ability to manipulate text for selected choices

### ISSUE THREAD

**Issue by ataylor32** [jshjohnson/Choices#262]
My goal is to use Choices.js to allow the user to choose multiple categories, but the categories are in a hierarchical structure, like this:

```html
<select name="categories" id="id_categories" multiple>
  <option value="1">Parent Category</option>
  <option value="2">--- Child Category</option>
  <option value="3">------ Grandchild category</option>
  <option value="4">A Second Top Level Category</option>
</select>
```

I would like to make it so that if the user chooses the "--- Child Category" option that it appears in their list of selected choices as "Parent Category > Child Category" rather than "--- Child Category". I looked through the README and it doesn't look like this is currently possible, though I may have missed it. Would you consider adding the ability to manipulate the text?

**Comment by maximmig** [comment]
Please see here: https://jsfiddle.net/maximmig/x4hjsdzw/1/

**Comment by ataylor32** [comment]
@maximmig That works! Thank you very much for putting that together!
