### ISSUE TITLE
Allow browsers' built-in feedback when users don't fill out required fields

### ISSUE THREAD

**Issue by ataylor32** [jshjohnson/Choices#263]
Modern browsers will let the user know if they submit a form without filling out a required field. Choices.js doesn't show this, so the user might be confused, wondering why the form isn't submitting. Here is an example:

![choices-required](https://user-images.githubusercontent.com/1054222/30726712-b977ec96-9f09-11e7-8984-073682b8c4bc.gif)

And here is the code for the example:

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Required Field Test</title>
    <link href="https://cdn.rawgit.com/jshjohnson/Choices/4c080cdc/assets/styles/css/choices.min.css" rel="stylesheet">
    <style>
      form {
        max-width: 200px;
      }
    </style>
  </head>
  <body>
    <h1>Normal Select</h1>

    <form>
      <select required>
        <option value="">---------</option>
        <option value="foo">Foo</option>
        <option value="bar">Bar</option>
      </select>
      <button type="submit">Submit</button>
    </form>

    <h1>Choices Select</h1>

    <form>
      <select id="select_choices" required>
        <option value="">---------</option>
        <option value="foo">Foo</option>
        <option value="bar">Bar</option>
      </select>
      <button type="submit">Submit</button>
    </form>

    <script src="https://cdn.rawgit.com/jshjohnson/Choices/4c080cdc/assets/scripts/dist/choices.min.js"></script>
    <script>
      new Choices('#select_choices');
    </script>
  </body>
</html>
```

**Comment by jshjohnson** [comment]
I'm not sure this is actually possible. I imagine for the error message to display, the original element would need to be visible. Will reopen if anybody knows a way of achieving this.

**Comment by ataylor32** [comment]
What if you apply this CSS to the original element (instead of `display: none`)?:

```css
position: absolute;
opacity: 0;
pointer-events: none;
```

**Comment by tegola** [comment]
@ataylor32 suggestion works well with the single selection:

![schermata 2018-02-28 alle 10 46 26](https://user-images.githubusercontent.com/1868590/36780945-c952f82a-1c74-11e8-83ae-84f52383c2d8.png)
