### ISSUE TITLE
Store value other than string

### ISSUE THREAD

**Issue by NetanelBasal** [jshjohnson/Choices#265]
I have the following choices:

```
const choices = [
  {
     name: 'A',
     key: [1,2]
  },
 {
    name: 'B',
    key: 3
 }
]

this.choices.setChoices(choices, 'key', 'name');
```

But now if I need to set the `A` option, I can't, because `setValueByChoice` does not support this. There is a way to set the `A` option programmatically in this case?

**Comment by jshjohnson** [comment]
Hey,

Sure, try the following:

```
const choices = [
  {
     name: 'A',
     key: [1,2],
     selected: true
  },
 {
    name: 'B',
    key: 3
 }
]

this.choices.setChoices(choices, 'key', 'name');
```

**Comment by NetanelBasal** [comment]
But how can I set this as select programmatically with `setValueByChoice`?
