### ISSUE TITLE
refresh select options

### ISSUE THREAD

**Issue by Youfka** [jshjohnson/Choices#266]
Hello, I have a login form with select captcha, if it's a login error, I have to refresh options. It refreshes original select, but not choices select, how can I refresh it? (I was trying to destroy and init it, but it keeps creating inside old select, then inside previous select etc)

**Comment by jshjohnson** [comment]
Hey, what do you mean by refreshing options? 

Based on what you've said, you could try creating an `onChange` event listener to your select box and firing [`setChoices`](https://github.com/jshjohnson/Choices#setchoiceschoices-value-label-replacechoices) within that with the options available. Alternatively, a new `refresh` method could be added but I think that would require some rewriting.

**Comment by DV8FromTheWorld** [comment]
+1  "a new `refresh` method"

Having choices either automatically update based on underlying select or at least tell it to do so would be _so nice_.

**Comment by theonlygusti** [comment]
> Hey, what do you mean by refreshing options?
> 
> Based on what you've said, you could try creating an `onChange` event listener to your select box and firing [`setChoices`](https://github.com/jshjohnson/Choices#setchoiceschoices-value-label-replacechoices) within that with the options available. Alternatively, a new `refresh` method could be added but I think that would require some rewriting.

How do you get the choices.js object for the element?
