### ISSUE TITLE
How to inspect dropdown menu?

### ISSUE THREAD

**Issue by tekord** [jshjohnson/Choices#268]
Hi! Thanks for nice library. I want to inspect dropdown items, but once I move mouse on item and click right button it collapsed. I can't inspect these elements from Chrome's Elements panel because focused (exanded) dropdown has different attributes on items which I want to inspect. So I can't inspect these attribute because they appears only if dropdown is expaned, but if I expand the dropdown then I still can't inspect due to lost of focus (and the collapsing after that).

**Comment by maximmig** [comment]
Please see here: https://www.screencast.com/t/ihcA7Eexj

**Comment by tekord** [comment]
@maximmig can't watch because unable to install flash player.

**Comment by tekord** [comment]
@maximmig not working :(. Right click on item closes the dropdown.

**Comment by maximmig** [comment]
Why can't you just inspect elements moving the mouse over the open dropdown having devtools open? Devtools will reveal all the changes. IMO there is no need to right-click at all.

**Comment by tekord** [comment]
@maximmig because when dropdown is expanded all item elements changes their state. And once I try to click on them in the inspector they changed back.

https://dl.dropboxusercontent.com/s/o5ixbyu6gx97j5a/2017-10-04_19-04-42.gif

I want to inspect item elements when dropdown is expanded.

**Comment by jshjohnson** [comment]
If you open Chrome dev tools, inspect the dropdown container and put a focus state on it, it will remain open 👍

**Comment by tekord** [comment]
@jshjohnson no, it is not 
https://dl.dropboxusercontent.com/s/b6g2ga58zi2zej1/2017-10-05_00-49-01.gif

**Comment by jshjohnson** [comment]
See here: https://www.youtube.com/watch?v=VnFuwCrqJ-U&feature=youtu.be
