### ISSUE TITLE
HTMLFormElement.reset() does not resets value of Choices element

### ISSUE THREAD

**Issue by tekord** [jshjohnson/Choices#270]
I have a filter form with native Select element and Choices element. `HTMLFormElement.reset()` does not affect Choises elements. I assume it is a bug.

**Comment by jshjohnson** [comment]
Hi @tekord,

This isn't so much a bug - it's more of a missing feature! :)

**Comment by Aterbonus** [comment]
Hi. I'm searching projects for Hacktoberfest and I want to tackle this issue :)

**Comment by jshjohnson** [comment]
@Aterbonus Awesome :D
