### ISSUE TITLE
Allow constructor to accept NodeList

### ISSUE THREAD

**Issue by tekord** [jshjohnson/Choices#271]
At the current time constructor can not accept NodeList type. The following code is not working:
```
const inputs = document.querySelectorAll('.js-pretty-dropdown');

const choices = new Choices(inputs);
```

The error:

```
choices.js:184 Uncaught TypeError: this.passedElement.getAttribute is not a function
    at new Choices (choices.js:184)
```

I have to use CSS-selector `const choices = new Choices('.js-pretty-dropdown')` which is unwanted for me. Is it bug or possible feature request?

**Comment by jshjohnson** [comment]
Hey @tekord,

This is a definite feature request - passing a class name, as you said, performs a `querySelectorAll` for you 👍

**Comment by yahacom** [comment]
How about this feature?
This will be good in case if need initialize a lot of elements inside some container for example.
This can be done by using some loop, of course. But will be better just pass one object to constructor, I think.
