### ISSUE TITLE
Small body's height makes Choises flipped and unsuable

### ISSUE THREAD

**Issue by tekord** [jshjohnson/Choices#272]
I have small page with 2 controls, 1 of them is Choises. I expected the dropdown will be expanded to bottom side, but it is flipped and there is no space to work with it. See screenshot:

https://dl.dropboxusercontent.com/s/tcv5nhddypewrso/2017-10-08_15-07-11.png

If I set body's height to 1000px it works well.

Is it possible to fix? I can edit my css and set body's height, but I guess the Choises should not be linked to body's height.

**Comment by jshjohnson** [comment]
Hi @tekord,

You can enforce the dropdown to go above or below by using the [`position`](https://github.com/jshjohnson/Choices#position) config option :)

**Comment by tekord** [comment]
@jshjohnson thanks! Maybe add this info to doc?

**Comment by jshjohnson** [comment]
It's here: https://github.com/jshjohnson/Choices#position ;)

**Comment by tekord** [comment]
@jshjohnson I mean write note about usage with small body height in https://github.com/jshjohnson/Choices#position section.
