### ISSUE TITLE
Can't disable all select options

### ISSUE THREAD

**Issue by jaredatch** [jshjohnson/Choices#278]
Example:

```
<select>
<option value="" placeholder>Select items</option>
<option value="alpha" disabled>Alpha</option>
<option value="bravo" disabled>Bravo</option>
<option value="charlie" disabled>Charlie</option>
</select>
```

In this scenario Bravo and Charlie are correctly disabled, but Alpha is not and is fully selectable.

In the markup, all items are correctly disabled. Select is configured to sort.

```
<select>
<option value="" placeholder>Select items</option>
<option value="bravo" disabled>Bravo</option>
<option value="charlie" disabled>Charlie</option>
<option value="alpha" disabled>Alpha</option>
</select>
```

In the example above, Alpha will still be selectable.

**Comment by jaredatch** [comment]
Last I checked this bug was never resolved and still exists, so this issue should not yet be closed.

**Comment by jshjohnson** [comment]
@jaredatch Thanks - would you mind creating a jsfiddle highlighting the problem with the latest version of Choices please?

**Comment by jaredatch** [comment]
@jshjohnson - just tried to replicate the issue on 4.0.2 and wasn't able to do it, so I assume it was addressed at some point in a bug scrub, either directly or indirectly (was on 3.0.3).

So closing. Thanks ! 😎
