### ISSUE TITLE
Remove inline styling from js to accommodate standard CSP policies

### ISSUE THREAD

**Issue by AndyRN** [jshjohnson/Choices#279]
This line of code violates standard CSP policies due to the inline style being set:
```js
this.passedElement.setAttribute('style', 'display:none;');
```

What developers can do instead is specify the `hiddenState` class with one that has a `display: none;` rule when creating a Choices input. As there is an operation that occurs a few lines before:
```js
// Hide passed input
this.passedElement.classList.add(
   this.config.classNames.input,
   this.config.classNames.hiddenState,
);
```

Is there a case that requires this styling to be set here that I'm failing to consider?

---
* [Link to code - choices.js:2729](https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/choices.js#L2729)
* [Content Security Policy - Unsafe inline styles](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/style-src#Unsafe_inline_styles)

**Comment by jshjohnson** [comment]
Hey - thanks for the info. Would you be able to submit a PR for this off the develop branch at all? 👍

**Comment by dc00283** [comment]
Ah, this fix would be useful to bring my project in-line with our required CSPs - any update on the PR?

**Comment by pabse** [comment]
@jshjohnson can we have a release with this change please? It is currently only on the develop branch.
