### ISSUE TITLE
Demo: Chicago is not a state

### ISSUE THREAD

**Issue by derekshirk** [jshjohnson/Choices#280]
The very last demo on this page: https://joshuajohnson.co.uk/Choices includes "Chicago" as a selectable option for "States". I do not believe Chicago to be a state. 

<img width="524" alt="screen shot 2017-10-31 at 12 20 14 pm" src="https://user-images.githubusercontent.com/1427548/32244593-3db0ccc6-be36-11e7-995c-ed257397a631.png">

Great work on this project. Thanks for sharing!

**Comment by jshjohnson** [comment]
Haha good spot 🤦🏻‍♂️
