### ISSUE TITLE
Multiple selector returns single Choices instead of array of Choices

### ISSUE THREAD

**Issue by tekord** [jshjohnson/Choices#284]
I have the following code:

```
var filterDropdownControls = new Choices('.main-filter-container .js-select-element', {
            itemSelectText: null,
            searchEnabled: false,
            searchChoices: false,
            shouldSort: false,
            shouldSortItems: false
        });
```

Expected result:

filterDropdownControls is an array of Choices becuse selector '.main-filter-container .js-select-element' returns multiple elements.

Actual result:

Choises is applied to all elements of selector. But the filterDropdownControls is a single instance of  Choices which linked to first element of selector.

**Comment by jshjohnson** [comment]
I agree actually - I would be happy to review a PR for this

**Comment by tekord** [comment]
@jshjohnson well, I can't help here because I am not JS developer :(

**Comment by tekord** [comment]
Staled, but still relevant I think

**Comment by jshjohnson** [comment]
@tekord With the latest release, this is now fixed
