### ISSUE TITLE
Choices triggers change event only if value of option is not empty

### ISSUE THREAD

**Issue by tekord** [jshjohnson/Choices#285]
I have dropdown where first option has empty value (in my domain model it means no choice). Choices does not trigger change event if user select this item, but empty value is value too. Is it bug or I missed something?

**Comment by bububo** [comment]
I have the same issue. Why the Choices doesn't work as a native dropdown in this case? 
I have the following structure:

`<select>
    <option value="">Please Select</option>
    <option value="1">Item1</option>
    <option value="2">Item2</option>
</select>
`

The change event fires only if I chose any item, but does not fire if I chose the "Please select" option.

**Comment by jshjohnson** [comment]
Sorry closed this by accident. I think you’re right. I’ll put a fix in for this with the next release.

**Comment by shuckster** [comment]
I seem to have a related issue: Removing the last item - thereby leaving an empty list - does not invoke the change-handler, making it impossible to save an empty list.

**Comment by Frique** [comment]
As a workaround you can listen for the "choice" event instead of "change". This fires with each selection, regardless of the selected value.

**Comment by tekord** [comment]
Not solved yet?

**Comment by jshjohnson** [comment]
@tekord This should now be fixed
