### ISSUE TITLE
Cannot assign to read only property 'exports' of object '#<Object>'

### ISSUE THREAD

**Issue by kkomaz** [jshjohnson/Choices#288]
I was required to reinstall my node modules and got a weird error as shown below.  I'm trying to debug this but not super clear on where the issue is coming from?  Were there any changes I am not accounting for?

![screenshot of google chrome 11-13-17 11-11-25 am](https://user-images.githubusercontent.com/8473884/32735678-6586dfba-c863-11e7-9025-c7f2f477e05d.png)

**Comment by jshjohnson** [comment]
Hi, what version are you using?

**Comment by kkomaz** [comment]
So I created a fork and my solution was to replaces the `module.exports` on `choices.js` 

from 

```
-module.exports = Choices;
 +export default Choices;
```

and remove `store.js`

**Comment by jshjohnson** [comment]
Try forking from the latest master now - what is on master currently is the beta of the next version so their may be minor issues. You may be better off using https://github.com/jshjohnson/Choices/releases/tag/v3.0.2 👍
