### ISSUE TITLE
Always selects first item in select-multiple element

### ISSUE THREAD

**Issue by Muppetteer** [jshjohnson/Choices#29]
There is a bug in the library that causes the first option in a select-multiple element to always be selected when the Choices object is initialised.

This is where it happens (line 1864 of src/choices.js)
```
// Join choices with preset choices and add them
allChoices
    .concat(this.presetChoices)
    .forEach((o, index) => {
        if (index === 0) {
            this._addChoice(true, o.disabled ? o.disabled : false, o.value, o.label);
        } else {
            this._addChoice(o.selected ? o.selected : false, o.disabled ? o.disabled : false, o.value, o.label);
        }
    });
```

The `if (index === 0) {` should be changed to take into account the select element type, like it does elsewhere in the script. i.e.

`if (index === 0 && this.passedElement.type === 'select-one') {`

Sorry I can't give you a patch but after wasting an hour or so unsuccessfully trying to get node.js and a long list of dependencies installed (webpack, eslint, opn, babel etc etc etc) so I can build a non-minified script that executes, I gave up and just edited the minified version instead. I'm not sure if "this" will work in the closure but the minified version inserts a named variable "e" pointing to "this" which does work.

It would be great if you could include a fully compiled, non-minified, source script in the distribution so that we can easily debug without having to mess around with node.js and/or reverse engineering the minified version. Thanks.

**Comment by jshjohnson** [comment]
Hi @Muppetteer,

I have resolved this issue in version 1.1.7. I have also tweaked my build script to generate an unminified bundle.

If you have any other issues, let me know.

Thanks!
