### ISSUE TITLE
include example with exact match (fuse options)

### ISSUE THREAD

**Issue by DanielRuf** [jshjohnson/Choices#290]
So far there is no example with some of the fuse options which could be nice as default.

Also all examples lack the sourcecode as text on the website so no easy copying possible so far.

**Comment by fernandoagarcia** [comment]
Fuse has it's own properties for matching. They can be loose or strict but usually involves more than one criteria in your settings. Here is my example but I don't know what your definition of exact is. In my scenario any character entered can be found in any index point of the string but does return a match only fitting the characters entered:

`      fuseOptions: {
        includeScore: true,
        includeMatches: true,
        threshold: 0.4,
        location: 0,
        distance: 100,
        maxPatternLength: 32,
        minMatchCharLength: 1
      }`
