### ISSUE TITLE
setChoiceByValue is not a function in v3.0.2

### ISSUE THREAD

**Issue by viciantomas** [jshjohnson/Choices#292]
I have newest version v3.0.2 and I am trying to use setChoiceByValue but it is still pulling this error at me.
`setChoiceByValue is not a function`

Edit:
I found where was a problem. There is a typo in documentation. It should be **setValueByChoice**

**Comment by jshjohnson** [comment]
So what is in master is the beta of the next release. I've realised this is actually becoming a bit of an issue for people. I will revert it to the last release 👍

**Comment by jshjohnson** [comment]
I've reverted master - https://github.com/jshjohnson/Choices#setvaluebychoicevalue 👍
