### ISSUE TITLE
Adding customProperties to choices through markup

### ISSUE THREAD

**Issue by alexbech** [jshjohnson/Choices#293]
Is it possible to add customProperties to choices for select-multiple through markup?
Like through data properties or something?

**Comment by ChristopherRobinSuperStar** [comment]
I realy need it too!!!

**Comment by jshjohnson** [comment]
Happy to review a PR for this 👍

**Comment by ChristopherRobinSuperStar** [comment]
https://github.com/jshjohnson How long can this feature take approximately?

**Comment by renatodeleao** [comment]
I also needed this a lot so i've done some digging on the code base and found this [line](https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/choices.js#L2808)

```javascript
 // Create array of options from option elements
        passedOptions.forEach((o) => {
          allChoices.push({
            value: o.value,
            label: o.innerHTML,
            selected: o.selected,
            disabled: o.disabled || o.parentNode.disabled,
            placeholder: o.hasAttribute('placeholder'),
           // Am i beeing to naive to believe that is this simple?
            customProperties: JSON.parse(o.getAttribute('data-custom-properties'))
          });
        });
```
I've then remake the customOptions example from demo site. 

```HTML
<label for="choices-with-custom-props-via-html">Option searchable by custom properties via <code>data-custom-properties</code> attribute</small></label>
<p><small>Try searching for 'fantastic', again</p>

<select class="form-control" id="choices-with-custom-props-via-html">
  <option value="Dropdown item 1">Label One</option>
  <option value="Dropdown item 2" selected disabled>Label Two</option>
  <option value="Dropdown item 2" data-custom-properties='{"description": "This option is fantastic"}'>Label Three</option>
</select>
```
This actually works but.. it's too simple to be true right? Am i missing something @jshjohnson 
`If not then` https://github.com/renatodeleao/Choices/pull/1

**Comment by guilhermeocosta** [comment]
Even though with [renatodeleao#1](url
https://github.com/renatodeleao/Choices/pull/1) merged, I still get "null" return from `choice` event on `event.detail.choice.customProperties`.

My code is something like this:

```html
<option value="1" data-custom-properties='{"description": "This option is fantastic"}'>label</option>
```

```javascript
new Choices(element, {
  searchFields: ['label', 'value', 'customProperties.description'],
});
```

Am I missing something? Also, any passed attributes to my `option` element are being stripped out, so I cannot do nothing via markup 😞 

Any ideias @renatodeleao or @jshjohnson?

**Comment by renatodeleao** [comment]
@guilhermeocosta it wasn't merged, i didn't get a reply from the maintainer at the time, so I merged into my forked repo, not this one. You can use that at your own risk, but since it might be really outdated I suggest you just fork the most recent version choices and make the changes as stated in https://github.com/renatodeleao/Choices/pull/1/commits/3e54c53953f8af30fc0ecdbd334048c5f5f31f2a yourself. Good luck.

**Comment by jshjohnson** [comment]
@renatodeleao The `develop` branch will be the next release, i'll happily review a PR for that

**Comment by renatodeleao** [comment]
@jshjohnson sure, i might have some time at the end of the week.

**Comment by oguilleux** [comment]
Hi guys ! Any news regarding this new feature ?

**Comment by julian-kuroiwa** [comment]
PR updated to #512 🤡

**Comment by styledev** [comment]
Can we get this issue re-opened. It looks like PR #512 was reversed at some point and the line was reverted.

Line 1493: customProperties: option.dataset['custom-properties']
https://github.com/jshjohnson/Choices/blob/ebbea8c3b0f20473e05112f61bc8ce3bd6bf12da/public/assets/scripts/choices.js#L1493

**Comment by chrisooo3** [comment]
Is this functionality added?

**Comment by reimax** [comment]
> Is this functionality added?

no...

**Comment by danielpina** [comment]
@renatodeleao solution https://github.com/Choices-js/Choices/issues/293#issuecomment-373690718 works for version 9.0.1 but not version 10.0.0

**Comment by styledev** [comment]
Just wanted to note that I tried to upgrade to v10.0.1 but this is still an issue. @jshjohnson can you please re-open this as this is a much needed issue as resetting groups and choices do not work since [this](https://github.com/Choices-js/Choices/pull/512) was reverted

**Comment by vervelover** [comment]
> @renatodeleao solution [#293 (comment)](https://github.com/Choices-js/Choices/issues/293#issuecomment-373690718) works for version 9.0.1 but not version 10.0.0
> 
> The problem I'm still facing is that `destroy()` does not return the custom attributes to the passed input

I confirm it works in 9.0.1 but not 10>
