### ISSUE TITLE
Adding labels for accessibility to dynamically generated inputs.

### ISSUE THREAD

**Issue by fernandoagarcia** [jshjohnson/Choices#296]
Do you have a hook to add custom HTML or labels to the dynamically generated inputs such as choices__input/choices__input--cloned ?

**Comment by jshjohnson** [comment]
Hey, you can manipulate the markup by using the [`callbackOnCreateTemplates`](https://github.com/jshjohnson/Choices#callbackoncreatetemplates) callback
