### ISSUE TITLE
Add custom ordering config option

### ISSUE THREAD

**Issue by chymz** [jshjohnson/Choices#3]
Maybe a bug only a select-one element, but when I use setValue() to set choices on my select they appear in the wrong orders .

Demo (#choices-2 and #choices-3) : https://embed.plnkr.co/hVyjk5z2lJZorqOi48e6/

Label Three appear in second position, and is selected by default :(

**Comment by chymz** [comment]
Maybe same problem : https://github.com/jshjohnson/Choices/issues/2
I misunderstood your documentation.

But the only way to change choices of the select is the ajax() function ?

**Comment by chymz** [comment]
I've updated the plunker and use now the ajax() function but the wrong order problem persist.

What is my mistake ?

Thanks !

**Comment by jshjohnson** [comment]
Hey @chymz,

Adding 'items' via the config is intended for text inputs (so will be ignored for select inputs). I'm in the process of adding 'options' to the config object so you can achieve what you're looking for. 

The ordering problem looks like a bug - i'll look into that! 

Thanks, 

Josh

**Comment by chymz** [comment]
Ordering problem isn't a bug, you use sortByAlpha function for ordering choices (https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/reducers/choices.js#L15)

Maybe you can make it configurable ?

**Comment by jshjohnson** [comment]
Hi @chymz,

I have just pushed a new release that allows you to define choices via the config (see https://github.com/jshjohnson/Choices#choices).

I'm going to be implementing custom sorting in the next release - it requires some restructuring. 

Thanks

**Comment by jshjohnson** [comment]
This has now been implemented as of version 1.0.47. 

See: https://github.com/jshjohnson/Choices#sortfilter

Thanks!
