### ISSUE TITLE
Placeholders not working for Single Select dropdowns

### ISSUE THREAD

**Issue by travist** [jshjohnson/Choices#301]
For the life of me, I cannot get placeholders to work with Single select drop-downs. Here is the JSFiddle.

https://jsfiddle.net/travistidwell/ycn5xvxx/

What am I missing?

**Comment by nandastone** [comment]
The placeholder options are intended `text` and `select-multiple` input types:

https://github.com/jshjohnson/Choices/tree/develop#placeholder

Note: For single select boxes, the recommended way of adding a placeholder is as follows:

```
<select>
  <option placeholder>This is a placeholder</option>
  <option>...</option>
  <option>...</option>
  <option>...</option>
</select>
```

Your example, updated: https://jsfiddle.net/3yd39cc2/2/

**Comment by travist** [comment]
Awesome. Thanks for that.

**Comment by Meekohi** [comment]
How do you do this when using `choices:` parameter?
