### ISSUE TITLE
Placeholder for single select

### ISSUE THREAD

**Issue by triawarman** [jshjohnson/Choices#304]
in this link [placeholder](https://github.com/jshjohnson/Choices#placeholder) explain recommended way of adding placeholder is
```html
<select>
  <option placeholder>This is a placeholder</option>
  <option>...</option>
  <option>...</option>
  <option>...</option>
</select>
```
this adding one option to the dropdownlist. with some modification, the option cannot be selected and set as disabled, but still we can see the option as part one of the select option. e.x.
![select](https://user-images.githubusercontent.com/10298895/33693982-b05866b4-db30-11e7-9b4a-5a55b88dbe6c.png)
but what if the placeholder dont add as one of the options, only add some text to html element when there's no selected option. e.x.
![select with add option as placeholder](https://user-images.githubusercontent.com/10298895/33694328-7f00e526-db32-11e7-8ff3-b7b94b01db6a.png)
i think this one is best solution for placeholder for single select.

Thanks for the plugin :)

**Comment by fernandoagarcia** [comment]
So What I normally do is after initializing the choices instance I add event listeners to the dropdown: `    if (single) {
      instance.passedElement.addEventListener('showDropdown', function(event) {
        // do something creative here...
        let allPlaceholders = instance.containerOuter.querySelectorAll('[data-value="placeholder"]')
            ,i = allPlaceholders.length;

        while (i--) {
          allPlaceholders[i].style.display = 'none';
        }
      }, false);
      instance.passedElement.addEventListener('hideDropdown', function(event) {
        // do something creative here...
        let allPlaceholders = instance.containerOuter.querySelectorAll('[data-value="placeholder"]')
            ,i = allPlaceholders.length;

        while (i--) {
          allPlaceholders[i].style.display = 'block';
        }
      }, false);
    }
`

**Comment by triawarman** [comment]
hy @fernandoagarcia thanks for your sugestion, will try in few days. 
your's is really helps me.

**Comment by triawarman** [comment]
In my case, i dont set any value to my placeholder, so i change to
```js
 let allPlaceholders = instance.containerOuter.querySelectorAll('[data-value=""]')
            ,i = allPlaceholders.length;
```
Thanks fernando.

**Comment by miguelangelui** [comment]
const selectElements = document.querySelectorAll('.associated-brand-select');
let choicesInstances = [];
selectElements.forEach(select => {
        const instance = new Choices(select, {
            removeItemButton: true,
            placeholder: true,
            shouldSort: false,
            removeItems: true,
            placeholderValue: 'Select brands',
        });
        // Guardar la instancia para su uso posterior
        choicesInstances.push(instance);
    });
    
    async function marcasAsociarSelect() {
        const url = `${API_BASE_URL}/brands`;
        const data = await fetchDataFromApi(url, { paginate: false });

        choicesInstances.forEach(associatedBrandChoices => {
            // Limpiar opciones previas
            associatedBrandChoices.clearChoices();

            // Añadir nuevas opciones desde la API
            if (data && data.success) {
                associatedBrandChoices.setChoices(data.data.map(brand => ({
                    value: brand.id,
                    label: brand.name,
                    selected: false,
                    disabled: false
                })), 'value', 'label', false);
            } else {
                associatedBrandChoices.setChoices([{
                    value: '',
                    label: 'No hay marcas',
                    selected: true,
                    disabled: true
                }]);
            }
        });
    }
