### ISSUE TITLE
[Help] Placeholder without being an option.

### ISSUE THREAD

**Issue by ellisio** [jshjohnson/Choices#305]
Hello,

I am trying to figure out how to get a placeholder configured to only display when no option is selected. Once an option is selected, the placeholder should no longer be visible.

I have included the desired flow below, is this possible?

### Current Flow

Using this configuration:

```
new Choices(this.$refs.country, {
    shouldSort: false,
    searchEnabled: false,
    choices: [{
        value: '',
        label: 'Select Country',
        placeholder: true,
    }, {
        value: 'US',
        label: 'United States (+1)',
    }, {
        value: 'CA',
        label: 'Canada (+1)',
    }],
});
```

The user is presented this menu:

![image](https://user-images.githubusercontent.com/127468/33751392-d61594aa-db97-11e7-9eff-30cc96cf6f83.png)

### Desired Flow

*Page Load:*
![image](https://user-images.githubusercontent.com/127468/33751406-ea3f4ef8-db97-11e7-8b89-d8746f3c3644.png)

*Initial Click:*
![image](https://user-images.githubusercontent.com/127468/33751428-0b6ee1d8-db98-11e7-8a55-b591dcc5bf51.png)

*Option Selected:*
![image](https://user-images.githubusercontent.com/127468/33751442-1da3062c-db98-11e7-91f3-df3b5ecce368.png)

*Option Selected, Dropdown Open:*
![image](https://user-images.githubusercontent.com/127468/33751453-360d7490-db98-11e7-8cc1-68d309b5b6a3.png)

**Comment by ellisio** [comment]
A hacky way would be to do the following in CSS:

```
.choices__list--dropdown .choices__placeholder {
    visibility: hidden;
    width: 0;
    height: 0;
    padding: 0;
}
```

However, if the user uses their up arrow key on the 1st "option" and presses enter it clears the value; which should not happen.

**Comment by fernandoagarcia** [comment]
I added an event listener when the dropdown opens that hides the placeholder and disables it. After a selection is made you wont need it unless you need to clear the selection. This should be sufficient for not allowing you to select the placeholder.
