### ISSUE TITLE
Clear options without the placeholder

### ISSUE THREAD

**Issue by sametsafak** [jshjohnson/Choices#311]
How can I do that with single select? If I use clearStore(), It deletes placeholder too.
I am using this method to add a placeholder 
https://github.com/jshjohnson/Choices/issues/301

**Comment by fernandoagarcia** [comment]
Not sure if you are trying to delete the entire choice store or just the selected items. But if the former, make a reference to the placeholder then repush to the choices array after tou use clearStore().
