### ISSUE TITLE
A11y - Active descendant not set on input

### ISSUE THREAD

**Issue by 4lbertoC** [jshjohnson/Choices#315]
Hello there,

I'm testing a11y on v3.0.3 but screen readers do not recognise the choices.
I noticed that the fix is already on the develop branch but not on master, which as far as I understood is the current reference for tags.

It's just about setting the correct `aria-activedescendant` attribute on the input field when a choice is highlighted.

I'm sending you a PR.
Do you see any potential side effect or is it possible to merge it?

Thank you!

**Comment by jshjohnson** [comment]
See conversation here: https://github.com/jshjohnson/Choices/pull/316
