### ISSUE TITLE
Enter is not bind

### ISSUE THREAD

**Issue by HMAZonderland** [jshjohnson/Choices#318]
I have some trouble getting the text (tag) variant to work. When I type a word and press the enter key the stroke itself is not registered. I added a `console.log` in the `_onKeyDown` function to see what is tracked and I see almost all keys passing through my console, except for the enter key.

I have version 3.0.3 on OSX 10.12.6 on Chrome 63.0.3239.84 (Official Build) (64-bit).

**Comment by HMAZonderland** [comment]
So, how's it going?

**Comment by HMAZonderland** [comment]
Can we reopen this issue? Its not resolved?

**Comment by jshjohnson** [comment]
@HMAZonderland What are you trying to achieve? `_onKeyDown` is a private method so you shouldn't be using it in your application. It would be good if you could provide a jsfiddle highlighting the issue 👍
