### ISSUE TITLE
Variablize style class names

### ISSUE THREAD

**Issue by zslabs** [jshjohnson/Choices#32]
Hey!
Currently when instantiating Choices, you can impact the naming of the UI classes, but https://github.com/jshjohnson/Choices/blob/master/assets/styles/scss/choices.scss doesn't have a way to override these selectors if you'd like to keep the base styles (as far as I can see). Would you be up for a way to plug into these values? It'd look something like this:

```
$choices-selector: 'choices' !default;

.#{$choices-selector} {
  color: blue;
}
```

It's something I could look into if you're interested.

**Comment by jshjohnson** [comment]
Hi @zslabs,

Nice idea, I've just committed this change: https://github.com/jshjohnson/Choices/blob/master/assets/styles/scss/choices.scss#L5

Thanks
