### ISSUE TITLE
"Attempting to select choice that does not exist" error when value is JSON

### ISSUE THREAD

**Issue by mark-james** [jshjohnson/Choices#322]
Hi,
I'm getting the error "Attempting to select choice that does not exist" when I'm loading JSON objects as the value and trying to select an item using setValueByChoice. I assume we need to implement another way or testing for equality for complex objects than what is in the setValueByChoice?

var foundChoice = selectOptions.find((choice) => {
          // Check 'value' property exists and the choice isn't already selected
          return choice.value === value;
        });

Are there any recommendations on how best to fix it?

cheers
Mark

**Comment by jshjohnson** [comment]
Could you provide a jsBin of some sort so I can investigate this please?

**Comment by fernandoagarcia** [comment]
Standardize your obiect before setting your choice. I wrote this mapper for that sobyou can declare the label, value and customProperties. Your object must be flat.

  /**
  * Generate a standardized list object - requires a data map refer to CreateDataMap
  * @param {array} objArr - an array of objects with data
  * @param {instance} mappedKeysObj - a data key map instance. Refer to CreateDataMap
  * @returns {promise} returns a promise with a newly created array of list objects
  */
  globalObj.generateListObject = (objArr, mappedKeysObj) => {
    let i = objArr.length
        ,listObjArr = []
        ,hasOwn = Object.prototype.hasOwnProperty
        ,prop;
    const valueKeyName   = mappedKeysObj.value;
    const labelKeyName   = mappedKeysObj.label;
    const customDataKeys = mappedKeysObj.customProperties;

    // After building our list objects return a promise
    return new Promise((resolve, reject) => {
      while (i--) {
        let listObj = {}
            ,customProperties = listObj['customProperties'] = {};

        for ( prop in objArr[i] ) {

          if ( hasOwn.call(objArr[i], prop ) ) {

            if ( prop === valueKeyName ) {
              listObj.value = objArr[i][prop];
            }

            if ( prop === labelKeyName ) {
              listObj.label = objArr[i][prop];
            }

            if ( customDataKeys.indexOf(prop) !== -1 ) {
              customProperties[prop] = objArr[i][prop];
            }
          }
        }

        listObjArr.push(listObj);
      }

      resolve(listObjArr);
    });
  };

**Comment by fernandoagarcia** [comment]
I created a mapping util just for this purpose:

[https://jsfiddle.net/fsquaredmedia/61vnLz3k/](url)
