### ISSUE TITLE
Populate by Ajax option?

### ISSUE THREAD

**Issue by eman1986** [jshjohnson/Choices#324]
I'm looking for a new selectbox library and really like this one, one thing I'm not seeing is how to populate it by ajax. That's a must for me as most of my select boxes are dynamic data

**Comment by jshjohnson** [comment]
https://github.com/jshjohnson/Choices/blob/master/README.md#ajaxfn 👍🏻

**Comment by eman1986** [comment]
does that function accept post or just get?
