### ISSUE TITLE
Impossible to add default choices and allow to add new items

### ISSUE THREAD

**Issue by hacktivista** [jshjohnson/Choices#328]
I need to add default (not previously selected) choices and allow to add new items to the initial list of choices.

Currently there are 2 options for adding choices at initialization:
1- Using input: through the 'items' config or 'setValue' method, this selects all items by default, so does not work for my use case.
2- Using select: through the 'choices' config, with plain html or 'setChoices' method, this does not allow me to add new items, so is not useful for my use case.

What could I possibly do? :(

**Comment by fernandoagarcia** [comment]
First you need to set the choices then push the default item you want into the items array. That should be sufficient.

**Comment by koutsenko** [comment]
Same issue here.

**Comment by fernandoagarcia** [comment]
@koutsenko  ok I think what you are asking is you want to add a dynamic value that didn't exist but was enter by the user. Please take a look at the following JS fiddle at the second instance to see if it matches your requirement: 

https://jsfiddle.net/fsquaredmedia/14dg45j7/

**Comment by koutsenko** [comment]
@fernandoagarcia thx for quick response.
Almost it is. I asking how to do font-size selector as google did in google docs app.
Your example adds an rounded badges, i dont' need them, and masking their styles isn't a solution also.

**Comment by fernandoagarcia** [comment]
@koutsento not sure what you mean about ‘font-size selector’ but the api uses either single select or multi-select. These are the only two options. If you just need the value entered then dont set the value to the choice instance then merely pass it to whatever data source you are aaving it to manually.  But it sounds like you require a lot more custom code for whatever it is you want to do. ChoicesJS is specific to displaying users with options and allowing them to select (single/multiple) those options with a good user interface. nothing more.

**Comment by koutsenko** [comment]
i found choices.js as "select2 replacement without jquery".
https://select2.org/tagging - the first example shows that you can both:
- select an input value
- select one of prefedined values

**Comment by koutsenko** [comment]
i made working demo, but with a set timeout hack:
 https://github.com/koutsenko/font-choose-sample

**Comment by leereichardt** [comment]
@fernandoagarcia Is it possible to do that Select2 Tagging? I want to have a multiple select and present the user with some pre-filled options, but I'd also like them to have the ability to add their own choices.

**Comment by fernandoagarcia** [comment]
@leereichardt that will should be a feature request. Keep in mind the JSfiddle is a partial implementation of how I would approach it. You still have to some more custom code to reset the dropdown. 

Add 'Dynamic option creation'

**Comment by HMAZonderland** [comment]
I'm looking into this as well but my application does have a state where there are no choices to choose from, but I want the user to be able to add his first value. How can I achieve this? 

Also look at my ticket #318

**Comment by HMAZonderland** [comment]
Can this issue get reopend as its not resolved?

**Comment by flip111** [comment]
Critical feature to have this for my app. Select2 equivalent https://select2.org/tagging#automatic-tokenization-into-tags
