### ISSUE TITLE
Array.from is defective

### ISSUE THREAD

**Issue by dartess** [jshjohnson/Choices#336]
`Array.from` from Choices not work with `Set`:
```
var set = new Set();
set.add("ccc");
console.log(Array.from(set)); // []
```

When connecting polyfills my polyfill is not used, because `Array.from` exists.

Therefore, I must strictly observe the order of connecting libraries and polyfills.

The correct polyfill can be found, for example, here: https://cdn.polyfill.io/v2/polyfill.js?features=Array.from|always&ua=chrome/50

**Comment by jshjohnson** [comment]
Closing as develop has been updated to use the core-js array.from polyfill
