### ISSUE TITLE
Dropdown scroll to selected

### ISSUE THREAD

**Issue by rolandtoth** [jshjohnson/Choices#337]
Is it possible to scroll to the selected item when opening the dropdown? I mean, if one item in the middle of a long list of options (simple HTML select tag) is selected, it gets out of view, one needs to scroll down manually to see. It would be better to have the dropdown scrolled automatically to make it visible.

Or is there an option for this already?

**Comment by fernandoagarcia** [comment]
You can using the dropdown show event but the api doesnt exactly give you a method for it. You would have to do the scroll math manually.

**Comment by rolandtoth** [comment]
Thanks, here's the code I've put together:

```javascript
$choice.passedElement.addEventListener('showDropdown', function () {
    var $select = this,
        id = $select.value;

    var $option = $select.parentElement.parentElement.querySelector('.choices__list--dropdown [data-value="' + id + '"]');

    if ($option) {
        $option.classList.add('is-active');
        $option.parentElement.scrollTop = $option.offsetTop - $option.parentElement.offsetTop;
    }
}, false);
```

Unfortunately scrollIntoView() caused jumps in IE and Firefox, otherwise it would do the job as well.

**Comment by kaphert** [comment]
IMO this should be default behavior and not optional.

**Comment by pascalbaljet** [comment]
Here's an alternative solution using the `choiceId` value and built-in methods for scrolling:

```javascript
const choices = new Choices(selectElement);

choices.passedElement.element.addEventListener('showDropdown', () => {
    const id = choices.getValue().choiceId
    const option = choices.dropdown.element.querySelector(`[data-id="${id}"]`)

    if (!option) {
        return
    }

    choices.choiceList.scrollToChoice(option, 1)
    choices._highlightChoice(option)
}, false);
```

**Comment by iryska** [comment]
> Here's an alternative solution using the `choiceId` value and built-in methods for scrolling:
> 
> ```js
> const choices = new Choices(selectElement);
> 
> choices.passedElement.element.addEventListener('showDropdown', () => {
>     const id = choices.getValue().choiceId
>     const option = choices.dropdown.element.querySelector(`[data-id="${id}"]`)
> 
>     if (!option) {
>         return
>     }
> 
>     choices.choiceList.scrollToChoice(option, 1)
>     choices._highlightChoice(option)
> }, false);
> ```

Thanks for the solution!
Looks like they updated in their code `scrollToChoice` to `scrollToChildElement`

**Comment by abrardev99** [comment]
> Looks like they updated in their code scrollToChoice to scrollToChildElement

Saved me
