### ISSUE TITLE
Preserve Selected Order After Page Load/Reload

### ISSUE THREAD

**Issue by charpun** [jshjohnson/Choices#340]
Maybe I missed it somewhere on here, but I'm trying to do the following:

When using `choices.js` to allow for multi-select in an admin panel, I want to preserve the order of the items were selected in, which works fine and stores fine. The issue is, when you come back to the form, the order of the selected items are the order in the options and not to stored order. Is there a way that when `choices.js` loads the field, it loads the selected items in the stored order?

Thanks.

**Comment by fernandoagarcia** [comment]
@charpun it depends on the input type. If you are using a select input then you need to reorder your array of choices before I believe. But if you are using an input type text then it should keep its order.

**Comment by RyanThompson** [comment]
I am in the same boat - but text does not support choices though it preserves ordering and multiselect does support choices but does not preserve ordering.
