### ISSUE TITLE
_triggerChange doesn't work if selected empty value

### ISSUE THREAD

**Issue by rsmything** [jshjohnson/Choices#342]
Need to replace **if (!value)** by **if (typeof value == 'undefined')** to send **change** event when you select option with **value=''**

```
	    key: '_triggerChange',
	    value: function _triggerChange(value) {
	      if (typeof value == 'undefined') {
	        return;
	      }

	      (0, _utils.triggerEvent)(this.passedElement, 'change', {
	        value: value
	      });
	    }
```

**Comment by Aiso786** [comment]
This is a serious issue. I made a PR from your solution.

**Comment by rsmything** [comment]
Okay, thanks

**Comment by rsmything** [comment]
i used **typeof value == 'undefined'** instead **value == 'undefined'** because function took undefined argument

**Comment by Aiso786** [comment]
yes, you're right. I've updated the PR.
https://github.com/jshjohnson/Choices/pull/349

**Comment by Aiso786** [comment]
The PR has been merged, we can close the issue.

**Comment by rsmything** [comment]
Thanks
