### ISSUE TITLE
Check if any value is selected in all selects?

### ISSUE THREAD

**Issue by jesperlandberg** [jshjohnson/Choices#343]
Hi, I have multiple selects in a form and need to check if the form has any values and then toggle a class on the form depending on this.

I tried getValue() but it only return the value from the first select.

**Comment by fernandoagarcia** [comment]
push your instances to an array when you instantiate them then iterate using the getValue() method.

**Comment by jesperlandberg** [comment]
alright, any example on how this could look? Basically what im currently trying is the above
```

        this.choices = new Choices(this.selects, {
            placeholderValue: 'Välj behörighet'
        })

        this.selects.forEach((select) => {
select.addEventListener('change', (e) => {
    if (this.choices.getValue() != '') // do something
})
})

```

**Comment by fernandoagarcia** [comment]
Try this: https://jsfiddle.net/fsquaredmedia/u5twLLLr/
