### ISSUE TITLE
handle flip on horizontal axis and other positioning considerations.

### ISSUE THREAD

**Issue by renatodeleao** [jshjohnson/Choices#344]
Hey, thanks for the awesome work on Choices! 👌 

I was wondering if plugin should also handle the need for horizontal flip automatically , by adding `is-flipped-x`, for the use cases when dropdown list overflows viewport width. 

![Image](https://d2ffutrenqvap3.cloudfront.net/items/1i2r1U1a0P2r2l22363Q/Image%202018-02-28%20at%205.54.14%20PM.png?v=26629ca6)

### Possible 5min solution
After messing a little bit with your code
```Javascript
// At showDropdown()

// get viewport width
const winWidth = Math.max(
        body.scrollWidth,
        body.offsetWidth,
        html.clientWidth,
        html.scrollWidth,
        html.offsetWidth
      );

// making dropdown pos an x, y object
const dropdownPos = {
      x: dimensions.x + dimensions.width,
      y: Math.ceil(dimensions.top + window.scrollY + this.dropdown.offsetHeight)
    }

// check agains winWidth and allow both x and y passed via options string (Similar to popper.js) like "top right"
   let shouldFlipY = false,
        shouldFlipX = false;
    if (this.config.position === 'auto') {
      shouldFlipY = dropdownPos.y >= winHeight;
      shouldFlipX = dropdownPos.x >= winWidth;
    } else if (this.config.position.includes('top')) {
      shouldFlipY = true;
    } else if (this.config.position.includes('right')){
      shouldFlipX = true;
    }

// add className
if (shouldFlipX) {
   // not hardcoded but from config
  this.containerOuter.classList.add('is-flipped-x');
}
```

```SCSS
.choices{
  &.is-flipped-x {
    .choices__list--dropdown {
      left: auto;
      right: 0px;
   }
  }
}
```

I did a quick test and this works, but i didn't spend too much time thinking of edge cases 😅 

### Other positioning considerations: portal or the overflow trap escape
In some situations it would be good to render the dropdown at the `<body>` (portal) and avoid the _overflow trap_. This is trickier than it seems and it's no accident that positioning engines like [popper.js](https://popper.js.org/) or [tether.js](http://tether.io/docs/welcome/) were born. Would you consider to optionally integrate and leave the positioning work for them? I'll leave [Tippy.js](https://atomiks.github.io/tippyjs/) here as a reference of an integration. This shouldn't be as easy as the above mentioned horizontal flip but I just want to hear your thoughts on it, i'm not "affiliated" with tether or popper.

Cheers! ✌️

**Comment by kaphert** [comment]
thumps up for your last suggestion. I had to change some things in my layout to prevent the overflow issue. It would be cool indeed if the dropdown could be added at the bottom of the body to prevent this.
