### ISSUE TITLE
Search without sorting

### ISSUE THREAD

**Issue by kaphert** [jshjohnson/Choices#345]
Hi there,

I have a large select with years. Let's say 1900 until 2018. And add them with `setChoices()`. The items are already sorted so they do not need to be sorted again. 

Two things:
1. If I add the years as integers the search is not giving any results. If I add them as strings it is working. Not a big deal and that is not what this issue is about.
2. If I search with string `20` the first result is 2009 and after that is is nicely sorted as expected: 2018, 2017, 2016, 2015, etc. The same thing happens when I search on `19`: the first record is `1949` and after that the results are 1999, 1998 is missing (is somewhere below) 1997, 1996, 1995, 1994, etc.

I can't see why this is happening. As far as I can see the results from fuse are correctly sorted (read: unchanged). 

```
new Choices(document.getElementById('select'), {
          shouldSort: false,
          silent: true,
          searchResultLimit: 100,
          itemSelectText: '',
          fuseOptions: {
              shouldSort: false,
              includeScore: false,
              includeMatches: false,
              threshold: 0,
              location: 0,
              distance: 100,
              maxPatternLength: 32,
              minMatchCharLength: 1,
              keys: ["value"]
          }
});
```

See also this example https://plnkr.co/edit/d1hsGPour408YC5OqVSf?p=preview 
v3.0.3

Is there any way to just keep the sorting as it is?

**Comment by kaphert** [comment]
I see this happening in chrome but not in firefox.This PR is related to the issue but only solves it for non search items: https://github.com/jshjohnson/Choices/pull/34 

Would it be an option to include an option: `shouldSortSearch` ?

**Comment by SuneRadich** [comment]
Im also seeing this, I've created a plunker showcasing the issue

https://next.plnkr.co/plunk/XPnOW1C3ujgjgYIA

Here I first directly use Fuse to search my array, and then use a copy of that array with Choices. 

The plunker is set to search for "1" in the Fuse example. And the results show up as expected.  But if you input a 1 in the search field in Chocies, the results are sorted differently. But only in Chrome browsers (not in Firefox or Edge).

**Comment by SuneRadich** [comment]
Also, it seems that search results always get sorted.

At least as far as I can see in [renderChoices](https://github.com/jshjohnson/Choices/blob/9b860da25477985de018efeacf37194aea3a70b2/assets/scripts/src/choices.js#L406).

Shouldnt there be a way to configure how to display search results?
