### ISSUE TITLE
Maintain groups in search view

### ISSUE THREAD

**Issue by nbokmans** [jshjohnson/Choices#348]
Hi,

I was wondering if it was possible to maintain the groups (and ordering) for when the user tries to search values. In the regular select view, there's groups to split up the items into, well, groups:

![Grouped filter](https://i.imgur.com/HWg3L7r.png)

However, after searching, the groups seem to be lost:
![Search view without groups](https://i.imgur.com/xF7wACe.png)

Is there a way to make these groups persist after searching? I can't find any options for Fuse.

**Comment by wuno** [comment]
I have had a heck of a time getting this to render. Would you mind posting your code?

**Comment by nbokmans** [comment]
@wuno I use `_.groupBy` and `_.orderBy` from Lodash: https://lodash.com/docs/4.17.5 to group the elements, and then create my options like so:

```
import Choices from 'choices.js';
import groupBy from 'lodash.groupby';
import orderBy from 'lodash.orderby';

const selectorOptions = { removeItemButton: true, shouldSort: false, searchFields: ['label'], searchResultLimit: 10, fuseOptions: { threshold: 0 } };

let allLanguages = async function () {
    const response = await fetch('/Language/All', {
        credentials: 'include'
    });
    const json = await response.json();

    return json;
}

let fromLanguages = new Choices('#fromLanguages', selectorOptions);
let toLanguages = new Choices('#toLanguages', selectorOptions);

allLanguages().then((languages: any[]) => {
    let groupedOptions: any = groupBy(languages, (l) => {
        return l.groupOrder;
    });

    let options = Object.keys(groupedOptions).map((key: any) => {
        let group = groupedOptions[key];
        return {
            label: group[0].group,
            id: key,
            choices: orderBy(group, ['order'], ['asc']).map((l: any) => {
                return {
                    value: l.value,
                    title: l.title
                };
            })
        };
    });

    fromLanguages.setChoices(options, 'value', 'title', true);
    toLanguages.setChoices(options, 'value', 'title', true);
});
```

The fetch to `/Language/All` returns a list like this:
```
[
   {
      "value":"0253eb15-c7f6-4efb-943d-da11c36aef3c",
      "title":"English",
      "group":"Most Common",
      "groupOrder":0,
      "order":68
   },
   {
      "value":"0357ba34-49b9-482b-9149-3af2f556d9f8",
      "title":"German",
      "group":"Common",
      "groupOrder":1,
      "order":5
   },
   {
      "value":"25bf5d5a-dbf7-4f75-8b58-f40eea107d73",
      "title":"Slovak",
      "group":"Common",
      "groupOrder":1,
      "order":14
   }
]
```

Where `groupOrder` is the order of the groups, and `order` is the ordering inside the group.

**Comment by wuno** [comment]
Amazing. Thanks a ton for this! I ended up getting it working and my solution was very close to yours. But this was super helpful and actually helped me make my code better. 

I appreciate you!

**Comment by Hendriksie** [comment]
Would love to see this as an option!

**Comment by ssc-hrep3** [comment]
Would also like to see this as an option to choices.js 👍
