### ISSUE TITLE
Simple multiple select

### ISSUE THREAD

**Issue by Fantasterei** [jshjohnson/Choices#35]
Hey.

I want to ask if there is a simple way to replace multiple selects but working like default? The input and badges are not the most elegant way each time.

Here is an example how i want to have it:
https://silviomoreto.github.io/bootstrap-select/examples/#multiple-select-boxes

Maybe there is a way to do this.
Thanks and best regards

**Comment by jshjohnson** [comment]
Hi @Fantasterei,

Technically this is already possible. The example you sent is essentially behaving the same as Choices currently behaves  - the only difference is styling. It would be fairly simple to achieve what you are looking for by changing the CSS.

Thanks,
Josh

**Comment by Fantasterei** [comment]
No because the script removes the selected items from the selection-list. So there is no chance to do this by css.
