### ISSUE TITLE
Initialize selected items in multi-select

### ISSUE THREAD

**Issue by justin-hackin** [jshjohnson/Choices#352]
Regarding options documentation for `items`, it would seem that one could provide an array of values for the choices or the choice objects themselves.  However, neither technique seems to initialize the selected items.  See https://codepen.io/justin-hackin/pen/MVajMQ for a clear example.  In this, I would expect "1" to be chosen.  

ASIDE: it was difficult to figure out that the only way you can initialize a select item as a multiselect box is to use the select attribute `multiple`.  Consider a `multiple` config option that would apply this attribute to the hidden select box.

**Comment by fernandoagarcia** [comment]
@justin-hackin not sure if I exactly got your question but I think you're asking about preselected items?

You can initialize preselected items by adding another key to each item you wish to be preselected:

```
{
  "value": 1,
  "label": "Sam",
 "selected": true
}
```

Here is the jsFiddle example: https://jsfiddle.net/fsquaredmedia/14dg45j7/
