### ISSUE TITLE
Implementation Difference Between `classNames.input` and `classNames.button`

### ISSUE THREAD

**Issue by stephendolan** [jshjohnson/Choices#358]
I have the following `Choices` initialization:

```
new Choices(this.inputTarget, {
  removeItemButton: true,
  classNames: {
    input: ['input', 'has-margin-bottom-md'],
    list: 'tags',
    button: 'delete is-small has-margin-left-sm',
    item: 'tag is-medium',
  },
});
```

When I added the `input` key to `classNames` without the array, I received this console error:

> DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided ('input has-margin-bottom-sm') contains HTML space characters, which are not valid in tokens.

Spaces within `classNames` keys seem to work find for the `button` and `item` keys, and in fact using an array with the `button` key seems to not add all of the classes.

Is this intentional? If so, we should update the documentation to specify which entries in `classNames` need to be defined as arrays to accept multiple class names.

Thank you for the excellent library. After hours of searching for a non-jQuery tag input implementation, I was delighted to find this in such excellent condition.

**Comment by fernandoagarcia** [comment]
@stephendolan is you are looking do some more advance object creation you might find the 'callbackOnCreateTemplates' useful and more versatile. The beauty of ChoicesJS is that it doesn't stop you from doing anything by over complicating the configurations. 

https://github.com/jshjohnson/Choices#callbackoncreatetemplates

**Comment by stephendolan** [comment]
@fernandoagarcia,

I'm not looking for any more advanced object creation. I am proposing that all `classNames` overrides either be handled the same (all can accept an array or none can accept an array), or that we update the documentation to specify that the `classNames.input` key cannot handle spaces, and that multiple class name values must be passed as an array.

**Comment by jshjohnson** [comment]
@stephendolan I've looked into this and I think it's just coincidental that passing an array works for some elements - it may just be that input classnames are directly set and not manipulated. I think a check needs to be in place to ensure classnames are strings 👍
