### ISSUE TITLE
How to modify item before addition

### ISSUE THREAD

**Issue by stephendolan** [jshjohnson/Choices#359]
My goal is to modify each item before it is added to my list of items to be upper case, regardless of what was input by the user.

I'm catching the `addItem()` event, then modifying both the `event.detail.value` and `event.detail.label` to be the `.toUpperCase()` version.

The event gets these arguments set correctly, but it seems as though the item is added to the input `value` before this event is triggered.

Is there a way to do what I'm looking to do cleanly, or do I need to dive into the DOM after each `addItem()`? If that's the case, it would be extremely helpful to have a `beforeAddItem()` method or something similar where I could modify the input before it is used to do sanitization. Either that, or implement a filter method like `sortFilter` called `itemFilter` that each item is passed to before it is added.

**Comment by stephendolan** [comment]
For anyone encountering a similar situation where they want to always do something to the user input, I ended up working around it with something like the following (this is just pseudocode, as I am using a front end framework to help with the input events):

```
const example = new Choices(myInputElement);

// This input is the input that is generated by Choices.js
example.input.addEventListener('input', function() { this.value = this.value.toUpperCase() });
```

**Comment by fernandoagarcia** [comment]
@stephendolan the event.detail is a native JS attribute that is read only. Best practice is only showing the user exactly what the user has entered. Then behind the curtain you can modify the value before storing it in your DB to uppercase or any case you wish. 

Here is a method you can use if you need tp proper case your strings: 

`function (str) {
    return str.replace(/\w\S*/g, function(txt){return txt.charAt(0).toUpperCase() + txt.substr(1).toLowerCase();});
  };`

**Comment by stephendolan** [comment]
@fernandoagarcia ,

Thank you, I think that is good reasoning.

**Comment by jshjohnson** [comment]
Closing based on the conversation above. Will reopen if necessary.
