### ISSUE TITLE
Override or option for _setInputWidth

### ISSUE THREAD

**Issue by stephendolan** [jshjohnson/Choices#360]
I'm using [Bulma](https://bulma.io) for styling, and Choices.js has been relatively easy to set up for use with it by adding the following four `classNames` keys as options:

```
classNames: {
  input: 'input',
  list: 'tags',
  button: 'delete is-small',
  item: 'tag is-medium',
}
```

The item that got a bit tricky was how the input width is set automatically with `_setInputWidth`. Should this be enabled as a default option by the JavaScript itself? It seems like a very style-specific function, and I ended up just overriding it with `this.choices._setInputWidth = function() { };` to preserve the Bulma styling that I set with the above `classNames` options.

It would be nice to either have the option to override this function in the `new Choices` initialization, or to extract this out with some kind of `enableStyling` option.

**Comment by jshjohnson** [comment]
I agree actually. This probably should be an opt-out config option. I'll look into this 👍

**Comment by stephendolan** [comment]
Thanks, @jshjohnson !

**Comment by youradds** [comment]
Was this ever added as an option? I would prefer to be able to pass in the width I want :)

**Comment by jshjohnson** [comment]
@youradds I'll happily review a PR for this :)

**Comment by youradds** [comment]
Me too. I'm looking at the code now, but I don't get how it works (and I'd probably bugger something else up! haha)
