### ISSUE TITLE
Incorrect documentation for `duplicateItems`

### ISSUE THREAD

**Issue by stephendolan** [jshjohnson/Choices#361]
The documentation reads as follows:

> **duplicateItems**
> **Type**: Boolean **Default**: true
> **Input types affected**: text, select-multiple
> **Usage**: Whether each inputted/chosen item should be unique.

This is incorrect, as setting `duplicateItems` to `true` (the default) means that duplicate items are **allowed**.

Setting `duplicateItems` to `false` means that duplicate items are **not allowed**.

I propose the following change to the documentation to be more clear:

> **duplicateItemsAllowed**
> **Type**: Boolean **Default**: true
> **Input types affected**: text, select-multiple
> **Usage**: Whether duplicate inputted/chosen items are allowed.

**Comment by jshjohnson** [comment]
Good spot - feel free to make a PR for this :)

**Comment by stephendolan** [comment]
Thanks, @jshjohnson . Will do!

**Comment by jshjohnson** [comment]
@stephendolan This change has been made in `develop` 👍
