### ISSUE TITLE
Add `inactiveState` to complement `activeState`

### ISSUE THREAD

**Issue by stephendolan** [jshjohnson/Choices#362]
Many CSS libraries have built-in helpers for **hiding** elements instead of helpers for showing them. Users of Choices.js would be more easily able to leverage these capabilities if, whenever we add or remove the `activeState` class, we do the opposite for the `inactiveState` class.

I propose that the default is set to `is-inactive`.

For now, it is easy enough to simply listen to the `hideDropdown` and `showDropdown` events to hide or show the dropdown through JS style additions and removals.

**Comment by jshjohnson** [comment]
Like this idea 👍 Would happily review a PR for it

**Comment by fernandoagarcia** [comment]
@stephendolan if you have a class 'something.is-active' then the inactive state would be 'something' so if you set some animation to 'is-active' it would still animate when you remove the class. Having another is-inactive would be redundant.

**Comment by stephendolan** [comment]
@fernandoagarcia ,

I'm not sure that I understand your point. See [Bulma](https://bulma.io/), for example, and specifically the [Helpers](https://bulma.io/documentation/modifiers/helpers/) page. I do not have a class `something.is-active`, I just have a tag `something`. To hide the `something` element, I must append `something.is-invisible`.

@jshjohnson,

Thanks, will do!

**Comment by fernandoagarcia** [comment]
@stephendolan the principles are taken from HTML5 Spec for example all buttons have an active state and the inactive state is the default state. Think of it as a boolean .is-active implies true to an element that is false. You can add .is-inactive which imply false but you would be doing so to an element that is already false. Thats why in Bulma you don’t see .is-notinvisible helper class.
