### ISSUE TITLE
No separation of removeItems and removeItemButton

### ISSUE THREAD

**Issue by stephendolan** [jshjohnson/Choices#363]
Currently, there is no way to specify that you only want removal of options through buttons, and not with the backspace key. The two existing options are defined as follows:

> **removeItems**
> **Type**: Boolean **Default**: true
> **Input types affected**: text, select-multiple
> **Usage**: Whether a user can remove items.

> **removeItemButton**
> **Type**: Boolean **Default**: false
> **Input types affected**: text, select-one, select-multiple
> **Usage**: Whether each item should have a remove button.

There are really only two behaviors that are possible: deletion with the backspace key and deletion with a button. I propose the following:

> **removeItemsWithBackspace**
> **Type**: Boolean **Default**: true
> **Input types affected**: text, select-multiple
> **Usage**: Whether a user can remove items by pressing the backspace key.

> **removeItemsWithButton**
> **Type**: Boolean **Default**: false
> **Input types affected**: text, select-one, select-multiple
> **Usage**: Whether a user can remove items by pressing a button that is added to each item.

To accommodate for this, the check at the beginning of [`_handleBackspace`](https://github.com/jshjohnson/Choices/blob/0519b993979a8d5ff4d3870df8208567d67b6226/assets/scripts/src/choices.js#L1294-L1313) could be updated to check `removeItemsWithBackspace`, and the check at the beginning of [`_handleButtonAction`](https://github.com/jshjohnson/Choices/blob/0519b993979a8d5ff4d3870df8208567d67b6226/assets/scripts/src/choices.js#L1161-L1179) could be updated to check `removeItemsWithButton`.

**Comment by fernandoagarcia** [comment]
@stephendolan you can set a custom eventlistener to stop the backspace.

`instance.containerOuter.querySelectorAll('.choices__input--cloned')[0].addEventListener('keydown', function (e) {
  if (e.key === 'Backspace') {
    e.stopPropagation();
  }
});`


sample: https://jsfiddle.net/fsquaredmedia/14dg45j7/

**Comment by stephendolan** [comment]
@fernandoagarcia yes, that is what I did to get the functionality I needed. This proposal is to discuss whether users of Choices.js should _need_ a workaround like that for functionality that should arguably be separated anyways.

**Comment by fernandoagarcia** [comment]
@stephendolan the backspace makes the component more accessible and inclusive to all users (with disabilities, WCAG Compatible). Also in order to keep the framework light weight I think  less configurations are better or at least the 'right amount' of configurations. The approach I provided is not necessarily a workaround its an addition to the component.  Its easier to add versus taking away...especially if you are using NPM or any package managers where you don't necessarily want to modify the source.

**Comment by jshjohnson** [comment]
@stephendolan I think having `removeItemsWithBackspace` and `removeItemsWithButton` options makes more sense actually. I just think `removeItemsWithBackspace` should be on by default. Will happily review a PR for this 👍
