### ISSUE TITLE
Fire showDropdown() on focus of text input

### ISSUE THREAD

**Issue by stephendolan** [jshjohnson/Choices#364]
Currently, when focusing a Choice.js input field of type `text`, the following code is executed:

https://github.com/jshjohnson/Choices/blob/0519b993979a8d5ff4d3870df8208567d67b6226/assets/scripts/src/choices.js#L1999-L2030

I propose that this is updated to include the same event firing logic to call `this.showDropdown();` as the `select-one` and `select-multiple` input types, since the `Press enter to add <b>"${value}"</b>` text is shown in the dropdown for `text` type input fields.

**Comment by fernandoagarcia** [comment]
@StephaneTrebel  you can always add that manually because that may not fit all use cases. You can always attach an eventlistener to the input that triggers 'showDropdown()'  which me be specific to what you are trying to achieve.

**Comment by stephendolan** [comment]
@fernandoagarcia ,

Since the default for a text Choices.js input is to show that `Press enter to add` text, shouldn't the event be fired by default and users should be forced to **remove** it manually if they don't need it?

**Comment by eman1986** [comment]
I too would like such a behavior available, I have a few spots that a text box makes more sense but I'm forced to use a drop down
