### ISSUE TITLE
adding delimiter for select multiple

### ISSUE THREAD

**Issue by eman1986** [jshjohnson/Choices#365]
it looks that if I use multiple on my select it just creates a new entry.

example: I have a select named email and when a user selects 3, the request looks like this:

> ?email=foo@email.com&email=bar@email.com&email=test@email.com

I'd greatly prefer it to look like

> ?email=foo@email.com,bar@email.com,test@email.com

but that seem to only apply to the text input, would be good to have the dimiliter be affected to the multiple select.

**Comment by jshjohnson** [comment]
Not entirely sure what you mean but you can specify a delimiter here: https://github.com/jshjohnson/Choices#delimiter

**Comment by eman1986** [comment]
but that doesn't apply to selects with the multiple attribute, just textboxes.
