### ISSUE TITLE
selectedState does it exist?

### ISSUE THREAD

**Issue by blanzh** [jshjohnson/Choices#367]
How can I add a class to the selected item?
I see `selectedState: 'is-highlighted',` in documentation

**Comment by jshjohnson** [comment]
By default the selected state styling and the highlighted state styling are the same. You can change this class and provide your own styling if you wish. Just change the classname in the config: https://github.com/jshjohnson/Choices#classnames 👍

**Comment by Singularetantum** [comment]
The documentation is incorrect, the "selectedState" classname config isn´t changing anything at the moment.

"selectedState" is not used in anywhere in the code
