### ISSUE TITLE
XSS Vulnerability in the input field

### ISSUE THREAD

**Issue by MaksimShakavin** [jshjohnson/Choices#369]
How to reproduce:
1. Open the [demo page](https://joshuajohnson.co.uk/Choices/)
2. Paste the xss payload to the input field of any example( `<svg onload=confirm(document.cookie)> & <img src=x onerror=alert(2)>`)

**Comment by MaksimShakavin** [comment]
@jshjohnson,
Here are the PRs for master branch:
https://github.com/jshjohnson/Choices/pull/370
and for new development branch:
https://github.com/jshjohnson/Choices/pull/371

**Comment by jshjohnson** [comment]
Merged 👍
