### ISSUE TITLE
Webpack vs Rollup

### ISSUE THREAD

**Issue by zslabs** [jshjohnson/Choices#37]
Hey!
Wanted to bring up more a discussion rather than an issue, but I recently read through https://nolanlawson.com/2016/08/15/the-cost-of-small-modules/ which had some interesting insights into some of the extra "stuff" Webpack can wrap around your code which can sometimes lead to larger file sizes - and wanted to get your take. About to do some integration work with Choices to replace [Chosen](https://harvesthq.github.io/chosen/) (which relies on jQuery), but noticed the distributed size is about the same of both Chosen and jQuery combined - and it came across a little odd. Thanks!

**Comment by jshjohnson** [comment]
Hmm, jQuery clocks in at ~240kb and Chosen minified is 60kb as far as I'm aware.

**Comment by jshjohnson** [comment]
You've definitely got a point. I'm going to see whether Webpack 2 makes any sizeable difference to the bundle size - I've heard mixed reports about it.

**Comment by jshjohnson** [comment]
Going to close this and return to it when Webpack 2 comes out of beta. Thanks

**Comment by zslabs** [comment]
👍 Just as a heads up, I've been using the beta for a few weeks now and haven't run into any snags, so maybe not too far off from playing around with it!

**Comment by jshjohnson** [comment]
Out of interest, did you find it decreased bundle sizes?

**Comment by zslabs** [comment]
TBH I never used Webpack v1 and have not had a chance to use Rollpack in prod yet, but I'll tell ya I was pleasantly surprised in comparison to the previous (more traditional Rails asset pipeline type of approach I used) that the filesize was darn-near identical.
