### ISSUE TITLE
Add choices gem for rails?

### ISSUE THREAD

**Issue by nhaglind** [jshjohnson/Choices#372]
Selectize.js has this but it's not officially supported https://github.com/manuelvanrijn/selectize-rails. Would be nice if Choices offered this option as well to put it into the Rails asset pipeline via 
`//= require choices`.

**Comment by jshjohnson** [comment]
Hey @nhaglind,

Feel free to make your own version which wraps Choices. I don't know Ruby so not sure how this would even work. Others have released wrappers before though: https://github.com/NetanelBasal/nb-choices

👍
