### ISSUE TITLE
Attribute in options are not show

### ISSUE THREAD

**Issue by hirenkeraliya** [jshjohnson/Choices#375]
`
<select name="type" class="form-control">
    <option value="1" data-column-id="1" data-type="string" data-index="0" data-unique="1">
        label 1
    </option>
    <option value="2" data-column-id="11" data-type="integer" data-index="1" data-unique="1">
        label 2
    </option>
    <option value="3" data-column-id="22" data-type="image" data-index="0" data-unique="0">
        label 3
    </option>
    <option value="4" data-column-id="30" data-type="name" data-index="1" data-unique="0">
        label 4
    </option>
</select>
`
In this case when I use your choices then I cannot get the selected option data attribute value and don't show any other element to my option attributes.

Thanks

**Comment by jshjohnson** [comment]
@hirenkeraliya Difficult to see the problem here. Could you provide a reduced test case please highlighting the issue. 

Thanks

**Comment by hirenkeraliya** [comment]
@jshjohnson Yeah when passing the data attribute to the `<option data-type="string">`  so how I get the data-type attribute value of the selected option?

**Comment by fernandoagarcia** [comment]
@hirenkeraliya  I would recommend adding the data to the customProperties so then it can be access via the event.detail on 'addItem' event

**Comment by hirenkeraliya** [comment]
when the change the selection of the select box then I need those custom properties so, how I get those custom properties
