### ISSUE TITLE
How to get a handle for an initialized Choices element

### ISSUE THREAD

**Issue by aleehedl** [jshjohnson/Choices#376]
If I have initialized my Choices element in the following way: 

```
new Choices(document.querySelector(#choices'));
```

Is there a way to access the initialized Choices element somewhere else in the code if I don't have a reference to the original value? As far as I know, using `new Choices` always returns a new, uninitialized value. 

The use case could be, for example, that I want to programmatically set the value (`.setValue()`)

**Comment by jshjohnson** [comment]
Hey,

All you need to do is assign it to a variable e.g.

```js
const instance = new Choices(document.querySelector(#choices'));

instance.setValue(...);
```

**Comment by aleehedl** [comment]
Hi,

The point was exactly that I don't have the option to assign it to a
variable.

Regards,
Alex

**Comment by jshjohnson** [comment]
Ahh I see, sorry. 

As far as I know you could chain the method you want to call like:

```
new Choices(document.querySelector(#choices')).setValue();
```

There is no way of accessing an instance without referencing a variable as far as I know though.

**Comment by aleehedl** [comment]
For example, in FullCalendar you can get an instantiated calendar and then run methods, like this:
```
$('#calendar').fullCalendar().next();
```

You can try it in the console in the [FullCalendar frontpage](https://fullcalendar.io). A similar feature would be really useful with Choices.js.

**Comment by jshjohnson** [comment]
See my previous comment. They are behaving the same way. One is just using jQuery's API.

**Comment by aleehedl** [comment]
It does not behave the same way AFAIK. I can demonstrate my issue this way:
I go to the [Choices frontpage](https://joshuajohnson.co.uk/Choices/), open devtools console and type:

```
(new Choices('#choices-multiple-labels')).setValue(['Three'])
```

What I'd expect to happen is the option `Three` on the existing dropdown (`initialized: true`) to be selected. This does not happen.

**Comment by fernandoagarcia** [comment]
@aleehedl If for whatever reason you don't have access to the initialization code then you're better off just destroying then reinitializing ChoicesJS. Possible even removing the '.choices'  element altogether. But on another note if you have the ability to access the code where you initialized when you wrote 'new Choices(document.querySelector(#choices'));' then you can it to a variable then push that variable to an array attached to window. I do this when I have to add my initializations via a for loop. Otherwise I think we need more context to help you out. A JS fiddle would help us troubleshoot your issue better.

**Comment by martinkovac** [comment]
I just add new instance to data with `$(element).data('choices', choices);` And then I retrieve it by `var choices = $(element).data('choices'); `But this is not good solution. There should be some other way to do it.

**Comment by pliebig** [comment]
@aleehedl i totally agree to your point. i got the same problem, i want to destroy an existing choices element which is not saved in any variable. Every other library like slick, swiper or fullcalender offers the opportunity to call an existing element and run existing commands / methods. How does it work for choices?

**Comment by jshjohnson** [comment]
@pliebig @aleehedl The `develop` branch has been updated to return an array of instances 👍

**Comment by heylookalive** [comment]
@jshjohnson hiya, what's the name of the method added to get the instances?

**Comment by jshjohnson** [comment]
@heylookalive @fs86 When you create a new instance of Choices it will now return an array of instances if it has created more than 1. 

So:

```
const [instance1, instance2] = new Choices(document.querySelector(#choices'));
```

**Comment by fs86** [comment]
Dosn't work for me. If i call new Choices() then my controls will get reinitialized.

**Comment by jshjohnson** [comment]
Not going to be able to debug your code without seeing it!

**Comment by fs86** [comment]
I wanted to create a small test project but I can't get it to work.

jsFunctions.js:
```javascript
window.jsFunctions = {
  initializeChoices: function () {
    const controls = document.querySelectorAll('select');
    new Choices(controls, {
      searchEnabled: false,
      shouldSort: false
    });
  }
}
```
Error message:
```
Uncaught TypeError: Cannot read property 'element' of undefined
    at e.value (choices.min.js:2)
    at new e (choices.min.js:2)
    at Object.initializeChoices (jsFunctions.js:5)
    at HTMLDocument.<anonymous> (index.html:32)
```

**Comment by fs86** [comment]
@jshjohnson I have created a small repo for you where you can see the issue. Instead of getting an instance of an already initialized select element, the element will get reinitialized and added to the DOM every time you hit the button.

Here is the repo: https://github.com/fs86/ChoicesTest

**Comment by jshjohnson** [comment]
@fs86 You are assigning the instance to a variable and not doing anything with it. You need to create a closure. 

Something like:

```js
let choices;

document.addEventListener('DOMContentLoaded', function () {
  choices = new Choices('select');
});
```

**Comment by fs86** [comment]
Thanks for your help, but I get still the same result. The select box is added multiple times to the DOM. See my updated repo.

**Comment by cheh** [comment]
Anybody got it?

**Comment by msimcha** [comment]
I found that you can set the value of an existing Choices instance that you cannot access but triggering the mousedown event on the item with the value for which you're looking:

`handleSelect (obj, value) {
    let selectFields = obj.closest('.choices').querySelectorAll('.choices__item--selectable')
    for (let i = 0; i < selectFields.length; i++) {
      if (selectFields[i].dataset.value === value) {
        console.warn(selectFields[i].dataset.value)
        selectFields[i].dispatchEvent(new Event('mousedown'))
      }
    }
  }`
(obj here is a select element)

**Comment by HermanSchoenfeld** [comment]
Pretty stupid they don't give you the instance. It should be attached to the DOM object like every other lib.

**Comment by charlesrock96** [comment]
> 

Esta es la respuesta, no se porque dicen que no funciona. Gracias

**Comment by PINHOf** [comment]
> Pretty stupid they don't give you the instance. It should be attached to the DOM object like every other lib.

Fucking hell, I had to dig the whole internet to find out that this plugin developed by 1000 developers...doesn't give the instance. Seriously, how ridiculous this is...

**Comment by ilkerccom** [comment]
> I found that you can set the value of an existing Choices instance that you cannot access but triggering the mousedown event on the item with the value for which you're looking:
> 
> `handleSelect (obj, value) { let selectFields = obj.closest('.choices').querySelectorAll('.choices__item--selectable') for (let i = 0; i < selectFields.length; i++) { if (selectFields[i].dataset.value === value) { console.warn(selectFields[i].dataset.value) selectFields[i].dispatchEvent(new Event('mousedown')) } } }` (obj here is a select element)

Thanks. You saved time! I made the code readable.

```js
const selectInput = document.querySelector("#selectInput");
if (selectInput.tagName == 'SELECT') {
    const choiceItems = selectInput.closest(".choices").querySelectorAll(".choices__item--selectable");
    for (let i = 0; i < choiceItems.length; i++) {
        if (choiceItems[i].dataset.value === "{VALUE_TO_BE_SET}") {
            choiceItems[i].dispatchEvent(new Event('mousedown'));
        }
    }
}
```

**Comment by dphaas2004** [comment]
@HermanSchoenfeld I agree.  The workaround I have found for this was pretty simple.  may not work for @aleehedl but for anyone with source code access should work fine.  Just simply append the returned choices object to the element at initialization.
`let element = document.querySelector("#ChoicesDiv");
  element.choices = new Choices(element, {});`

from there you can run methods in other functions pretty easily.

[https://codepen.io/dphaas2004/pen/xxMJYaV](url)

hope it helps someone as I too spent most of my day searching the API and code for a way to to do this.

**Comment by acenkus** [comment]
> @HermanSchoenfeld I agree. The workaround I have found for this was pretty simple. may not work for @aleehedl but for anyone with source code access should work fine. Just simply append the returned choices object to the element at initialization. `let element = document.querySelector("#ChoicesDiv"); element.choices = new Choices(element, {});`
> 
> from there you can run methods in other functions pretty easily.
> 
> https://codepen.io/dphaas2004/pen/xxMJYaV
> 
> hope it helps someone as I too spent most of my day searching the API and code for a way to to do this.

That's actually not bad solution, I think! Thanks!

**Comment by ngohuytrieu** [comment]
> handleSelect (obj, value) { let selectFields = obj.closest('.choices').querySelectorAll('.choices__item--selectable') for (let i = 0; i < selectFields.length; i++) { if (selectFields[i].dataset.value === value) { console.warn(selectFields[i].dataset.value) selectFields[i].dispatchEvent(new Event('mousedown')) } } }

Dude, you saved my life. It took me days for this solution. Thanks bro!
