### ISSUE TITLE
Configuring using data attribute

### ISSUE THREAD

**Issue by pavelloz** [jshjohnson/Choices#389]
Hey,

Good job on the script, im enjoying using it so far :).

Is there any way of configuring options via data attributes no not pollute javascript files (i have 3 selects on the page, only one of them needs search, only one of them needs to be unsorted) - i would like to avoid marking them with some classes/ids and then deciding on what options to pass.

Deciding on select configuration on a per select basis in data-attributes seems reasonable. I think select2 has this approach and it works great - you initialize your select with global config (defaults extended with your overrides) and then specific options are applied on top of that for the specific select.

**Comment by eman1986** [comment]
right now I don't believe there is

**Comment by Stichoza** [comment]
I had the same issue and if anyone is interested, here's the code to automatically instantiate all inputs with support of `data-choices-*` attributes:

```js
document.querySelectorAll('.js-choices').forEach(item => {
    const dataset = item.dataset;
    const options = {};
  
    for (const [key, value] of Object.entries(dataset)) {
        if (key.startsWith('choices')) {
            const optionKey = key.replace('choices', '')
                .replace(/([A-Z])/g, '-$1').toLowerCase().substring(1);
  
            let parsedValue = value;
  
            if (value.toLowerCase() === 'true') {
                parsedValue = true;
            } else if (value.toLowerCase() === 'false') {
                parsedValue = false;
            } else if (!isNaN(value) && value !== '') {
                parsedValue = Number(value);
            }
  
            options[optionKey] = parsedValue;
        }
    }
  
    new Choices(item, options);
});
```

### Example usage:

```html
<select class="js-choices"
    data-choices-search-result-limit="4"
    data-choices-loading-text="Loading items...">
    ....
</select>
```
