### ISSUE TITLE
User add item & multi-select

### ISSUE THREAD

**Issue by Tam** [jshjohnson/Choices#39]
Is it possible to mix multi-select with the users ability to add custom items? Or alternatively, give the text field some predefined suggestions in the style of the multi-select?

I've tried setting the `choices` option when targeting a text field, but it doesn't seem to work.

**Comment by jshjohnson** [comment]
The ability to add custom items to a multi-select is a definite possibility - that would be fairly simple to implement. Thanks for the suggestion.

**Comment by dgt41** [comment]
@jshjohnson if you are about to implement this feature can I also ask to apply this also for single select option tag? It would be great help on something I'm currently working...

**Comment by dgt41** [comment]
@jshjohnson I would like to give some input here, so for the single value:

http://codepen.io/dgt41/pen/xRbpwK/

And for the multiple values:

http://codepen.io/dgt41/pen/RoNxro

So couple remarks here: 
- there should be an option for the value (both for sing and multiple)
- the search should return ONLY exact results not partials as it is ATM

Hope this is somehow helpful

**Comment by dgt41** [comment]
@jshjohnson any ETA here?

**Comment by jshjohnson** [comment]
@dgt41 

I'll be looking at this as soon as I can - very busy this week though. I'm happy to review pull requests.

**Comment by jshjohnson** [comment]
Just to give an update, I've begun work on this within [a feature branch](https://github.com/jshjohnson/Choices/tree/feature/select-add-items)

**Comment by dgt41** [comment]
@jshjohnson I did some testing on the feature branch, so for the single the item is added but is not active:
![screen shot 2016-11-14 at 22 48 32](https://cloud.githubusercontent.com/assets/3889375/20286699/dcffefe8-aad0-11e6-8a97-07cff202faf7.png)

For the multiple I do get some strange behaviour, adding a new item will also add another (already existing) item. I hope I can find some time debugging and contributing some code

**Comment by StephaneTrebel** [comment]
FYI, I've a push a PR (https://github.com/jshjohnson/Choices/pull/79) to help complete this feature.
Feel free to comment !

**Comment by jshjohnson** [comment]
Thanks to the PR from @StephaneTrebel, I'm close to getting this feature through the door. 

Things left to do:

- [ ] Ensure the select box stays focussed after inputting a custom choice
- [ ] Ensure the `duplicateItems` config option works with select elements (i.e. no inputting a value that already exists

**Comment by StephaneTrebel** [comment]
FYI, I've done some tests and I think that :

- [ ] Ensure the duplicateItems config option works with select elements (i.e. no inputting a value that already exists)

is ok.

I have not tested the groups since I don't use them yet. If I do I'll give a heads up :)

**Comment by erikskar** [comment]
Sorry, I do not understand how I do it.
Is it working or not?
Or is it still in development?

**Comment by jshjohnson** [comment]
@erikskar This feature is still in development

**Comment by rstacruz** [comment]
Can we help?

**Comment by jshjohnson** [comment]
Hi @rstacruz - sure! I think this feature is really close to completion. It just needs some unit tests + some investigation into option groups (i.e what should happen if you have a groups of options and you add a new option).

**Comment by dgt41** [comment]
@jshjohnson any progress here?
Can you release a beta (that doesn't include the groups part)?

Thanks

**Comment by ea2809** [comment]
News...

**Comment by jshjohnson** [comment]
There is still one issue here if you have a select box with groups - added items do not appear in the dropdown. I think in this situation a group should be added titled 'Miscellaneous' with custom items within it. I don't think this is a blocker though so i've merged this into version [2.8.0](https://github.com/jshjohnson/Choices/releases/tag/v2.8.0).

**Comment by jshjohnson** [comment]
@zhanglun This feature is no longer being actively worked on. To enable it requires a more fundamental refactor of Choices (which is in the pipeline)

**Comment by zhanglun** [comment]
@jshjohnson 
Thank you very much. I really look forward to the new version

**Comment by garyapps** [comment]
I am curious if this issue will ever be resolved. It is 2019, and the issue was raised in 2016. If there si a new version of Choices coming out, when will it release?

Also, I would suggest that until then this be listed as a limitation of the tool on the main page. I have wasted a significant amount of time integrating Choices.js into our UI, before discovering that there is no way to provide a list of tags (with <select>) and additionally also allow the user to add their own tags. Maybe other individuals can be saved from this frustration...

**Comment by MalyshevDmitry** [comment]
Wow. I thought that the Choices have this feature. I need it too.

**Comment by MalyshevDmitry** [comment]
> I have wasted a significant amount of time integrating Choices.js into our UI, before discovering that there is no way to provide a list of tags (with ) and additionally also allow the user to add their own tags. 

The same situation..

**Comment by caramiki** [comment]
I think I want to give a shot at making this work. I also want to use it for a project.

**Comment by tobias-kuendig** [comment]
For anyone looking for a good alternative that supports this feature see https://github.com/yairEO/tagify

**Comment by wgch** [comment]
> For anyone looking for a good alternative that supports this feature see https://github.com/yairEO/tagify

Works neat!

**Comment by GoldenMaximo** [comment]
[Easy temporary workaround for anyone in need](https://github.com/jshjohnson/Choices/pull/525#issuecomment-515485766)

It's not perfect and I don't actually recommend it but if you're in need/in a hurry - it's something.

**Comment by alvin** [comment]
> I have wasted a significant amount of time integrating Choices.js into our UI, before discovering that there is no way to provide a list of tags (with ) and additionally also allow the user to add their own tags.

^^ Ditto, quite surprising.

**Comment by GoldenMaximo** [comment]
> > I have wasted a significant amount of time integrating Choices.js into our UI, before discovering that there is no way to provide a list of tags (with ) and additionally also allow the user to add their own tags.
> 
> ^^ Ditto, quite surprising.

I had found myself in the same situation. Check out the fix I made. It's been working fine in production since July.

**Comment by sevenpixels** [comment]
I would love to see this as an option.

**Comment by Sogl** [comment]
Still an issue in the end of 2022? OMG... 

Today I discovered that this library does not support this function. 😢

**Comment by phonosys** [comment]
still not possible ? ;s

**Comment by djames004** [comment]
I know this is really old; however, I did come up with a solution today for my needs that was very simple. I needed a way for a user to type a client name and if our database had a match the user can select the client. If there is not a match, the user can choose what they've searched for as the client.
