### ISSUE TITLE
add ajax for textbox

### ISSUE THREAD

**Issue by eman1986** [jshjohnson/Choices#395]
I have a few instances where using a textbox makes more sense than a drop down, but the documentation says its only for the select element.

**Comment by jshjohnson** [comment]
@eman1986 Need more info, not sure what you're asking?

**Comment by eman1986** [comment]
for example, in the document:

> ajax(fn);
> Input types affected: select-one, select-multiple
> Usage: Populate choices/groups via a callback.

every single example I see of the textbox input there's nothing essentially it can do, having AJAX would be a great step forward and would avoid me having to write some funky thing that'll toggle things to make everything work.
