### ISSUE TITLE
Remove button clears placeholder

### ISSUE THREAD

**Issue by Ugoku** [jshjohnson/Choices#399]
Hi!
First of all, thanks for all your work on Choices. It's a very good `<select>` add-on 👍 

I'm running into a small problem though. First of all, some code:

```html
<select class="myElement">
    <option value="" placeholder>Brand
    <option value="Ford">Ford
    <option value="Mercedes">Mercedes
    <option value="Opel">Opel
</select>
```
```javascript
new Choices(document.querySelector('.myElement'), {
    removeItemButton: true,
});
```

This produces a nice searchable Choices dropdown, with the ability to clear a selected value:

![8cb1da2a-3a2f-4d77-9330-10f3052b266b](https://user-images.githubusercontent.com/3470653/41098219-eafe9bee-6a5a-11e8-906a-74d390fe9ba8.png)

![ea31ee0d-e8ef-4230-bd34-c3b6d4b91115](https://user-images.githubusercontent.com/3470653/41098225-f16b6b4c-6a5a-11e8-8a1a-91755fb4c729.png)

However, when the remove button is pressed, the placeholder is also gone, showing an empty dropdown:

![5ef3b86e-6d43-4844-b216-449d72af1260](https://user-images.githubusercontent.com/3470653/41098228-f75f7034-6a5a-11e8-9623-db8a83d13c3c.png)

Is this intended behaviour? If so, is there a way to show the placeholder again after clearing?

Thanks!

**Comment by andrey-hohlov** [comment]
+1

**Comment by travist** [comment]
I am also having this problem. I was able to solve it in my application by adding the following code.

```js
var placeholder = 'Select one';
var choices = new Choices(input, options);
if (choices.isSelectOneElement) {
  this.addEventListener(input, 'removeItem', () => {
    choices._addItem(placeholder, placeholder, 1, -1, null, true, null);
  });
}
```
