### ISSUE TITLE
Clear current selected value on select-one element

### ISSUE THREAD

**Issue by chymz** [jshjohnson/Choices#4]
It's more a enhancement than a bug.

Can we have a button to clear current selection on select-one element ?
Like chosen does : https://harvesthq.github.io/chosen/#allow-deselect-on-single-selects

Thanks !

**Comment by chymz** [comment]
Here is a first attempt : https://github.com/chymz/Choices/commit/8d7ad122cb6f70d6eb53c3c49ff49a3d547df2c5

I don't if you want a PR or if you want to do on your own ?

(associated branch : https://github.com/chymz/Choices/tree/select-one-clear)

**Comment by jshjohnson** [comment]
If you didn't pass a placeholder and you cleared the current selection, would you expect the element to be blank?

**Comment by chymz** [comment]
Sorry for the delay, yes :)

**Comment by jshjohnson** [comment]
This has now been implemented as of version 1.1.5. 

https://github.com/jshjohnson/Choices#removeitembutton
