### ISSUE TITLE
Inline-block causes words to break

### ISSUE THREAD

**Issue by smth** [jshjohnson/Choices#401]
It'd be good to have the option of auto width elements. I tried doing this by setting `.choices` to `inline-block`, but that gives you this on a select:

![inline-select](https://user-images.githubusercontent.com/1375708/41146292-c5070de0-6afa-11e8-9d6d-bf99067b9af2.png)

**Comment by jshjohnson** [comment]
You can edit all of the CSS for Choices to suit your needs already :) There is no need to add functionality to achieve this

**Comment by smth** [comment]
Sure, that can be done pretty easily (and I did that), but was thinking the ideal solution would go further, calculating the width of the longest dropdown item etc.

**Comment by Webdinge** [comment]
But is there a way to have the dropdown as wide as the widest option? I have multiple selects. One is just 40px wide the other has a variable width. It seems that the way the select is setup there's no way to do this. You now have to style each select seperatly while an option like this would make it easier. I'm not a CSS guru so perhaps there is an easy way to accomplish this....
