### ISSUE TITLE
Add custom option with callback

### ISSUE THREAD

**Issue by xereda** [jshjohnson/Choices#405]
I have a specific need.

I need to add a feature that allows you to create a new item. But, this behavior is not the same as the component already supported, but rather the possibility of calling a callback function (or something it can attend).

Basically we need that when the user types something that is not in the list, it has a new option like "Add xyx?", And clicking on this item opens a modal for the user to fill in the required data.

What we need to know about "Choices" is if it allows me to add a new item and that this new item can call some specific callback.

The examples below illustrate the behavior I need.

![__contaazul](https://user-images.githubusercontent.com/14337850/41541217-4fdc2406-72e8-11e8-9d91-6a75b7760b49.gif)

![__zeropaper](https://user-images.githubusercontent.com/14337850/41541229-558567c8-72e8-11e8-80c7-b1812d8d7b7f.gif)

![__zendesk](https://user-images.githubusercontent.com/14337850/41541234-58a4a680-72e8-11e8-823f-0a88fa41a2b2.gif)

![__consultoria-gratis](https://user-images.githubusercontent.com/14337850/41541246-5fd355e6-72e8-11e8-8273-df0ba5daa87a.gif)

Thank you for your feedback.

**Comment by Ymx1ZQ** [comment]
I have the same need!

**Comment by ezerr** [comment]
You will have to add a new choice while the user is typing (event `search`), and trigger supporting logic when that item is clicked on (event `addItem`).
