### ISSUE TITLE
Use Disabled Option as "Placeholder"

### ISSUE THREAD

**Issue by wydflannery** [jshjohnson/Choices#41]
Would it be possible to have this plugin work with a disabled attribute so an `<option>` can be used as a placeholder? In a traditional `<select>` you could do the following to achieve this:

```
<select id="dropdown-save-to-project" class="form-control">
    <option disabled selected>Choose Project..</option>
    <option>Project #1 </option>
    <option>Project #2</option>
    <option>New Project</option>
</select>
```
When using choices, the `<select>` is shown empty until a non-disabled element is selected. I also tried using the built in placeholder/placeholderValue options but could not get it working with a single select input and didn't see any examples on the demo page.

(I also think this would degrade nicely if you opted to use a traditional `<select>` for mobile.)

**Comment by jshjohnson** [comment]
Hi @wydflannery, 

As of version 2.0.6, setting a disabled option as a placeholder item will now work.

Thanks

**Comment by wydflannery** [comment]
I really appreciate it, thank you!
