### ISSUE TITLE
How to retrieve Choices object from original <select> element?

### ISSUE THREAD

**Issue by stephendolan** [jshjohnson/Choices#410]
What is the recommended way to retrieve a Choices object from the original <select> element?

On page load, I create all of the Choices objects.
At some later time, I want the selection of one dropdown to modify the contents of another dropdown, but I no longer have the Choices object for either of those dropdowns available.

**Comment by bennybee** [comment]
I'm also looking for a solution to this. The method examples rely on each Choices instance existing as a variable - which isn't always possible when initialising multiple instances.

**Comment by jshjohnson** [comment]
This is now possible. If you initiate multiple instances, an array of instances will be returned 👍

**Comment by bennybee** [comment]
Thanks, how would this work in practice?

I want to init choices on all selects on the page. Later I want add an event to a button that will find it's closest select, get it's Choices instance and update it's option list
