### ISSUE TITLE
initialising a disabled single-item select

### ISSUE THREAD

**Issue by mattlub** [jshjohnson/Choices#412]
Hello. My use-case is creating a **single-item select**, passing in a disabled `<select>` html element.

I would have expected the created `Choices` select to be disabled, but instead only the options are disabled, i.e. you can still see the dropdown but just can't change the selection.

The solution I have is to run `this.disable()` inside the **callbackOnInit** option.

----------

**Q:** Wouldn't it make sense for the whole select to be disabled automatically if a disabled html element is passed?

**Comment by jshjohnson** [comment]
@mattlub I agree I have just made this change in version 4.0.6 👍
