### ISSUE TITLE
add choices and remove choices

### ISSUE THREAD

**Issue by angeliqueIcono** [jshjohnson/Choices#413]
How can I add or remove choices on a particular event after it's initialized? (addchoice or removechoice doesn't exist in the doc)

Thank you in advance

**Comment by Ymx1ZQ** [comment]
this is the same problem I am having... it seems impossible to add a choice for the user 
(i.e. the ability of adding an email from a list... or adding an email not in the list!)

**Comment by ezerr** [comment]
You will have to set all the choices again if you want to add/remove choices. You will have to do what with `setChoices`.

````
var select = document.getElementById('yourElementId');
var picker = new Choices(select, yourConfig);
var choices = [{'value':'myValue', 'label':'myLabel'});
// whatever event you want to trigger, replace 'choice' with your event
select.addEventListener('choice', function(event) {
  // push another object into choices array
  choices.push({'value':'myOtherValue', 'label':'myOtherLabel'});
  // set the choices again by replacing all the choices with the  changed choices variable
  picker.setChoices(choices, 'value', 'label', true);
});
````

**Comment by casually-creative** [comment]
Rebuilding the whole choices list from scratch IS NOT an ACCEPTABLE answer. I have a complex select list with multiple groups and options. I don't want to write unnecessary Javascript to reconstruct a JSON structure of those groups and options. Please create methods `createChoice` and `removeChoice` so we can more fluently interact with the choices dropdown. Thank you.
