### ISSUE TITLE
Featured Request: Drag to re-order

### ISSUE THREAD

**Issue by JiveDig** [jshjohnson/Choices#417]
When displaying items in the order they were chosen, it would be great to be able to drag/sort the order after all choices are made.

**Comment by mpakus** [comment]
yeah, same request, how can we do that, any recommendations @jshjohnson ?

**Comment by heldchen** [comment]
same, the only feature I'm missing to finally replace Selectize

**Comment by jshjohnson** [comment]
The aim of Choices has always been to be as lightweight as possible. Features like drag and drop add a lot of complexity for little user benefit IMO.

**Comment by JiveDig** [comment]
I respect your decision and think Choices is great.

One instance of Choices has been to chooce social icons for sharing and many clients prefer their most active social networks first so was hoping to give them an option to reorder. Choices may not be the best library here after all, but i’m still happy to have a lightweight option for things that don’t need anything else. 

Thanks for all your work :)

**Comment by collimarco** [comment]
+1 I would also love to reorder items with drag and drop: I use this library for array inputs, and for arrays the order matters.

**Comment by aleaforny** [comment]
+1 Also, would love this feature as the rest of this plugin is awesome. Perhaps it could be an additional file/library if you wish to keep Choices ligthweight for those who doesn't use these features

**Comment by joeworkman** [comment]
@JiveDig Long time no see! I submitted a PR that adds this 😄
