### ISSUE TITLE
Clone choice select

### ISSUE THREAD

**Issue by timersys** [jshjohnson/Choices#418]
I'm having a hard time trying to close a choices select dyanmically. Basically I have a "add new row" button that will duplicate the previous row which includes a choices js.

- Using jquery clone is not working
- Initializing select again is not working
- Just copying the select input and then trying to new Choices on it is not working.

Anyone faced the same issue?

**Comment by drannex42** [comment]
Any updates? Having the same issue over here.

Sidenote: This is why the stale-bot is a **bad* idea.

**Comment by drannex42** [comment]
I opened the #488 ticket
