### ISSUE TITLE
callbackOnChange isn't triggered when backspacing an item

### ISSUE THREAD

**Issue by nathanielw** [jshjohnson/Choices#42]
From the description in the readme, it seems like the `callbackOnChange` callback should be called when an item is added or removed via any sort of user-input. Currently removing an item only triggers it if an item is removed using the button, not if it is backspaced. 
Seems like it should be called after [line 817](https://github.com/jshjohnson/Choices/blob/ef1e7d23effe27a8f9d72a6c1efa3ac900c15de7/assets/scripts/src/choices.js#L817).

**Comment by jshjohnson** [comment]
Good spot, thanks. Looking into this now.

**Comment by jshjohnson** [comment]
This should now be resolved as of version 2.0.3. Thanks!
