### ISSUE TITLE
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event.

### ISSUE THREAD

**Issue by pedroresende** [jshjohnson/Choices#426]
Whenever I click on the select option, I get the following violation on console.log

```
[Violation] Added non-passive event listener to a scroll-blocking 'mousewheel' event.
```

a possible fix you be to add the `{passive: true}` flag to the `addEventListener` https://stackoverflow.com/questions/46542428/warning-added-non-passive-event-listener-to-a-scroll-blocking-touchstart-even/46542547

**Comment by pedroresende** [comment]
any news about this ?

**Comment by jshjohnson** [comment]
I'm unable to replicate this in Firefox or Chrome

**Comment by pedroresende** [comment]
@jshjohnson it was on chrome 68

**Comment by jshjohnson** [comment]
I cannot replicate this and the error doesn't actually make sense as Choices doesn't listen to the 'mousewheel' event. I imagine it's being caused by another script on your site. 👍
