### ISSUE TITLE
Loading text not replaced

### ISSUE THREAD

**Issue by froggiefab** [jshjohnson/Choices#43]
Hi,

When using Choices in 'multiple mode', the "Loading..." text is not replaced if "placeholderValue" is not set or if 'placeholder' is set to "false".
![choices - loading](https://cloud.githubusercontent.com/assets/5774943/18787648/f74d1d9a-81a3-11e6-92bf-c22296abaffe.png)

Thanks.

**Comment by jshjohnson** [comment]
Thanks - will be pushing a fix shortly!

**Comment by jshjohnson** [comment]
This is now resolved as of version 2.0.7. Thanks.

**Comment by froggiefab** [comment]
Thanks for the quick fix :)
