### ISSUE TITLE
Autocomplete for Text-Mode

### ISSUE THREAD

**Issue by tomglx** [jshjohnson/Choices#432]
Why can't one define choices via the equal named attribute for autocomplete suggestions
in Text-Mode? Instead there's only a bubble echoing the input I'm already seeing. The 
functionality is already there, but it's only used when binding choices to a select widget.
I need a hybrid of an input field, where one can use the input for either an incremental search
in the given choices, or as free text not restricted to the given choices.
Like a windows combo box, if you will.

**Comment by Ymx1ZQ** [comment]
it seems we all need the same thing: a select with the possibility of adding options

**Comment by alanhamlett** [comment]
Could be solved with #475.

**Comment by BeebBenjamin** [comment]
I think I want this for text input.  Instead of adding what's already in the box, I want to send a request to an API and get the top match to add if I click it...
