### ISSUE TITLE
Please merge your develop branch into master

### ISSUE THREAD

**Issue by Yana-Kalandarova** [jshjohnson/Choices#435]
Hey guys,

I noticed you use deprecated  package babel-preset-es2015 in master branch.
I also know you already replace this package with babel-preset-env in develop branch.

It will be very nice to have this update in master branch as well. 
I really want to use you library for dropdowns.

Please assist ASAP!
Thanks!

**Comment by jshjohnson** [comment]
Develop has now been merged to master 🎉
