### ISSUE TITLE
Incorrect typings for callbackOnCreateTemplates

### ISSUE THREAD

**Issue by bharatramnani94** [jshjohnson/Choices#436]
In [typings file](https://github.com/jshjohnson/Choices/blob/master/types/index.d.ts), _callbackOnCreateTemplates_ should have the parameter and return type defined as:
```callbackOnCreateTemplates?: (template: Function) => any;```
while it currently has:
```callbackOnCreateTemplates?: (template: string) => string;```

Or am I missing something?

I see that the _develop_ branch has the updated types, but it isn't merged (#435). Merging that should solve this issue.

**Comment by jshjohnson** [comment]
The develop branch has been merged now 👍
