### ISSUE TITLE
Choices with "selected" attribute do not trigger "addItem" event - v3.0.4

### ISSUE THREAD

**Issue by Tahira-Farid** [jshjohnson/Choices#440]
I have recently updated all the Choices instances in the platform from v2.5.1 to v3.0.4. I have noticed that in the latest versions when a choice is pre-selected with selected: true at the point of initiation, it no longer triggers the event "addItem". For me I think this is a loss of functionality as in most cases I write the callback functionalities as a result of a choice being selected in the "addItem" event. 
Is there an alternative event can detect pre-selected choices that I should use instead? 

`

                                 let my = this;
                                      new Choices(this, {
                                          search: false,
                                          callbackOnInit: function () {
                                              let choicesArray = [];
                                              let selected = false;
                                              my.connectionTypes.forEach((type) => {
                                                  // If connectionType is set as default we pre-select it
                                                  selected = type.default

                                                 let choice = { value: type.sso.toString(), label: my.translateItem(type.name_libelle.translations), selected: selected };
                                                 choicesArray.push(choice);
                                             });

                                             this.setChoices(choicesArray, 'value', 'label', 'selected', false);
                                            
                                             // Add event listener for when a choice is selected
                                             this.passedElement.addEventListener('addItem', function(event) {
                                                  // When choice is selected update is_sso value
                                                  my.is_sso = event.detail.value;
                                             });
                                        }
                                   });

`

**Comment by jshjohnson** [comment]
@Tahira-Farid I'm a bit confused. `setChoices` only accepts 4 arguments. See (here)[https://github.com/jshjohnson/Choices#setchoiceschoices-value-label-replacechoices]?

**Comment by Psyphant** [comment]
Hey guys!

I have the same problem. I want to add a handler on the selected item (to remove the item) and need an event like "addItem" to be triggered by the setChoices function.

Can somebody help me?
