### ISSUE TITLE
ChoicesJS Web Component (available)

### ISSUE THREAD

**Issue by moelders** [jshjohnson/Choices#441]
Hello,

I write on behalf of [adidas organization](http://github.com/adidas), we have chosen your select component to be part of our public design library.

In order to easy the integration with modern frameworks we have created a real Web Component with it: [_choicesjs-stencil_](https://github.com/adidas/choicesjs-stencil).

- [adidas YARN Design System](https://adidas.github.io/adidas-yarn-design-system/) (WIP).
- [_choicesjs-stencil_ demo](https://adidas.github.io/choicesjs-stencil/).

Do not hesitate to contact us for clarifications, contribution, etc.

[**adidas**](https://adidas.com)

**Comment by jshjohnson** [comment]
@moelders Awesome! Thanks

**Comment by moelders** [comment]
@jshjohnson, if you agree, you can add a small section in your README referencing this wrapper.

Thank you!

**Comment by moelders** [comment]
We have released a new version fixing issues with the component in forms: [choicesjs-stencil@1.1.0](https://github.com/adidas/choicesjs-stencil/releases/tag/1.1.0).

**Comment by jshjohnson** [comment]
@moelders Will update the README ASAP :)

**Comment by moelders** [comment]
Thanks @jshjohnson!

**Comment by jshjohnson** [comment]
I've added a link to the web component to the README. FYI, a major version has just been release 👍 

Thanks again.
