### ISSUE TITLE
Two Select Elements Related to whatever is selected

### ISSUE THREAD

**Issue by frogydiak** [jshjohnson/Choices#450]
Hello! It's more of a question rather than an issue. I wanted to use Choices for a project with 2 select elements: Primary Category and Other Categories. 

- Both will  have the same values
- When a value is selected in whichever element, that value will be disabled in the other.

Is that possible with Choices? How?

Thanks!

**Comment by jshjohnson** [comment]
Yes that is possible - there is an example of this on the demo site :)
