### ISSUE TITLE
Can not get multiple select values after update 4.x

### ISSUE THREAD

**Issue by CodeExplore** [jshjohnson/Choices#451]
Hi,

I am not sure how I can explain it.

I am trying to get multiple select values with **$select.val()** but i cannot get values after update 4.x

Why we need this, because sometimes we are using **$form.serialize()**, **$form.serializeArray()** for AJAX save form.

Btw, normal select works. The problem was multiple select. You can see examples:

Works: [v3.0.4 JSFiddle Example](http://jsfiddle.net/g2nw4zxr/)
Not Works: [v4.0.1 JSFiddle Example](http://jsfiddle.net/g2nw4zxr/1/)

The great library really. thanks for creating it.
Regards

**Comment by jshjohnson** [comment]
@CodeExplore Thanks, it's a bug and an easy fix. Will update you when it's been fixed 👍

**Comment by CodeExplore** [comment]
@jshjohnson thank you for time. I will wait for the update. :+1: 

Have a nice day.
Regards

**Comment by jshjohnson** [comment]
@CodeExplore This has now been resolve :) http://jsfiddle.net/g2nw4zxr/2/

**Comment by CodeExplore** [comment]
@jshjohnson Great! It works :100: I moved to the new version now :+1: 

Thanks for the effort.
Regards
