### ISSUE TITLE
can't assign to property "keyCode" on false: not an object

### ISSUE THREAD

**Issue by gmask** [jshjohnson/Choices#453]
Just updated Choices from 3.0.4 to 4.0.5 and this error started appearing: `can't assign to property "keyCode" on false: not an object`.

I'm using Choices in Vue.js like this:

First, here is the source element:
```
<select id="category-select" multiple @change="onCategorySelect"/>
```

Initialize Choices:
```
this.categorySelect = new Choices('#category-select', {
        removeItemButton: true,
});
```

Set options:
```
axios.get(route('categories.get.select'))
    .then(response => {
        this.categorySelect.setChoices(response.data, 'value', 'label');
});
```

What's odd is that Choices actually renders and I can use it, however the source element is not hidden as before and there are many errors thrown if I use `customProperties`, for example. This was all working before, and I don't think I'm using any of the breaking changes noted in the releases between these versions.

I also noticed that the npmjs.com package lists latest version at 4.0.5, however GitHub is at 4.0.3. Could this be the reason..? I tried manually pulling in 4.0.3 with same results.

**Comment by jshjohnson** [comment]
@gmask Hey, looks like a bug. I'll take a look tomorrow :)

**Comment by jshjohnson** [comment]
@gmask Would you be able to provide a jsfiddle highlighting the problem please? I am unable to replicate the bug my side. Thanks

**Comment by gmask** [comment]
In the process of building the jsfiddle I discovered the issue was with my stylesheet (I had overriden quite a lot of the `choice.scss` file). In the latest update the source changed and my custom styles no longer worked and were the source of the above problem.

However, now there is another problem: I am getting `TypeError: "data.customProperties is undefined"`. I'm assuming this is also due to a change in the way the items are processed. 

Here's my whole template where you can see how I'm trying to access the customProperties key, like `data.customProperties.City`:

```
callback: function (template) {
        let classNames = this.config.classNames;

        return {
            item: (data) => {
                return template(`
          <div class="${classNames.item} ${data.highlighted ? classNames.highlightedState : classNames.itemSelectable}" data-item data-id="${data.id}" data-value="${data.value}" ${data.active ? 'aria-selected="true"' : ''} ${data.disabled ? 'aria-disabled="true"' : ''}>
            ${data.label}
            <span class="text-xs font-bold text-grey-darker ml-1">${data.value}</span>
          </div>
        `);
            },

            choice: (data) => {
                return template(`
          <div class="${classNames.item} ${classNames.itemChoice} ${data.disabled ? classNames.itemDisabled : classNames.itemSelectable}" data-select-text="${this.config.itemSelectText}" data-choice ${data.disabled ? 'data-choice-disabled aria-disabled="true"' : 'data-choice-selectable'} data-id="${data.id}" data-value="${data.value}" ${data.groupId > 0 ? 'role="treeitem"' : 'role="option"'}>
            ${data.label} <span class="text-xs bg-grey-light rounded p-1">${data.value}</span>
            <div class="text-xs mt-2 text-grey-darker">
                ${data.customProperties.City} ${data.customProperties.State ? ', ' + data.customProperties.State : ''}
            </div>
          </div>
        `);
            },
        };
    }
```

**Comment by jshjohnson** [comment]
@gmask I can see the problem. `classNames` is always the first argument passed to a template function. 

Your code should be like:

```
item: (classNames, data) => {...},
choice: (classNames, data) => {...}
```

**Comment by gmask** [comment]
@jshjohnson thanks, that did the trick... no idea how it was working before 🤔
