### ISSUE TITLE
Exact phrase match isn't available as a result, but partial sometimes is

### ISSUE THREAD

**Issue by JiveDig** [jshjohnson/Choices#454]
I have a select field where each option has a value of a url to redirect to and the label is the name of a school. If I search for "mary" I get Maryland as an option, but if I type an more characters than that, including "maryland" or "Maryland" then the actual Maryland options isn't available. I've been trying different settings all morning and can't get it to work. Any ideas before I bail on Choices?

<img width="387" alt="screen shot 2018-11-01 at 12 06 53 pm" src="https://user-images.githubusercontent.com/540990/47863856-acfc0880-ddce-11e8-8a2f-556b0c2d354f.png">

<img width="324" alt="screen shot 2018-11-01 at 12 07 00 pm" src="https://user-images.githubusercontent.com/540990/47863851-a8cfeb00-ddce-11e8-9a82-6781f61a4420.png">

This is where I left off with my code:
```
jQuery(document).ready(function($) {

	new Choices( $( '.college-search' )[0], {
		searchEnabled:    true,
		customProperties: ['label'],
		searchResultLimit: 8,
		shouldSortItems: true,
	});

});
```

**Comment by jshjohnson** [comment]
@JiveDig Choices uses a library called Fuse to handle fuzzy searching. You can pass any [Fuse config options](http://fusejs.io/) when you [initialise Choices](https://github.com/jshjohnson/Choices#setup) by passing a `fuseOptions` object.
