### ISSUE TITLE
Browser lockup issues with 4.1.0

### ISSUE THREAD

**Issue by travist** [jshjohnson/Choices#455]
We are looking to upgrade the [Form.io renderer](https://github.com/formio/formio.js) to 4.1.0 of Choices, but there is currently a bad bug where the browser locks up on large lists. We fixed this for the 3.0.4 branch, but this fix has not made its way into the 4.x branch it seems.

Here is 3.x
  http://jsfiddle.net/travistidwell/6wh0znj5/

Here is 4.x
  http://jsfiddle.net/travistidwell/h20xacun/  

Here is the pull request where we fixed this in the 3.x branch.
  https://github.com/jshjohnson/Choices/pull/310

**Comment by jshjohnson** [comment]
@travist Good spot - this should have gone into the `develop` branch too! Putting a fix now.

**Comment by jshjohnson** [comment]
I've published a beta version to npm. It seems to have resolved the issue:

http://jsfiddle.net/xbzfc6e9/

**Comment by jshjohnson** [comment]
This should be resolved as of [version 5](https://github.com/jshjohnson/Choices/releases/tag/v5.0.0)

**Comment by travist** [comment]
The Form.io renderer is still currently on 3.x. We tried to upgrade to 4.x at one point and could not move forward with that upgrade because of this performance problem. Do you claim that the issue is resolved in > 5.x?  If so, then I may try upgrading in the coming weeks and I will let you know. 

If you want an example case that was failing for 4.x, then this page would make the browser lock up completely when I upgraded to 4.x.

http://formio.github.io/formio.js/app/examples/select.html

It would get really bad in the "Lazy Loading" and External Sources portion of the dropdown since that adds > 300 entries to the dropdown.

Let me know what you think.

**Comment by jshjohnson** [comment]
@travist Version 3 and versions greater than 5 have the same fix detailed here: https://github.com/jshjohnson/Choices/pull/310

**Comment by travist** [comment]
Thanks for your response. I did some testing this weekend and it looks good. We are updating our renderer to include latest choices library. You can see it here.

http://formio.github.io/formio.js/app/examples/select.html
