### ISSUE TITLE
It's impossible to enable Choices instance that is created from initially disabled <select>

### ISSUE THREAD

**Issue by anton-github** [jshjohnson/Choices#457]
Hi, thanks for your great work!

**Description:**
I want to create Choices instance from native select that contains collection of its native <option>.
When I call Choices constructor, the select input can be disabled or enabled, and later I am free to change that state in accordance with the app business logic (by calling enable method). So I reckoned this is pretty common use-case but the behaviour I faced is strange.

**Expected behaviour:**
If select is initially disabled, after I call enable method it must be possible to select one of initial options (if they weren't disabled, so there wasn't a disabled attribute on the <option>).

**Current behavior:**
If select is initially disabled, after I call enable method, I can click on the control and open the list of options but I still can't choose any of them. Here is the example: https://jsbin.com/vigunef/edit?html,css,js,console,output

**My considerations:**
I seems to me, this line can cause that issue. (https://github.com/jshjohnson/Choices/blob/496db95153fe88585b7b454d41315fac867a9be4/src/scripts/choices.js#L1909)
For me the logic here is quite strange, because select and its options have their own «disabled state», but If I am not mistaken, according that line, if the native select is disabled its options become disabled too, despite their own «disabled state». So later, when we want to activate a Choices instance, we will not able to choose any of options because they all has already been marked as disabled. So maybe we should check only they own «disabled state»?

By the way, the css assets from CDN (base.min.css and choices.min.css) aren't available for some reason so I had to copy final css to the jsbin.com

Thanks!

**Comment by jshjohnson** [comment]
@anton-github Hey. I agree that is strange behaviour. Will look into this for you 👍

**Comment by jshjohnson** [comment]
@anton-github Which CDN are you using by the way?

**Comment by MeekLogic** [comment]
Same issue. Self-hosted.

This issue does not happen when using `setChoices()` but when initially disabling the select and having options already provided via HTML.

**Comment by kzkn** [comment]
@jshjohnson 
I have same issue. I use the version 9.0.1.

Here is a minimal reproducible example.
https://gist.github.com/kzkn/3157bfffd081a4043caf87437df82129

**Comment by beelzebub1** [comment]
Got same as above, `9.0.1` too. However if i toggle disabled to `false` before choices init, then re-assigning disabled to `true` i'm all set. Let's go bad workaround for now 😄
