### ISSUE TITLE
Choice element not re-enabling after Ajax call in 4.1

### ISSUE THREAD

**Issue by noelrappin** [jshjohnson/Choices#458]
I have code that is using a choice element and is calling the following method on search:

```
search(event: CustomEvent) {
    CustomerLookupController.choiceElement.ajax(() => {
      fetch(`/customer_lookup.json?query_string=${event.detail.value}`).then(
        response => {
          response.json().then(data => {
            CustomerLookupController.choiceElement.setChoices(
              data,
              "id",
              "display",
              true
            )
          })
        }
      )
    })
  }
```

This broke in 4.1. After I type one character into the choice element, triggering this search, the choice element disables, but does not reenable. (It continues to show a "Loading..." place holder. This is true even if I explicitly call `enable()` on the choice element after the `setChoices` call.

I can't tell whether I need to do something different to make this work, or whether this is a regression in 41.

**Comment by jshjohnson** [comment]
@noelrappin l think this may be a regression issue - would you be able to provide a jsfiddle reproducing the problem please?

**Comment by noelrappin** [comment]
I think it will be tricky to set up a fiddle because it depends on the Ajax call, but I'll see what I can do.

**Comment by majksner** [comment]
Here is the jsfiddle

https://jsfiddle.net/60ac9hL3/1/

**Comment by websnacks** [comment]
Hi, I have the same problem (TypeError: e.replace is not a function) and fixed it with creating a loop to change the id into a string. (not the best solution but it worked)

`for (const key of Object.keys(data.results)) {
  data.results[key]['id'] = toString(data.results[key]['id']);
}`

**Comment by noelrappin** [comment]
I still just get the system hanging without any error being flagged

**Comment by hg64** [comment]
Hi there, love your control but having the same problem with ajax calls leaving the control in a disabled state.
Using v7.0.0 to replace options dynamically on a select-single

choicesList.passedElement.element.addEventListener('showDropdown', function(event) {
choicesList.ajax(function(callback) {
fetch(url).then(function(response) {
   response.json().then(function(data) { callback(data.items, 'id', 'text'); });
   }).catch(function(error) {console.log(error);});});
}, false);
