### ISSUE TITLE
removeActiveItemsByValue method doesn't work properly with choice event

### ISSUE THREAD

**Issue by derherbst** [jshjohnson/Choices#459]
Hello! 
I want to create custom select with checkboxes using multiple-select. 
Expected behavior: 
When I click on option, mark in checkbox appears and option appears in items list (with delete button)
When I click again on selected option in choice list, the item in items list disappears.

So, now I'm using choice event. I'm comparing two properties 'choiceId' in choice object and e.detail.choice.id in custom event objects. So if these two properties match I use removeActiveItemsByValue(e.detail.choice.value).

Now it works twice because choice event works like addItem event. So first it deletes item from items list and then adds it in the end. 

The question is how can I use that method properly? Is there any way to use it with choice event? 

The code below
![image](https://user-images.githubusercontent.com/20741461/48136623-2dc87200-e2b1-11e8-8599-909b9b765d18.png)

**Comment by PredragPeranovic** [comment]
I have encounter same problem.
Reason for probelem is in choices.js when _addItem is called after triggering choice event (from line 830)
`this.passedElement.triggerEvent(EVENTS.choice, {
      choice,
    });

    if (choice && !choice.selected && !choice.disabled) {
      const canAddItem = this._canAddItem(activeItems, choice.value);

      if (canAddItem.response) {
        this._addItem({
          value: choice.value,
          label: choice.label,
          choiceId: choice.id,
          groupId: choice.groupId,
          customProperties: choice.customProperties,
          placeholder: choice.placeholder,
          keyCode: choice.keyCode,
        });

        this._triggerChange(choice.value);
      }
    }`

Quick hack-fix without changing choices.js is to use onTimeout when removing item something like:
`
 input.addEventListener('choice', event => {
    const choice = // optain choice instance  
   if (choice.selected) {
     setTimeout(() => choice.removeActiveItemsByValue(choice.value), 100)
  }
})

`

**Comment by prasanna1211** [comment]
Great, this was the exact one I was looking for.
