### ISSUE TITLE
Server side filtering

### ISSUE THREAD

**Issue by froggiefab** [jshjohnson/Choices#46]
Hi,

I'd like to add a server-side filtering feature which would fetch data as the user inputs text (with a 'minChars' and a 'delay' properties). 

Is that something that you plan to add in a future release ?

Thanks

**Comment by jshjohnson** [comment]
Hi @froggiefab,

So just I'm clear, you would like the ability to specify how many characters are needed before Choices will filter as well as the delay after each key press? 

Thanks,

Josh

**Comment by froggiefab** [comment]
Yes that would be great.

But I also would like to be able to fetch choices from the server as the user inputs text (make a request to receive filtered choices from a large dataset rather than loading all choices on init).

Thanks,

Fabien

**Comment by jshjohnson** [comment]
Ah I see what you mean. I could potentially add a new callback for when the user types so you can then handle your server logic from within that callback.

I'll look into this, sounds like a cool idea.

**Comment by froggiefab** [comment]
Great, thanks a lot !

**Comment by jshjohnson** [comment]
As of version 2.1.0 there is now a callback when a user searches + you can now specify a minimum character limit via the [ 'searchFloor'](https://github.com/jshjohnson/Choices#searchfloor) config property.
