### ISSUE TITLE
setChoiceByValue does not remove choice from dropdown

### ISSUE THREAD

**Issue by ezerr** [jshjohnson/Choices#463]
I am creating my choices on a multi select dynamically with `setChoices` and `duplicateItemsAllowed` set to false, then immediately selecting the items I want using `setChoiceByValue`. This works fine, but the choice is not removed from the dropdown. The behavior should be just like if the user selected the choice, the item is selected, and the choice is removed from the choices dropdown.

**Comment by jshjohnson** [comment]
@ezerr Hey - could you provide a jsfiddle reproducing the problem please?

**Comment by ezerr** [comment]
@jshjohnson Sure thing. In the below link, as soon as you load it, it will have a selected item that was set by `setChoiceByValue`. But when you click on the select, you can still see that selected item in choices, it was not removed.

https://jsfiddle.net/mhkbs0zt/2/

**Comment by jshjohnson** [comment]
@ezerr Thanks - it was a regression issue. It's been fixed in 4.1.3 now :)
