### ISSUE TITLE
Searching with ajax broken in 4.1.0

### ISSUE THREAD

**Issue by samueldjack** [jshjohnson/Choices#466]
Version 4.1.0 seems to have introduced a bug which isn't present in 4.0.5. Namely, when I open the dropdown and start typing, the textbox looses focus after each character and I can't type any more.

Our code is responding to the search event by calling the ajax method (and it is making sure to call the callback supplied by the ajax method once it has obtained the data).

**Comment by jshjohnson** [comment]
Hey - could you please provide a jsfiddle highlighting the issue please?

**Comment by edtownend** [comment]
I've run into this problem too - as a workaround, I'm calling `choices.input.element.focus();` immediately after the call to the ajax callback.

**Comment by majksner** [comment]
Experiencing similar issue. I'm losing focus on each keypress when using callback. If I user setChoices then after first keypress select becomes disabled.

**Comment by majksner** [comment]
Here is the Jsfiddle

https://jsfiddle.net/60ac9hL3/1/

**Comment by tkaprol** [comment]
I have exactly same issue too.

**Comment by majksner** [comment]
Use the latest version, and run the callback method after ajax call.

**Comment by ssc-hrep3** [comment]
You need to use the `callback` function instead of `setChoices()`. I've updated the fiddle of @majksner here:
https://jsfiddle.net/dz3gwhb7/

**Comment by noelrappin** [comment]
Hey, I still see this problem even if I use `setChoices` (at least in some browsers). If I explicitly add focus per @edtownend, it comes back, but slowly and keystrokes can get lost. Has anybody fixed this, or do I need to revert back to 4.0.7?

**Comment by jshjohnson** [comment]
Closing as `ajax` has been removed from version 8.*

**Comment by yogeshjain999** [comment]
I faced same issue as @samueldjack while using `setChoices` with a promise.

```js
example.setChoices(async () => {
  const items = await fetch('/items');
  return items.json();
});
```

But if the data is loaded separately and then passed to `setChoices`, it seems to work.

```js
async onSearch() {
  const response = await fetch('/items');
  const data = await response.json();

  example.setChoices(data, 'value', 'label', true);
}
```

**Comment by KaraAJC** [comment]
Looks like this is related: https://github.com/jshjohnson/Choices/pull/701
