### ISSUE TITLE
Can't disable first item on initiate

### ISSUE THREAD

**Issue by markjoeljimenez** [jshjohnson/Choices#473]
Not sure if intended, but I can't seem to disable the first option.

https://jsfiddle.net/uf9bmpy6/

**Comment by astr0sl0th** [comment]
I am having the same issues too:

![screenshot 2019-02-07 at 16 06 05](https://user-images.githubusercontent.com/9317246/52424850-bba33b80-2af2-11e9-9456-286b1c4a92f1.jpg)
