### ISSUE TITLE
Custom entry for Select Elements

### ISSUE THREAD

**Issue by coleherzer** [jshjohnson/Choices#475]
Hi there, 

I may be missing something, but it currently seems that adding free entry custom options is not supported in Choices when the element passed in `new Choices` is a Select element (essentially the functionality added by the `tags: true` option in Select2 which allows free entry if no results match the search). I see that similar functionality is supported for Input elements, but it looks like this isn't possible if the initialized element is a Select. 

I'm just curious if this is something that may be expected in a future version of Choices, or if there may be some quick work around I'm not seeing.  

Thanks so much!

**Comment by JoshHarrington** [comment]
+1 for this issue, spent ages trying to figure out why I couldn't get the tags feature working.

Eventually figured out that when choices is initialised on a `select` element then tagging does not function in the way it will on `input[type="text"]` - not sure if I just missed this in the docs, but would appreciate if the functionality (of letting the user add new items) could be added for select elements. Thanks!

**Comment by alanhamlett** [comment]
+1
