### ISSUE TITLE
Support searching in group names

### ISSUE THREAD

**Issue by stof** [jshjohnson/Choices#477]
It would be great if searching could (optionally) match in group names, bringing  the options of that group in the search results.

I'm currently using https://github.com/harvesthq/chosen and it has this feature. I discovered your library while looking for jQuery-free alternatives (in my quest to identify the road to removing jQuery from our projects).

**Comment by stof** [comment]
I don't think having a bot marking issues as stale on the repo is a good idea if the maintainer does not take a look at them at all during the 60 days timeframe.

Anyway, that feature request is still applicable.

**Comment by MalyshevDmitry** [comment]
+1

**Comment by dpow40** [comment]
+1

**Comment by Pezhvak** [comment]
+100000
