### ISSUE TITLE
Upgraded from Choices v3 to v4 and it stopped working

### ISSUE THREAD

**Issue by DarrenMack-OD** [jshjohnson/Choices#481]
Hi,
I recently upgraded to Choices.js v4 from v3 and now it won't work, I just get a blank area where the drop-downs should be... Is there any major change to the code I should be aware of?

**Comment by jshjohnson** [comment]
@DarrenMack-OD Yes - https://github.com/jshjohnson/Choices/releases/tag/v4.0.0
