### ISSUE TITLE
Text input as Select dropdown

### ISSUE THREAD

**Issue by achchu93** [jshjohnson/Choices#487]
I have a text input field. i wanna make it as "Multiple select input" with choices dropdown. Can i achieve it with this plugin?

**Comment by gkweb** [comment]
@achchu93 - Do you have control over the seed element? It would be advised to switch to a multi select element.

See in the [examples](https://joshuajohnson.co.uk/Choices/) - Multiple select input

**Comment by achchu93** [comment]
@gkweb i think you didnt understand my question. Even for the multi select, the element should be a select element. if it is an text input it doesnt work. For text input it takes as tags. i want to initialize multiple select on text input element.

**Comment by alanhamlett** [comment]
Is this a duplicate of #475?
