### ISSUE TITLE
Using .clone() on a parent element does not show choices options on newly cloned element

### ISSUE THREAD

**Issue by drannex42** [jshjohnson/Choices#488]
If you have a parent element that holds the child-element [select] and you call a .clone() on the parent element choices.js will not propagate when you click on the select element inside the new cloned element.

Example: 

```
<div class="parent">
     <select>...</select>
</div>
```
```
$('.parent').clone();
```
Choices won't re-instantiate itself onto the newly formed cloned item.

**Comment by jshjohnson** [comment]
Could you please provide a JS fiddle highlighting the problem please?

**Comment by AndrewHaine** [comment]
I've encountered the same issue ([Fiddle here](https://jsfiddle.net/Andy_Haine/2p3k6dvg/5/)).

My workaround was to `.destroy()` the existing Choices instance and then re-initialize after the cloned elements were appended

**Comment by drannex42** [comment]
> My workaround was to `.destroy()` the existing Choices instance and then re-initialize after the cloned elements were appended

If I remember correctly this was the same way I handled the issue. Thanks for writing up how to solve it, perhaps it'll help someone else out going forward.
