### ISSUE TITLE
how can add necessary components with es6 modules to reduce size of js file

### ISSUE THREAD

**Issue by riiccardo** [jshjohnson/Choices#489]
hey @jshjohnson thanks for great plugin 👍 

Take a look at [Glide](https://github.com/glidejs/glide) to understand my description.
for example i just need `autoplay` i just use this code

``` javascript
import Glide, { Autoplay } from '@glidejs/glide/dist/glide.modular.esm'

new Glide('.glide').mount({ Autoplay })
```

similar issue here #64

u said: 

> Update: With Webpack 2 Choices is reduced to 55kb!

but in github `assets/scripts/choices.min.js` shows
**`choices.min.js : 97.7kb`**

Use the **`rollup`** instead of **`webpack`**  to make bundle size lighter

thanks regards 😍

**Comment by jshjohnson** [comment]
Choices is now using Webpack 4 which has made some improvements to bundle size. I've also removed some redundant code which brings the bundle size down to ~22kb gzipped. 

I do endeavour to split Choices into 3 components (1 for each input type) but I haven't found the time yet
