### ISSUE TITLE
Incorrect method name in docs

### ISSUE THREAD

**Issue by pavel-mazhuga** [jshjohnson/Choices#490]
There is a function called "setChoiceByValue" mentioned in the docs. However, it's actually called "setValueByChoice". This should be fixed, I guess. Great plugin, btw.

**Comment by jshjohnson** [comment]
Are you sure you are using the latest version? This was recently renamed.

**Comment by pavel-mazhuga** [comment]
Right, sorry. It turned out I'm using version 3.0.4. Thanks!
