### ISSUE TITLE
Hide the "click to select" text on hover?

### ISSUE THREAD

**Issue by youradds** [jshjohnson/Choices#491]
Hi,

Cool plugin - thanks :) One problem I'm having, is that I don't want the "click to select" text to show to the right of the options. The reason being, is that it's only going to be 100-200px wide, and its causing the value to go onto multiple lines :/ How do I get rid of it? I tried commenting this out of the SASS file but it didn't help:

```
  .#{$choices-selector}__item--selectable {
    @media (min-width: 640px) {
      padding-right: 100px;
      &:after {
        content: attr(data-select-text);
        font-size: $choices-font-size-sm;
        opacity: 0;
        position: absolute;
        right: 10px;
        top: 50%;
        transform: translateY(-50%);
      }
      [dir="rtl"] & {
        text-align: right;
        padding-left: 100px;
        padding-right: 10px;
        &:after {
          right: auto;
          left: 10px;
        }
     
``` }
    }

(and yes, I'm using SASS and then building it into my own file :))

TIA

Andy

**Comment by leooon** [comment]
This was my workaround for this, but I guess the best approach is to replace the entire **choices__item--selectable** class.

`
.choices__list--dropdown .choices__item--selectable:after {
	display: none !important;
}
 .choices__list--dropdown .choices__item--selectable {
	padding-right: 0 !important;
}`

**Comment by rista86** [comment]
There is also option to change this text by setting:
`itemSelectText: ""`
Only you will still have unneeded padding, so be sure to clear that as well.

**Comment by divan** [comment]
That would be actually nice to have in options.

Having right half of the select list to be occupied by 'Press to select' text is not very common. Most people would expect to have more control over how option item actually looks like.
