### ISSUE TITLE
Performance issues - setChoiceByValue() and form.reset();

### ISSUE THREAD

**Issue by hope55** [jshjohnson/Choices#493]
I started to use Choices.js instead of select2 in my project, but ran into performance issues, when i'm having ~1000 options in my employee list with a simple "single-select" setup . 

Every time I refresh the user datasheet form containing my Choices dropdown (making form.reset() + using setChoiceByValue() to select the current employee-manager from the dropdown), Choices will re-render the HTML content of the dropdown multiple times (by making incredible amount HTML parses), however there is no point of doing this. This causes ~3000 ms (!) lag when refreshing a simple user datasheet. 

I can see Choices.js binds handler to form.reset() event, which alone causes 450 ms HTML rendering time for Chrome. 

With select2 this action has taken just 150-200 ms. Is there any workaround to avoid this rendering overhead in Choices?

**Comment by hope55** [comment]
Unfortunately I faced a more serious performance issue ever since. As choices binds it's click handlers to the root document, a single click on any HTML Element on a page (even on an empty div) will result in re-rendering all choices lists on the page causing the page to stop responding for seconds. 

There seems to be no response on this issue from the authors in 3 weeks, so I must start to find an alternative library. What a pity! Without these issues Choices would be a top pick. Any ideas on alternatives?

**Comment by hope55** [comment]
I started to debug, and found the bugs in the code in `choices.js` from line 1461, and 1512, and 1531, all the same.
Current: 
```
if (hasHighlightedItems) {
  this.unhighlightAll();
}
```
Fixed:
```
if (hasHighlightedItems.length > 0) {
  this.unhighlightAll();
}
```
Because `[]` expands to truthy, not falsy.
@jshjohnson: could you fix it please? This library is awesome anyways, thank you for your work!

**Comment by jshjohnson** [comment]
Thanks for the suggestions - I've just merged another fix which will hopefully solve the performance issue you are seeing. It will go out in the next release

**Comment by hope55** [comment]
Thank you, Josh! I'm looking forward to the next release!

**Comment by gruawati** [comment]
Hello.
I have a close problem with choices.js and form.reset.
I change values in a mysql database and i am using ajax for it. Everything is fine an works. But some values have to be values from a list, so a select is the correct way for me, but the select list ist very long, so i need a "search" in this too. I tried choices.js and it work very fine in a modal (select2 or selcetize works in a modal not).
But my problem is, if i press the button "add" or "change" to add or edit something, then i have to reset my form with form.reset, cause if not, then the values from before are still in the field. I know, it sounds complicated but i hope somebody can understand me. But if i reset my form, then the values of my choices select are empty and i can choose nothing. Can somebody help me how i can fix that? And by the "change value" i need the value, who is saved in database.
Maybe somebody have a little jsfiddle or something where i see how to use "setchoices" and that it not crash when i reset with form.reset().
Btw, i know my english is not the best, sorry if somebody can't understand me.

**Comment by mscart** [comment]
same problem as @gruawati  ...when i reset my form the choices elements are gone. the list is empty. any idea ?
