### ISSUE TITLE
How to get an instance later in another component?

### ISSUE THREAD

**Issue by kriss145** [jshjohnson/Choices#494]
How to get an instance later in another component?

1. I created a first time Select (like in the documentation). 
2. Now I would use an instance to change the values of this select in another component where I don't have a config from point one.

It's possible to do this on this plugin?

Thanks

**Comment by hope55** [comment]
This is not really a Choices related question, it is much more about how to share data between JS modules. There are several options to do this:
1. You can make it global. (window.myChoiceinstance = new Choices(...);) Then you can access it from anywhere. (considered not to be best practice as you pollute your global namespace with those variables)
2. You can create a simple new component (usually called provider or service), which is imported into all your components, ( i.e.: where you created the Choice instance, AND your "another component" where you would set the value of the Choices instance) and assign your Choices instance as a property to it in the first component, and access it from the second.
Hope this helps!

**Comment by jshjohnson** [comment]
Closing as @hope55 gave a good answer
