### ISSUE TITLE
`deepmerge` concatenates array options instead of replacing them.

### ISSUE THREAD

**Issue by jhou** [jshjohnson/Choices#495]
When the `userConfig` options are merged with the `DEFAULT_CONFIG` here: https://github.com/jshjohnson/Choices/blob/master/src/scripts/choices.js#L59

`deepmerge` concatenates the `searchFields` default array with the user-supplied one.  This makes it impossible to *not* search both `label` and `value` in the choice results.

see example here: https://jsfiddle.net/4tx7qzdo/
go to either of the searches and type 'z' or 't' or 'v' and see what you get.

I have a fix - I will submit a PR.  Just want to see if I can write some tests around it first.

**Comment by jhou** [comment]
Fixed in #496

**Comment by jhou** [comment]
by the way, would it be possible to get a release containing the 2PRs of mine which you merged recently?  Especially the `searchFields` fix, the project I'm working on could really use that.

**Comment by jhou** [comment]
(also, apologies for re-opening this issue, when it's actually fixed, i just am not sure how to properly initiate this side discussion) 🤷‍♂️

**Comment by jshjohnson** [comment]
This has now been released [4.1.4](https://github.com/jshjohnson/Choices/releases/tag/v4.1.4) :)
