### ISSUE TITLE
Documentation error

### ISSUE THREAD

**Issue by youradds** [jshjohnson/Choices#499]
It seems there is a bug with your docs: 

```
// or
const example = new Choices(document.getElementById('example'));

example.passedElement.addEventListener('addItem', function(event) {
  // do something creative here...
  console.log(event.detail.id);
  console.log(event.detail.value);
  console.log(event.detail.label);
  console.log(event.detail.customProperties);
  console.log(event.detail.groupValue);
}, false);
```

That doesn't work. After some debugging, I found it should be:

`example.passedElement.element.addEventListener('addItem', function(event) {`

**Comment by gkweb** [comment]
@youradds - If you find an error and know the fix - Create a PR

**Comment by youradds** [comment]
@gkweb  I don't know how to make a PR, nor do I have time to learn currently :) I just wanted to  make people aware so someone could update it (not an issue for me, as I know my way around the fix - but for someone else who may be getting annoyed at not being able to get it going)

**Comment by Spone** [comment]
I made a PR :)
