### ISSUE TITLE
setChoices() : populate choices without callback system of ajax()

### ISSUE THREAD

**Issue by chymz** [jshjohnson/Choices#5]
First, thanks for 'choices' option 

I made a function to do the same with ajax() but without callback.
Can you watch it ?

Here it is : https://github.com/chymz/Choices/commit/02a71448cab38364f5c0555675507ad6a945f80c

Feel free to close if you don't want it ;)

**Comment by jshjohnson** [comment]
This has now been implemented into version 1.0.3 (https://github.com/jshjohnson/Choices#setchoiceschoices-value-label)

Thanks!
