### ISSUE TITLE
IE11 - Scroll bar closes dropdown immediately on click if select is single-select with text input

### ISSUE THREAD

**Issue by markjoeljimenez** [jshjohnson/Choices#503]
If a user decides to click on the scroll bar to navigate through the list on IE11, the dropdown closes immediately.

This issue is happening on your demo site as well: https://joshuajohnson.co.uk/Choices/

**Comment by DarrenMack-OD** [comment]
I have the same issue on my site as well :( It is frustrating as most of my clients are corporate on IE11 :/

**Comment by markjoeljimenez** [comment]
As a temporary solution, we're simply hiding the scroll bar on IE.

```
.choices[data-type*='select-one'] .choices__list--dropdown .choices-list {
    -ms-overflow-style: none;
}
```

**Comment by DarrenMack-OD** [comment]
Thanks @markjoeljimenez We might give that a go ;)

**Comment by DarrenMack-OD** [comment]
@markjoeljimenez Weird, that CSS doesn't work for me :/
