### ISSUE TITLE
Dropdowns can not be placed in an overflow

### ISSUE THREAD

**Issue by bernesto** [jshjohnson/Choices#504]
Problem: When dropdowns are placed in an overflow hidden container, dropdown templates may be clipped by bottom of the parent container. 

Expected Behavior: Dropdown templates should breakout of parent containers and extend below to the extent of the browser window, or relocate above when not possible. 

Solution: Dropdown elements should be placed in the DOM before the closing 'body' tag and absolutely positioned at the origin element with a high z-index.

**Comment by jshjohnson** [comment]
This was a design design when creating Choices. Adding the logic for determining position adds complexity and increases the size of the module. If you are in this situation, I would look at removing the overflow hidden from containing element instead of breaking out of it.

**Comment by ssbb** [comment]
> This was a design decision when creating Choices. Adding the logic for determining position adds complexity and increases the size of the module. If you are in this situation, I would look at removing the overflow hidden from containing element instead of breaking out of it.

It's important for scrollable containers too. Imagine a form in a modal window. In 100% of cases you don't want the modal window to be higher than the screen height, so you add `overflow: auto` for example. In such cases it will cause issues with Choices.

Other libraries typically solve this issue with placing dropdown list somewhere directly in `<body>` for example.

**Comment by ssbb** [comment]
I ended up using floating-ui for positioning so it maps with @jshjohnson comment above really. It would be great to have an ability to disable built-in positioning at all (for example, something like `position: "manual"`).

```js
const ChoicesHook = {
  mounted() {
    this.selectEl = this.el.querySelector('select');

    this.choices = new Choices(this.selectEl, {
      addChoices: this.allowCreate(),
      removeItemButton: true,
      choices: this.options(),
      shouldSort: false,
      position: 'bottom',
      callbackOnInit: () => {
        this.choicesToggle = this.el.querySelector('.choices__inner');
        this.choicesDropdown = this.el.querySelector('.choices__list--dropdown');
      },
    });

    let cleanup;

    this.selectEl.addEventListener('showDropdown', () => {
      cleanup = autoUpdate(this.choicesToggle, this.choicesDropdown, this.autoPosition.bind(this));
    });

    this.selectEl.addEventListener('hideDropdown', () => {
      cleanup && cleanup();
    });
  },

  updatePosition() {
    computePosition(this.choicesToggle, this.choicesDropdown, {
      placement: 'bottom',
      middleware: [
        // Flip top/bottom position
        flip(),

        // Match toggle width
        size({
          apply({ rects, elements }) {
            Object.assign(elements.floating.style, {
              minWidth: `${rects.reference.width}px`,
            });
          },
        }),
      ],
      strategy: 'fixed',
    }).then(({ x, y }) => {
      Object.assign(this.choicesDropdown.style, {
        left: `${x}px`,
        top: `${y}px`,
        bottom: 'auto',
        position: 'fixed',
        width: 'auto',
      });
    });
  }
};
```
