### ISSUE TITLE
choices-multiple-remove-button - list 

### ISSUE THREAD

**Issue by olivads** [jshjohnson/Choices#505]
hi 
I use select multiple choices, id="choices-multiple-remove-button"
my prob: when I click into the input without write someting I have the list of option value
I want the list if I write something a letter by exemple but if I click into i don t want the list of option value

**Comment by jshjohnson** [comment]
Hi @olivads, 

I really don't understand what you mean. Please may you provide a js fiddle illustrating the problem please
