### ISSUE TITLE
Text input: populate choices with Ajax

### ISSUE THREAD

**Issue by Spone** [jshjohnson/Choices#509]
Hi there,

thanks for the very useful library!

I'm wondering if there could be a way to populate choices with the `ajax` method, it the context of a `text` input.

My use case is a "Tags" input, where I want the user to be able to reuse existing tags, as well as creating a new one on the fly.

I was able to use Choices with a `text` input, but in this case I can't auto-suggest tags based on an Ajax query.
I was also able to use Choices with a `select-multiple` input, but in this case, I can't add a new tag on the fly.

Does it make sense? Do you see a way of achieving that behavior?

Thanks

**Comment by kinopyo** [comment]
Seems like a similar question was asked before but not resolved: https://github.com/jshjohnson/Choices/issues/475.

I'm also curious of how to achieve this "Tags" use case - the ability to add new entry is baked in `text`, and "choices" is baked in `select-multiple`. 😕
