### ISSUE TITLE
Ajax: remove current values from suggestions (deduplicate)

### ISSUE THREAD

**Issue by Spone** [jshjohnson/Choices#510]
Hi,

I'm using `ajax` to populate the choices for my `select-multiple`. The ajax call returns the whole list of available choices.

If the input already has selected values, these values still appear in the choices list. Is there an easy way to deduplicate them?

I already use `duplicateItemsAllowed: false` to prevent them from being selected, but I'd like to hide them.

Thanks

**Comment by nlemsieh** [comment]
I think this can be done on the backend side, by passing the selected values to your ajax request `{exclude: choices.getValue(true)}`, and then exclude them from the search results.

**Comment by Spone** [comment]
Yes @nlemsieh that's what I ended up doing. I was wondering if there was a frontend-only way.
