### ISSUE TITLE
Import ES6 code without polyfills (again)

### ISSUE THREAD

**Issue by perifer** [jshjohnson/Choices#519]
https://github.com/jshjohnson/Choices/issues/480 brought great improvements to bundle size (thanks!).

To decrease it even further I would like to exclude polyfills as discussed in 
https://github.com/jshjohnson/Choices/issues/117 and https://github.com/jshjohnson/Choices/issues/144.

As I understand it the entry point for importing the ES6 code is 
https://github.com/jshjohnson/Choices/blob/master/src/scripts/choices.js. However that file includes `import './lib/polyfills';`.

Would it be an option to leave that out and create another file that imported `choices.js` and `lib/polyfills.js`? That file could then be the one that was transpiled, catering both for users that needs the pre-built files and users that would like to import just the source code.

**Comment by jshjohnson** [comment]
Hi @perifer 

I left the custom event polyfill as it's the only polyfill you can't use polyfill.io for: https://github.com/jshjohnson/Choices#browser-compatibility

It's also only 699 bytes gzipped

**Comment by perifer** [comment]
Oh, I missed that. Nice!

**Comment by perifer** [comment]
(Missed that you already har renoverar the others)

**Comment by stof** [comment]
I opened https://github.com/Financial-Times/polyfill-library/issues/151 to request the inclusion of the CustomEvent polyfill in their service.

**Comment by stof** [comment]
@jshjohnson The polyfill is actually available on their service. Add `CustomEvent` in the list of polyfills to load.
