### ISSUE TITLE
Get the value of the group

### ISSUE THREAD

**Issue by NetanelBasal** [jshjohnson/Choices#52]
There is a way to get the value of the group?
```js

    const example = new Choices(ele);

    example.setChoices([{
      label: 'Personal',
      choices: [
        {value: 'Child One', label: 'Child One'},
        {value: 'Child Two', label: 'Child Two'}
      ]
    },
      {
        label: 'Internet',
        choices: [
          {value: 'Child One', label: 'Child One'},
          {value: 'Child Two', label: 'Child Two'}
        ]
      }], 'value', 'label');
  }
```

So for example here when I click on item in the Personal group I need to know the group name.

**Comment by jshjohnson** [comment]
Hi @NetanelBasal,

Not currently but it would be simple to pass the group value to the callbackOnAddItem/callbackOnRemoveItem etc functions.

I'll look into this for you.

Thanks,

**Comment by NetanelBasal** [comment]
Thank you, This will be very helpfull.

**Comment by jshjohnson** [comment]
Hey @NetanelBasal,

As of version `2.3.0`, this is now possible. See: https://github.com/jshjohnson/Choices#callbackonadditem (third argument)

Thanks!

**Comment by NetanelBasal** [comment]
Thanks!!
