### ISSUE TITLE
unhighlightAll in Click handler causes click performance issue on large lists.

### ISSUE THREAD

**Issue by jchamb** [jshjohnson/Choices#522]
If working with a large chosen list (2000+ items), unhighlightAll is called for every click on the page when the select is inactive. It causes very noticeable click performance delays.

Didn't dig to far to see why it is called there, butIi didn't notice any issues with the select after i removed it form the click handler.

**Comment by jshjohnson** [comment]
@jchamb Could you provide a js fiddle please highlighting the problem please?

**Comment by jchamb** [comment]
I actually can't get it to reproduce in an ultra basic fiddle. Admin it's being used in is also using some pjax binding, maybe two things compounding. I took a look at the source and see you have a check wrapped around it in the source.

As I mentioned above I removed the
`&&this.unhighlightAll()`
 in the minified bundle and the problem went away.  That hack is good enough to take care of my issue so i'm gonna close this.

**Comment by martijnhartlief** [comment]
I was running into the same issue where I have over 9000 items.

![image](https://user-images.githubusercontent.com/12697043/57222740-f76f7380-7003-11e9-9792-8534fab4f3e3.png)

Changing an input that is not Choices triggers the slowdown, so i think the click handler listens to all input elements instead of the one it's bound to.

Like @jchamb suggested, removing &&this.unhighlightAll() from the minified version removes the slowdown.

**Comment by abarrak** [comment]
@jchamb I tried to reomve all `highlightAll()` and `unhighlightAll()` but the green box and highlight functionality still exists, and the slowness still occur.

**Comment by midzer** [comment]
@jchamb is talking about this line:

https://github.com/Choices-js/Choices/blob/f0ec43fa20b8fc1118e2a33a349220b78ccf9eb9/src/scripts/choices.ts#L1782

^This hack is working for me, too.

When Choices was unmaintained, I've created a fork https://github.com/midzer/Choices to improve performance for large lists by replacing slow fuse.js library with KMP search algorithm and few other improvements.

**Comment by mtriff** [comment]
@midzer I would certainly appreciate any PRs addressing performance. 

I don't think I want to remove Fuse.js outright, but having KMP as another option (and allow Fuse.js to [be removed via tree shaking](https://github.com/krisk/Fuse/pull/597)) would be a good approach.

I'm still familiarizing myself with the codebase. What's the side effect of removing `unhighlightAll`? We can discuss this in a PR.
