### ISSUE TITLE
Choices not defined

### ISSUE THREAD

**Issue by junaidp** [jshjohnson/Choices#523]
Hi 
I have just started using choices , but not abe to get a start .

I am using in my GWT application , using cdn 
Getting this error 

Also trying in codepen , if i can get some guidance what i am missing 
https://jsfiddle.net/junaidp/q62owxL8/

<img width="1304" alt="screen shot 2019-02-19 at 06 15 14" src="https://user-images.githubusercontent.com/747843/52991808-9b3a8180-340e-11e9-8dc2-fee7e5308b33.png">
<img width="956" alt="screen shot 2019-02-19 at 06 16 57" src="https://user-images.githubusercontent.com/747843/52991809-9bd31800-340e-11e9-9485-2245bd079603.png">

**Comment by jshjohnson** [comment]
@junaidp You aren't passing a select element in your codepen example

**Comment by junaidp** [comment]
thanks , now i am passing select element in codepen , its working , but still not in the project.

in my html i am adding a select element exactly as in the feedle above.
                          
In the screenshot of developer tools, we can see that choices cdn is there

<img width="1434" alt="screen shot 2019-02-21 at 06 27 26" src="https://user-images.githubusercontent.com/747843/53145865-462f7480-35a2-11e9-9726-f9afa104a3e1.png">

now when i run, first i am checking the element in alert( here is the screenshot) ...

<img width="766" alt="screen shot 2019-02-21 at 06 32 22" src="https://user-images.githubusercontent.com/747843/53145936-960e3b80-35a2-11e9-8db5-a46478ed1084.png">

but then on next line 

 var example = new Choices($doc.getElementById('cities'));

I get this error ..
<img width="1400" alt="screen shot 2019-02-21 at 06 34 09" src="https://user-images.githubusercontent.com/747843/53146008-dd94c780-35a2-11e9-9069-c6e132d81cee.png">

Now , choices are here as cdn , element is here , Not getting what i am missing here .

**Comment by junaidp** [comment]
fixed, issue was in GWT calling to javascript
