### ISSUE TITLE
When I fill third select chained in a row it returns me error. What it can be?

### ISSUE THREAD

**Issue by iievgen** [jshjohnson/Choices#524]
![image](https://user-images.githubusercontent.com/47789652/53032064-c5278e80-3476-11e9-96e6-3571f9b74fd9.png)
When I fill third select chained in a row it returns me error. What it can be?

**Comment by jshjohnson** [comment]
I really need more information to help you

**Comment by iievgen** [comment]
I have 3 selects: 1 select is filled by default and 2 will be filled by values when we choose from 1 one option. On choosing 1 opion from 2 select will be filled 3 select.
But now after chosing 1 one it fills second but on chosing one from second select it returns this error:
choices.min.js?c4f6:2 Uncaught TypeError: Cannot read property 'dispatch' of undefined
Are we need to reinit it for each of freshly filled selects? How?

**Comment by iievgen** [comment]
Now it is solved. There was mismatch with classes on my side. Sorry and thank you!
