### ISSUE TITLE
Problems in using Choices in an Angular 7 CLI project

### ISSUE THREAD

**Issue by Abhishek-Kanitkar** [jshjohnson/Choices#526]
Hi @jshjohnson ,

This is an awesome tool you have developed ! Thanks for that :)

But I am really not able to use it on IE 11 even with 6.0.1.

Can you or anyone please help me ? in this ?

You can try rendering it in IE 11 inside a Angular project.

I have attached screenshots of errors.

![ie-rendering](https://user-images.githubusercontent.com/9163540/53136617-90febb80-35a5-11e9-8c54-1c90003e1c12.png)
![ie-error](https://user-images.githubusercontent.com/9163540/53136618-90febb80-35a5-11e9-827a-8e767909393e.PNG)

**Comment by psmyrdek** [comment]
Could you show us a few snippets of using it within Angular app?

**Comment by Abhishek-Kanitkar** [comment]
> Could you show us a few snippets of using it within Angular app?

@psmyrdek I dont have the snippets as I overwrote my code for some other changes but here are high level steps

1. Install Choices as an npm module in your Angular CLI project
2. Add the minified .js & .css files for Choices in your angular.json file in styles & scripts properties under 'architect' key.
3. Then in your component, first you need to write import statement on the lines of
import * as Choices from '[node module name for Choices]';

And then instantiation and usage as per Choices guidelines.

Please let me know if you face any issues in this.
