### ISSUE TITLE
updating from 6.0.1 to 6.0.2 breaks ie11 support. es6 in public/scripts/choices.js

### ISSUE THREAD

**Issue by dementor5** [jshjohnson/Choices#529]
Many const, let and arrow function appeared after updating from 6.0.1 to 6.0.2 in public/scripts/choices.js and public/scripts/choices.min.js

https://github.com/jshjohnson/Choices/blob/4d1c3cd2aea5a8882fcadd21780d2233f7b9c54c/public/assets/scripts/choices.js#L4002-L4837

**Comment by thisconnect** [comment]
I have the same issue, `6.0.1` works for now. It seems this is the only relevant commit between the 2 versions https://github.com/jshjohnson/Choices/commit/879c97f64c8f2765fa1ca21ece3832c7d8426e57

**Comment by jshjohnson** [comment]
Fixed here: https://github.com/jshjohnson/Choices/releases/tag/v6.0.3

**Comment by thisconnect** [comment]
thnaks
