### ISSUE TITLE
Placeholder display on the search text input and not on the select 

### ISSUE THREAD

**Issue by ArielGueta** [jshjohnson/Choices#53]
When I am setting a placeholder, my expectation is to see the placeholder on the select element and not on the search input when clicking the select box. 

How can I set a placeholder for the users to see when there is no value selected?

My example plunker:
[plunker](https://plnkr.co/edit/ygiBJ6sLlUx4hsTVjVw2?p=preview)

Thanks. ( By the way awesome plugin )

**Comment by jshjohnson** [comment]
Hi @ArielGueta,

I think you're correct. I think there should perhaps be a `searchPlaceholder` config option as well as the normal placeholder. 

In the meantime, see this ticket for some info for setting a placeholder item: https://github.com/jshjohnson/Choices/issues/41

**Comment by kayue** [comment]
Is there any updates on this feature?

**Comment by jshjohnson** [comment]
This is being managed as a part of this feature: https://github.com/jshjohnson/Choices/issues/77
