### ISSUE TITLE
6.0.3 searchEnabled: false broke in multiselect focusing on choices__input--cloned on empty space click

### ISSUE THREAD

**Issue by dementor5** [jshjohnson/Choices#533]
reference to demonstration:
https://jsfiddle.net/pvvnxdementor5/9gmv72L1/17/

**Comment by jshjohnson** [comment]
They both work in your example?  Could you provide a clearer description please

**Comment by dementor5** [comment]
Just try to get a focus on search input by clicking anywhere except it.

**Comment by jshjohnson** [comment]
I can focus using my keyboard and my mouse?

**Comment by dementor5** [comment]
If i click by mouse on .choices__inner of first multeselect, (not a .choices__input--cloned), then i get automatic focus on .choices__input--cloned - i can just simple start write a word.
But if i click on .choices__inner of second multiselect, i can't start writing search request , becouse i haven't focus on search input.
