### ISSUE TITLE
Dependencies look wrong

### ISSUE THREAD

**Issue by stof** [jshjohnson/Choices#535]
The package.json lists a few dependencies of the library. But the `main` script seems to bundle these dependencies rather than importing them. This means that installing these dependencies through npm is totally useless. They are actually dev dependencies.

Btw, it would be great to provide built files actually importing these dependencies. This way, they would not get duplicated in the page if something else also use them (you could still provide a full bundle for ease of use for people not using a module bundler)

**Comment by jshjohnson** [comment]
Happy to review a PR for this 👍

**Comment by stof** [comment]
Which PR do you prefer ? A PR moving dependencies to dev dependencies, or a PR moving them out of the built file (with a full build for simplicity for people not using a bundler) ?

**Comment by stof** [comment]
@jshjohnson any answer for my question ?
