### ISSUE TITLE
Enabling to paste multiple comma separated values

### ISSUE THREAD

**Issue by rNianios** [jshjohnson/Choices#537]
Hi,
I am not sure if it's an issue or if it is supported and I just not able to find it. 

I am trying to paste a couple of comma separated values into an input box but they are being recognized as a single tag instead of multiple tags. 

Is it possible to be recognized as multiple values?

**Comment by Braintelligence** [comment]
I have the same problem 3 years later. I can't find anything about this in the documentation. You can disable pasting itself but I don't see a way to paste multiple legit options at once into the input field.

**Comment by chrisovato** [comment]
Any updates?

**Comment by fumagally** [comment]
I have the same problem to pasting values with comma separated into input
