### ISSUE TITLE
Error may be unecessary when elements is not found

### ISSUE THREAD

**Issue by leooon** [jshjohnson/Choices#538]
It would be nice to not have this error displayed as this could be expected. And also more in line to how other libraries deal with this cases. This makes sense for you guys? 

![image](https://user-images.githubusercontent.com/739772/53972753-28075f80-40de-11e9-9b22-bf41f2fcb273.png)

![image](https://user-images.githubusercontent.com/739772/53972777-33f32180-40de-11e9-93cf-0614c72ea0fa.png)

**Comment by jshjohnson** [comment]
There is a silent flag you can pass to silence those logs :)

**Comment by leooon** [comment]
You're right, I just notice it! (it's the first item in the documentation hehe)

**Comment by leooon** [comment]
@jshjohnson, I think this particular error is not considering the silent flag. Is this intended?

![image](https://user-images.githubusercontent.com/739772/54304922-ee829880-45a4-11e9-887d-17a2f24df0d3.png)
