### ISSUE TITLE
Pressing `enter` submits the form

### ISSUE THREAD

**Issue by rstacruz** [jshjohnson/Choices#54]
![image](https://cloud.githubusercontent.com/assets/74385/19431139/c7b5485c-9489-11e6-8508-35014d2ce737.png)

Contrary to what the hint text says, pressing `Enter` actually submits the form that the input is in.

Thanks for choices.js!

**Comment by jshjohnson** [comment]
Hi @rstacruz,

Is the input focussed when you press enter? 

Thank,
Josh

**Comment by rstacruz** [comment]
Yep!

**Comment by rstacruz** [comment]
Oh, to replicate:

```html
<input id="x" type="text">
```

```js
new Choices(document.getElementById('x'))
```

**Comment by jshjohnson** [comment]
That's strange, could you give me your browser details please? Thanks

**Comment by jshjohnson** [comment]
Could you also provide a JSbin example please if possible?

**Comment by jshjohnson** [comment]
Hey, any chance you could send me your browser details please?

Thanks

**Comment by ch33foong** [comment]
This is replicated on Chrome Version 54.0.2840.71. 
Make sure the text box inside a form tag.

**Comment by Fudoshiki** [comment]
Same issue Chrome 57

**Comment by jshjohnson** [comment]
Resolved in [PR82](https://github.com/jshjohnson/Choices/pull/82)
