### ISSUE TITLE
Unable to prevent showDropdown

### ISSUE THREAD

**Issue by powerbuoy** [jshjohnson/Choices#541]
I'm trying to prevent the dropdown in a multiple select from showing when the search input is focused and empty. I want the dropdown to show only when the users starts searching.

I've hooked into the `showDropdown` event and just as a first test I tried to `event.preventDefault()` to see if I could stop it from showing up, sadly that does not work. I've also tried just returning false from my callback but that doesn't work either.

It seems the event _is_ cancelable (its `cancelable` property is `true` and trying `preventDefault()` does not produce an error) but like I said `preventDefault()` does nothing.

I also tried setting `renderChoiceLimit` to 0 while keeping `searchResultLimit` at 4 which clearly would be the most straight forward solution - but that too fails. It seems that when `renderChoiceLimit` is 0 it is ignored.

How can I solve this?

**Comment by jshjohnson** [comment]
Please may you provide a jsfiddle highlighting the issue

**Comment by powerbuoy** [comment]
Here's a fiddle that highlights this, and my other two issues in one:

https://jsfiddle.net/n7yvrdzL/5/

**Comment by skix123** [comment]
I face the same issue, looks like there should be `-1` instead of `0`: https://github.com/jshjohnson/Choices/blob/master/src/scripts/choices.js#L689
