### ISSUE TITLE
Search by letter bug

### ISSUE THREAD

**Issue by reinisg** [jshjohnson/Choices#542]
I have created simple dropdown where can search the value.
Here is an example: https://codepen.io/reinis/pen/KEvGZJ
If I enter the letter 'E', it will find EUR, but if I will write 'EU', the result will be EUR, RUB, USD. And this bug is also on other situations with searching by letters. Is there any solution for this issue?

**Comment by jshjohnson** [comment]
Choices uses a fuzzy searching library so it will not look for exact matches. You are seeing USD and RUB because they satisfy half of your search (i.e. "U")

**Comment by reinisg** [comment]
Okay, thanks for fast reply.
