### ISSUE TITLE
data-custom-properties not picked up if option is inside an optgroup

### ISSUE THREAD

**Issue by powerbuoy** [jshjohnson/Choices#543]
I've been using `<option data-custom-properties="somevalue">` on my multiple select to store some additional data I need. This has been working fine until today when I wrapped my `<option>`s in an `<optgroup>`. Suddenly all my `customProperties` are `null`. This looks like a bug to me?

**Comment by jshjohnson** [comment]
Please may you provide a jsfiddle highlighting the issue

**Comment by powerbuoy** [comment]
Here's a fiddle that highlights this, and my other two issues in one:

https://jsfiddle.net/n7yvrdzL/5/

**Comment by alphonse927** [comment]
Hi, I'm also facing this issue, there's any more info about this?

**Comment by Zilus** [comment]
this issue persist on 9.0.1

**Comment by Black-Dragon-Spirit** [comment]
Dirty fix for this one is find the var addGroupChoices = function (choice) { ... change the customPropeties: choice.customProperties in to customProperties: choice.getAttribute('data-custom-properties'),
