### ISSUE TITLE
Show optgroup during search

### ISSUE THREAD

**Issue by powerbuoy** [jshjohnson/Choices#544]
I'm using `<optgroup>` to group choices and it works fine. When the user starts searching, though, the optgroups aren't rendered. This is a huge problem for me as several choices have the same name but are under a different group. Without the group names it's impossible for the user to know what he's selecting.

Is there any way to show the optgroups even during search? Any chance you could add this functionality otherwise?

The order of search results would need to change if this is enabled I guess because you only want to print the group names once. The order of the groups should probably also be configurable. In my case I would like to retain the order of the groups regardless of where the most relevant search result is.

**Comment by jshjohnson** [comment]
Please may you provide a jsfiddle highlighting the issue

**Comment by powerbuoy** [comment]
Here's a fiddle that highlights this, and my other two issues in one:

https://jsfiddle.net/n7yvrdzL/5/

**Comment by alanhamlett** [comment]
Please re-open this issue.

**Comment by leereichardt** [comment]
Can this issue be re-opened?

**Comment by Pezhvak** [comment]
why haven't this been implemented?

**Comment by dayglorious** [comment]
Is there a fix to this issue, or a workaround for it?

**Comment by icyz** [comment]
any news about this?

**Comment by PatrickH89** [comment]
any news about this? Still not working
