### ISSUE TITLE
Calling setChoices with an empty array should clear the choices

### ISSUE THREAD

**Issue by Spone** [jshjohnson/Choices#545]
Hi there,

I'm implementing something similar to [this](https://github.com/jshjohnson/Choices/issues/162#issue-229401941) (with Algolia as a backend API). The choices aren't cleared when I select a choice.

The relevant part is:

`choices.setChoices([], 'id', 'text', true);`

I had to reach for the internal method `_clearChoices` to make it work:

`choices._clearChoices();`

I think calling `setChoices` with an empty array should clear the params.

Alternatively, you could make the `_clearChoices` method public and document its use.

What do you think? Am I missing something here?

**Comment by jshjohnson** [comment]
I agree on both points tbh. Setting an empty array should clear choices and clearChoices should be public

**Comment by Spone** [comment]
@jshjohnson I gave it a shot in the linked PR :)

**Comment by Spone** [comment]
This has been merged.
