### ISSUE TITLE
Typescript type info 'choices' missing

### ISSUE THREAD

**Issue by Moeriki** [jshjohnson/Choices#551]
To get up and running faster it'd be convenient to have type info on the `choices` option. Right now it is set to `any[]`.

I have written this for myself, based on the examples I saw in the docs. Not sure how correct it is.

```ts
export interface ChoiceItem {
  customProperties?: { [key: string]: string };
  disabled?: boolean;
  label: string;
  selected?: boolean;
  value: string;
}

export interface ChoiceGroup {
  choices?: ChoiceItem[];
  id?: string;
  label: string;
}

export type Choice = ChoiceItem | ChoiceGroup;
```

Can anyone confirm the validity?

Would a PR be accepted adding this to the project?

**Comment by jshjohnson** [comment]
Sure :) sounds good
