### ISSUE TITLE
Add Items without needing to hit Enter?

### ISSUE THREAD

**Issue by atomgiant** [jshjohnson/Choices#552]
I'm using Choices for allowing entering multiple "tags" for an item.  Choices currently requires a user to "Hit Enter to add the item".

This is a constant source of confusion for my users.  The user starts typing out the tag which looks like this:

![choices_typing](https://user-images.githubusercontent.com/21659/54761680-eb049800-4bc8-11e9-966c-d8b7a0897799.png)

Many don't read the "Press Enter" text and change focus out of that input which makes it appear as if their entry worked as you can see here:

![choices_unfocused](https://user-images.githubusercontent.com/21659/54761816-33bc5100-4bc9-11e9-9981-7c5a0ab7d38e.png)

For comparison, here is what the tag looks like after Enter is pressed:

![choices_after_enter](https://user-images.githubusercontent.com/21659/54761846-46cf2100-4bc9-11e9-982c-2d7e9ca2d607.png)

Is there a way to have the tag be added without clicking Enter?  For example, maybe on click, or on blur or on form submit?  I think it might also make sense to clear that input if they didn't hit enter and left the field since it is misleading to show that text that is not going to be submitted.

This might also help with Issue #549.

Thanks!

**Comment by gwidonw** [comment]
@atomgiant Hi Tom, did you managed to find any workaround for this?

**Comment by gwidonw** [comment]
Just if someone needs it. In my use case, I needed to make space and `,` key to work the same as Enter. The only way that I found to get user input was to use `addItemFilterFn` callback function and call `choicesInstance.setValue` from inside. Far from perfect but quite simple and it works. The working code example below:

https://jsfiddle.net/gwidonw/5u47kzsj/1/

**Comment by atomgiant** [comment]
That's awesome @gwidonw.  Thanks so much for sharing your example. 

I haven't found a workaround to this yet but your example should help a lot in tweaking this behavior.  

I'll report back with any progress once I have a chance to look at this a bit more in depth.

**Comment by atomgiant** [comment]
@gwidonw I tweaked your jsfiddle.  Here is my version https://jsfiddle.net/j0fhb3sc/3/

I added the following changes:

1. Hide the dropdown after you add the tags.  Otherwise it was still showing with such as `foo,`
2. Set the tag value on blur

Thanks for your help with this.

**Comment by besimhu** [comment]
Just wanted to say thanks for the code snippets. Came in handy for me on mobile.
