### ISSUE TITLE
Demo broken in IE11

### ISSUE THREAD

**Issue by Flowgram** [jshjohnson/Choices#553]
Hi there, 

It looks like Choices on the demo page is broken in IE11 even though the polyfills are there.

There's an arrow function on page, but even when that's removed I'm getting the error:

`Object doesn't support property or method 'includes'`
`choices.min.js (2,21791)`

The code it's referencing is:

`["auto","always"].includes(this.config.renderSelectedChoices)`

Many thanks for any help with this.

**Comment by Flowgram** [comment]
Ok, I've fixed it with an amended polyfill list:

`<script src="https://cdn.polyfill.io/v2/polyfill.js?features=es5,fetch,Element.prototype.classList,requestAnimationFrame,Node.insertBefore,Node.firstChild,Object.assign,Array.prototype.includes,String.prototype.includes,Array.from,Array.prototype.find"></script>`

**Comment by jshjohnson** [comment]
This has now been resolved 👍
