### ISSUE TITLE
this is undefined

### ISSUE THREAD

**Issue by Eventusrus** [jshjohnson/Choices#554]
Hello. When I use "this" in callbackOnInit, this is undefined. 
I used webpack with babel. Code after compile:

```
var _this = this;

$(document).ready(function () {
  var choices = new Choices('select', {
    searchEnabled: false,
    itemSelectText: '',
    callbackOnInit: console.log(_this)
  });
});
```

**Comment by jshjohnson** [comment]
You need to provide `callbackOnInit` with a function, you are providing it the result of a console log which is always undefined
