### ISSUE TITLE
choices.js inside of vuetify v-dialog not working

### ISSUE THREAD

**Issue by mutex12** [jshjohnson/Choices#556]
Hi folks,

I'm trying to track down the interaction between the v-dialog and choices.js that prevents the choices.js (6.0.3) dropdown from appearing.

Code placed anywhere else is ok.

I suspect v-dialog bind/unbind addEventListener focusin or z-index handling causing issues.

Snippet:

```html
<template lang="pug">
    v-dialog(
        v-model="visible"
        scrollable
        full-width
        persistent
        :no-click-animation="true"
        :transition="false"
        )
        v-card
            v-card-text
                select(ref="choices")
                    option(selected disabled) This is a placeholder
                    option(value="1") Option 1
                    option(value="2") Option 2
</template>

<script>
import Choices from 'choices.js'
export default {
  data: function () {
        return {
            visible: false
        };
    },
    mounted: function () {
        var element = this.$refs['choices']
        // eslint-disable-next-line no-unused-vars
        var choices = new Choices(element, {})

        element.addEventListener('input', e => {
            this.$emit('input', e.target.value)
        });
    }
};
</script>
```

**Comment by mutex12** [comment]
Ok, the issue is that choices.js adds event listeners on the "document" to catch click and other events, not the element wrapper it has just created.

Vue v-dialog like most dialogs stops propagation of the click event to elements underneath, hence click is never delivered.

Is there a modified choices.js out there to add the event listeners to just the wrapper?

**Comment by mutex12** [comment]
```
_addEventListeners() {
    document.addEventListener('keyup', this._onKeyUp);
    document.addEventListener('keydown', this._onKeyDown);
    document.addEventListener('click', this._onClick);
    document.addEventListener('touchmove', this._onTouchMove);
    document.addEventListener('touchend', this._onTouchEnd);
    document.addEventListener('mousedown', this._onMouseDown);
    document.addEventListener('mouseover', this._onMouseOver); 
```
document.addEventListener calls should really be on the containerOuter instead, ie.

`this.containerOuter.element.addEventListener('click', this._onClick);
`
Same work is needed in the _removeEventListeners function.

**Comment by leereichardt** [comment]
I think I've come across this issue is a large scale project I'm working on, but I can't see what's stopping the propagation.

Is there a modification out there to apply the event listener @mutex12 says? Or have you discovered a solution yet?

**Comment by oliveiracdz** [comment]
Hi there!

Did you found any workaround @mutex12?
https://github.com/vuetifyjs/vuetify/blob/d1755df2c6627cbb57e518409e0366c3c8ccdbb2/packages/vuetify/src/components/VDialog/VDialog.ts#L247
