### ISSUE TITLE
If I pass a NodeList as elements, I get an error "Passed element was of an invalid type"

### ISSUE THREAD

**Issue by SilencerWeb** [jshjohnson/Choices#559]
If I pass a NodeList of selects as elements, I get an error "Passed element was of an invalid type". But if I pass a selector instead of the NodeList, it works fine.

The version is the latest one, 7.0.0.

**Comment by AlbertRAR** [comment]
Same issue with 7.0 (didn't test with older versions)

**Comment by AlbertRAR** [comment]
@SilencerWeb since we deal with NodeList, after initializing we should iterate over instances:
`const selects = new Choices(nodeList, options);
selects.forEach(...)
`

**Comment by jshjohnson** [comment]
This should really work out the box but a quick fix would be to pass your node list to `Array.from` first: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from

**Comment by AlbertRAR** [comment]
@jshjohnson this variant doesn't work as well.

**Comment by GoldenMaximo** [comment]
I came across this issue as well.

I tried:

 `const selects = document.querySelectorAll('.responsible-user');`

Then:

 `const selects = [...document.querySelectorAll('.responsible-user')];`

But what really worked was passing just the selector alone:

`const choice = new Choices('.responsible-user', options);`

**Comment by jshjohnson** [comment]
Closing as the ability to pass multiple elements to one instance has been removed as of version 8.x
