### ISSUE TITLE
Consider not minifying

### ISSUE THREAD

**Issue by rstacruz** [jshjohnson/Choices#56]
...or leaving `choices.js` as the `"main"` entrypoint, instead of `choices.min.js`.

This lets others debug properly :)

**Comment by jshjohnson** [comment]
Hmm, I think the general consensus is to have the minified version as the entry point as that allows somebody to easily include the library directly into their HTML from their `node_modules` folder. This means they do not need to have a build system to minify it etc.

**Comment by rstacruz** [comment]
Not always, I think... here are a few that don't:

- React https://unpkg.com/react@15.3.2/package.json
- jQuery https://unpkg.com/jquery@latest/package.json
- Lodash https://unpkg.com/lodash@4.16.4/package.json

That doesn't mean they don't provide a minified version though :)
