### ISSUE TITLE
How to stylize?

### ISSUE THREAD

**Issue by SilencerWeb** [jshjohnson/Choices#560]
Is there an option that I can pass so the select would be always open and I could stylize it?

**Comment by AlbertRAR** [comment]
Yes, it is [showDropdown()](https://github.com/jshjohnson/Choices#showdropdown-1) method.

**Comment by dementor5** [comment]
new Choices(`.choice`, {
  callbackOnInit() {
    const passedEl = this.passedElement.element;
    passedEl.addEventListener(`hideDropdown`, () => this.showDropdown());
    this.showDropdown();
});

**Comment by SilencerWeb** [comment]
@AlbertRAR, it isn't an option, but still thanks :)

I worked with [react-select](https://github.com/JedWatson/react-select) and there is such option as `isOpen`, which helps in this case a lot.
