### ISSUE TITLE
Version 7? What was the breaking change? Requesting CHANGELOG.md.

### ISSUE THREAD

**Issue by travist** [jshjohnson/Choices#564]
I see you have created a new version 7.x, which is fine, but I don't see anywhere I can look to know what was breaking about this change. This library should have a CHANGELOG.md file within the repo so that people like myself can see what was breaking so we can update our dependent libraries to support the new versions with confidence.

**Comment by jshjohnson** [comment]
Hi @travist - I use Github releases as a change log: https://github.com/jshjohnson/Choices/releases 

I'll make the last release description more explicit though 👍

**Comment by travist** [comment]
Perfect thanks!
