### ISSUE TITLE
How to prevent hide dropdown when select option?

### ISSUE THREAD

**Issue by betodasilva** [jshjohnson/Choices#565]
Hi

I'm creating a dropdown that has checkbox inside each option, but I can't figure out how to prevent the dropdown to close automatically after click on it.

Is there a way to do that?

Thanks in advance.

**Comment by dementor5** [comment]
new Choices(`.choice`, {renderSelectedChoices: `always`});

**Comment by shotaMik** [comment]
Hi, 

Is it possible to prevent the dropdown to close automatically for single option selects? as I see renderSelectedChoices only work with multi-select options.

Thanks
