### ISSUE TITLE
Is there a good way to add an 'onchange' event listener to the input field?

### ISSUE THREAD

**Issue by Colin-Moran** [jshjohnson/Choices#569]
I have some logic I need to handle every time the input value changes in the textbox. Right now I'm kind of working around it by using the 'search' event but that doesn't fire when the input value is empty.

Is there a good way to go about adding an onchange event listener to the text input?

**Comment by dementor5** [comment]
The first that came to my mind: 
```
new Choices(`select`, {
  callbackOnInit() {
    const searchField = tThe first that came to my mindhis.input.element;
    searchField.addEventListener(`input`, () => console.log(searchField.value));
  },
});
```

**Comment by Colin-Moran** [comment]
That was exactly what I needed. I didn't realize that I could access the element that way! Thank you!
