### ISSUE TITLE
In date of the item template there is no "disabled" flag

### ISSUE THREAD

**Issue by dementor5** [jshjohnson/Choices#576]
In data there is no flag of "disabled". These lines never will work:
https://github.com/jshjohnson/Choices/blob/7540d39f95a6f8a1f45f036ae40d03954aaa342f/src/scripts/templates.js#L60
https://github.com/jshjohnson/Choices/blob/7540d39f95a6f8a1f45f036ae40d03954aaa342f/src/scripts/templates.js#L71
https://github.com/jshjohnson/Choices/blob/7540d39f95a6f8a1f45f036ae40d03954aaa342f/src/scripts/templates.js#L84
https://github.com/jshjohnson/Choices/blob/7540d39f95a6f8a1f45f036ae40d03954aaa342f/src/scripts/templates.js#L106

**Comment by jshjohnson** [comment]
This is not true - If you set the disabled property true to the original input, this flag will be set to true. Alternatively if you call the [`disable`](https://github.com/jshjohnson/Choices#disable) command, it will be set to true.

**Comment by dementor5** [comment]
Template item - by default use a item class: "item: 'choices__item" and may be with remove button or without.
Look at the screenshot or check it self in dev tools on you demo site:
https://joshuajohnson.co.uk/Choices/
![hasNotAriaDisabled](https://user-images.githubusercontent.com/22612354/56435219-5af96180-62e0-11e9-9828-61e1fde87388.png)

On the screenshot disabled dropdown and it has not aria-disabled="true" tags on selected items.

I think it is a bug.
