### ISSUE TITLE
IE - incompatibility with new CustomEvent

### ISSUE THREAD

**Issue by AlexeyDavyd** [jshjohnson/Choices#578]
Can you please add native support of CustomEvent functions for IE, without using approach with polyfills?

**Comment by jshjohnson** [comment]
This was a conscious decision as not all consumers of this library need to support old versions of IE

**Comment by aarongerig** [comment]
@jshjohnson In order to support IE 9/10/11 one can use following syntax for custom events, no polyfills needed:

```js
var event = document.createEvent('CustomEvent');
event.initCustomEvent(...);
```
See https://caniuse.com/#search=CustomEvent
If you're interested, let me know and I'll prepare a pull request.

**Comment by aarongerig** [comment]
@jshjohnson WDYT?
