### ISSUE TITLE
CSS uses too much nesting sometimes

### ISSUE THREAD

**Issue by rstacruz** [jshjohnson/Choices#58]
For instance:

```css
.choices__group .choices__heading {
```

...when you can just use `.choices__heading`. I typically restyle Choices.js to fit the project I'm working on, and using less-specific CSS selectors would help a lot.

**Comment by rstacruz** [comment]
This is particularly problematic as well:

```css
.choices__list--dropdown .choices__item--selectable {
```

Would that be alright to be expressed as just `.choices__item--selectable`?

**Comment by jshjohnson** [comment]
Hey! 

Would you mind submitting a pull request for this? 

Thanks :)

**Comment by rstacruz** [comment]
Sure, though I'm not too familiar with the css styling here though so I
don't know if I can cover all cases :)

**Comment by jshjohnson** [comment]
As of version `2.3.0`, `choices__heading` is no longer one level deep in the CSS. The dropdown example you sent is necessary unfortunately.

Thanks.
