### ISSUE TITLE
write instead of click

### ISSUE THREAD

**Issue by olivads** [jshjohnson/Choices#581]
my website
 https://www.yalokaz.fr , choose a town and I use choices to select a city

My problem: when you click in input select, city appear;
and I want when I write in input select, city appear and when i click in input select, city don't appear (empty)

How I can do.

**Comment by nasatome** [comment]
Saludos!, encontraste la solucion al problema?....
tengo el mismo problema y observe que me pasa cuando el "Selecto Choices" esta dentro de un slider vertical...


https://swiperjs.com/demos/#vertical_slider
