### ISSUE TITLE
3 issues: disable maxItemText / hide placeholder / style placeholder

### ISSUE THREAD

**Issue by sfnprg** [jshjohnson/Choices#582]
Hello, I'm trying to implement this in my project. I like the multiple choice style so I changed my select element to "multiple" but need to limit to 1 item.

1. how to disable _maxItemText_ "block"? If I set to null / false, it gets interpreted as text. If as empty value ("") it still displays the box
2. how to hide placeholder if at least one item is selected? My form is short in width so depending on option selected sometimes shows the placeholder and some other not which doesn't look good
3. how to style placeholder? I tried but seems if doesn't work 
`.choices input::-webkit-input-placeholder, .choices input::-moz-placeholder, .choices input:-ms-input-placeholder, .choices input::placeholder, .choices input:-moz-placeholder, 
  .choices select::-webkit-input-placeholder, .choices select::-moz-placeholder, .choices select:-ms-input-placeholder, .choices select::placeholder, .choices select:-moz-placeholder {
    color: white;
    border: 1px solid orange;
  }
`

Any suggestions?
Thanks

**Comment by nuno360** [comment]
Trying to get the same result of Maxitems of Selectize.js, I would like to disable the maxItemText and noChoicesText. Any suggestions?

**Comment by eballeste** [comment]
This should be reopened, I have this exact use case and currently doing some hacky things to get the script to behave this way.
