### ISSUE TITLE
IE custom-event-polyfill

### ISSUE THREAD

**Issue by Carboner** [jshjohnson/Choices#585]
Sadly - I need to support IE 11 in my app. After bumping Choices version from 6.0.3 to 7.0.0 it became unusable on IE 11. 
The problem seems to be with customEvent, I used custom-event-polyfill to fix it in my app, but maybe some similar polyfill should be part of Choices.

**Comment by jshjohnson** [comment]
This was a conscious decision, see here: https://github.com/jshjohnson/Choices/pull/536
