### ISSUE TITLE
Is there a easy way to just set height/width ?

### ISSUE THREAD

**Issue by vegarringdal** [jshjohnson/Choices#59]
Is there a easy way to just set height/width ?
Or get it to follow the select you add it too?
Or do you have a bootstrap theme so it really looks like it belongs with the rest of the form elements?

Thx, looks really cool, love its vanilla js

**Comment by jshjohnson** [comment]
Hey @vegarringdal,

You can set the width and height of the element via the CSS:

```css
.choices__inner {
  width: 100px;
  height: 40px;
}
```

There isn't a Bootstrap theme - I'm open to somebody creating one though via a pull request (I personally don't use Bootstrap).

Thanks,
Josh

**Comment by vegarringdal** [comment]
thx, Ill try that

**Comment by vegarringdal** [comment]
tried this, didnt help much unless I go a do edits to all classes
Could have been useful if we could get it to follow the height/width of element we attach it to, if thats possible, but that might be more work then Im aware of.
Then again dropdowns can be useful to have wider in some cases 😄
