### ISSUE TITLE
IE11 breaks due to new CustomEvent()

### ISSUE THREAD

**Issue by MaffooBristol** [jshjohnson/Choices#590]
This is on version 7.0.0. Results in `SCRIPT445: Object doesn't support this action`

**Comment by jshjohnson** [comment]
Please look at previously closed issues before opening new ones. This has been answered numerous times: see #585, #536,  #578

**Comment by MaffooBristol** [comment]
My bad, I'd only searched open issues.

**Comment by jshjohnson** [comment]
No worries 👍
