### ISSUE TITLE
Uncaught TypeError: Cannot create property 'keyCode' on boolean 'false' at e.value (choices.min.js:2) at e.value (choices.min.js:2)

### ISSUE THREAD

**Issue by deivoff** [jshjohnson/Choices#595]
Hey, a have a some error when I click on select. I use typescript.

code:
`import Input from '../input';`
`import Choices from 'choices.js';`

`export default class InputSelect extends Input<HTMLSelectElement> {`
`    constructor(element: HTMLSelectElement) {`
`        super(element);`
`        const choises = new Choices(element);`
`    }`
`}`

error:
`Uncaught TypeError: Cannot create property 'keyCode' on boolean 'false'
    at e.value (choices.min.js:2)
    at e.value (choices.min.js:2)`

**Comment by mirkosaugo** [comment]
My problem is similar, i've this one:

`Uncaught TypeError: Cannot set property 'keyCode' of undefined`

Please consider my fix @jshjohnson into `_handleChoiceAction` function:

Change this line: `choice.keyCode = passedKeyCode;` to if(passedKeyCode!== null && passedKeyCode!= undefined ) choice.keyCode = passedKeyCode;

**Comment by vianna274** [comment]
any update about this issue?

**Comment by davep3rrett** [comment]
I'm experiencing the same issue - any update?

**Comment by tinovyatkin** [comment]
Fixed by #697, will lands in 8.0 release.
