### ISSUE TITLE
Set and get selected values (on select elements)

### ISSUE THREAD

**Issue by chymz** [jshjohnson/Choices#6]
I need to set and get selected element, like we do on select elements, only by send/return the values of selected choice(s). 
(Like we do with jQuery : `$('select').val(value);`)

Today, if i use setValue() function, I need to pass an object like `{value: 'one', label: 'Label One'}` right ? 
If so, i'have some issues with it : https://embed.plnkr.co/t48jwB4R7TunhXwcsr5z/

I've done an attempt to demonstrate clearly what i need : https://github.com/chymz/Choices/commit/5c8d91d55d590f67795c06cf4eb256c52c69d00b

If you need a PR, ask me.

Thanks for you time !

(And sorry for spamming issues :p)

**Comment by jshjohnson** [comment]
I have implemented a variation of the example you provided (thanks!) in the latest version (1.0.3). There are technically two ways of achieving what you're looking for: 

**Via [`setChoices`](https://github.com/jshjohnson/Choices#setchoiceschoices-value-label):**

```js
const example = new Choices('#choices-16', {
example.setChoices([
    {value: 'One', label: 'Label One', disabled: true},
    {value: 'Two', label: 'Label Two'},
    {value: 'Three', label: 'Label Three', selected: true},
], 'value', 'label');
```

**Via [`setValueByChoice`](https://github.com/jshjohnson/Choices#setvaluebychoicevalue)**

```js
const example = new Choices('#choices-16', {
    choices: [
        {value: 'One', label: 'Label One'},
        {value: 'Two', label: 'Label Two'},
        {value: 'Three', label: 'Label Three'},
    ],
});

example.setValueByChoice('Two');
```

Thanks.
