### ISSUE TITLE
Firefox sometimes stucks on AJAX

### ISSUE THREAD

**Issue by Gruven** [jshjohnson/Choices#604]
### What's wrong
Firefox sometimes stucks on AJAX method call. By "sometimes" I mean that most times it stucks, but sometimes it doesn't. On Chrome it's working fine.
Example:
```
const uri = './sample-url/';
const choices = new Choices(select);
choices.ajax((callback) => {
      axios.get(uri),
      })
        .then(({ data: { items } }) => {
          callback(items, 'value', 'label');
        });
    });
```
Choices successfully initializes, I see it on the page, but it says "Loading..." forever. Console says:
```
TypeError: placeholderItem is null
```
And refers to 2623 line of choices.js:
```
placeholderItem.innerHTML = this._placeholderValue || '';
```

### Environment
Ubuntu 19.04 x64
Firefox 67.0.4
Chrome 75.0.3770.100
Choices 7.0.0

**Comment by Gruven** [comment]
Inserting setTimeout for callback is a "workaround"

**Comment by BlaM** [comment]
Same issue appears in Chrome under Windows, so this seems to be mostly unrelated to environment.

As suggested by @Gruven this seems to be a timing related issue. Best guess without spending too much time with debugging: "AJAX complete" tries to work with the DOM structure that has not yet fully been created if results come back too fast.

**Comment by jshjohnson** [comment]
Closing as `ajax` has been removed as of version 8.x
