### ISSUE TITLE
utils::calcWidthOfInput() relies on nonstandard behavior of window.getComputedStyle()

### ISSUE THREAD

**Issue by aiwebb** [jshjohnson/Choices#607]
The issue is in [`src/scripts/lib/utils.js:calcWidthOfInput()`](https://github.com/jshjohnson/Choices/blob/879c97f64c8f2765fa1ca21ece3832c7d8426e57/src/scripts/lib/utils.js#L134):

```js
const inputStyle = window.getComputedStyle(input);

if (inputStyle) {
  testEl.style.fontSize = inputStyle.fontSize;
  testEl.style.fontFamily = inputStyle.fontFamily;
  testEl.style.fontWeight = inputStyle.fontWeight;
  testEl.style.fontStyle = inputStyle.fontStyle;
  testEl.style.letterSpacing = inputStyle.letterSpacing;
  testEl.style.textTransform = inputStyle.textTransform;
  testEl.style.padding = inputStyle.padding;                    // <---------
}
```

The spec for `window.getComputedStyle()` stipulates that [shorthand properties like `padding` should be empty in the return object](https://drafts.csswg.org/cssom/#dom-cssstyledeclaration-getpropertyvalue).

Firefox adheres to spec on this, so `inputStyle.padding` is always `""`. This results in input padding not being accounted for in Firefox.

Chrome departs from spec in favor of usability, so `inputStyle.padding` reflects the actual padding settings of the element.

The solution is to change this to copy `paddingLeft` and `paddingRight` explicitly.

**Comment by jshjohnson** [comment]
Closing as this util has been removed as of version 8.x
