### ISSUE TITLE
register as a bower module

### ISSUE THREAD

**Issue by herbertpimentel** [jshjohnson/Choices#61]
Will be very appreciated if you publish this also as a bower module.

**Comment by jshjohnson** [comment]
Hey @herbertpimentel,

There was a merged pull request a while ago to do this: https://github.com/jshjohnson/Choices/pull/38

If you have any issues installing with Bower, let me know.

Thanks

**Comment by herbertpimentel** [comment]
@jshjohnson I can´t find your pack at bower repo

```sh
$ bower search choices

Search results:

    dindinet-cookiechoices https://github.com/dindinet/cc.git
```

I have also tryed at https://bower.io/search/


I am facing some problems to import it using requirejs. So could you provide some example about how should I proceed ?


```javascript

define(function(require){
  var choices = require('libs/choices.min');

  // it is undefined 
  console.log(choices); 
});

```

**Comment by jshjohnson** [comment]
Hey, could it try it again now? I've just published it - apologies I don't actually use Bower!

**Comment by herbertpimentel** [comment]
@jshjohnson the bower module now is  fine, but I am facing problems to import choices using require.js

I am also facing some problems to import it using requirejs. So could you provide some example about how should I proceed ?

**Comment by jshjohnson** [comment]
Hi @herbertpimentel,

This should work for you: 

```
requirejs.config({
  baseUrl: '/',
  paths: {
    choices: 'bower_components/choices.js'
  }
});

requirejs( ['choices'], function(Choices) { 
 var example = new Choices();
});
```

**Comment by herbertpimentel** [comment]
@jshjohnson I have created a sample project to show how I am trying to use choices with requirejs following your instructions above

https://github.com/herbertpimentel/choicesjs_test

You just need run:

1. Install bower globally using npm
```sh
> npm install -g bower 
```
2. Install the bower dependences 
```sh
>bower install 
``` 

As I hove you will see choices is successful loaded but I receive a message `TypeError: Choices is not a constructor...` when I try to use it.
