### ISSUE TITLE
Can't select an option when used in combination with Fullpage.js

### ISSUE THREAD

**Issue by KeironLowe** [jshjohnson/Choices#618]
So it seems when Fullpage.js is being used on the page, you can't select a option in the dropdown. The only way I could select a value is by right clicking on it.

I've tracked the issue down to a pointerdown event listener attached by the scrolloverflow.js extension for Fullpage.js. I'm not sure if this is an issue with Choices, or Fullpage.js or both, let me know if I need to open an issue there instead.

**Comment by jshjohnson** [comment]
I don't even know what Fullpage.js is so I'm not sure I'm going to be of much help - if you can track the issue down to an actual bug in this library, please open a new issue with an example 👍
