### ISSUE TITLE
Using with TypeScript: Property 'config' does not exist on type 'Options'. ts(2339)

### ISSUE THREAD

**Issue by limonte** [jshjohnson/Choices#620]
I'm following the example from docs: https://github.com/jshjohnson/Choices/blob/master/types/index.d.ts#L656

and getting this TS error:

![image](https://user-images.githubusercontent.com/6059356/62415529-bb17d780-b633-11e9-9067-1d4bdba713a0.png)

**Comment by limonte** [comment]
Also, the example from types is different from the example from README

![image](https://user-images.githubusercontent.com/6059356/62415690-9a9d4c80-b636-11e9-86c0-2eb457f65c3c.png)

![image](https://user-images.githubusercontent.com/6059356/62415692-a426b480-b636-11e9-8867-a84cda12ff57.png)

**Comment by limonte** [comment]
The example from types isn't working for me, I believe there are mistakes in types.

**Comment by tinovyatkin** [comment]
Fixed by #687
