### ISSUE TITLE
[Mobile Safari] Not always removing loading state

### ISSUE THREAD

**Issue by aarongerig** [jshjohnson/Choices#628]
I load about 4000 items via Ajax callback into a Choices instance. This works fine on all browsers except mobile Safari. The items are always loaded correctly and are also inserted into the HTML markup. The only thing not working all the time (about 60% success rate) is to remove the loading state. So the Choices instance is still showing the "Loading ..." label, eventhough the items are all loaded and inserted.

Let me know if you need more infos on this.

Choices.js version: 7.0.0

**Comment by aarongerig** [comment]
@jshjohnson Do you need anything else to confirm this bug?

**Comment by aarongerig** [comment]
ping @jshjohnson

**Comment by aarongerig** [comment]
@jshjohnson Is there anything I can do? A short answer would do, this should be easier ...

**Comment by jshjohnson** [comment]
Please may you provide a reduced use case highlighting the issue please? Thanks

**Comment by aarongerig** [comment]
Couldn't reproduce it on the latest version (9.0.0). In production, I'm using version 7.0.2 with some weird workarounds for setting the disabled state (see https://github.com/jshjohnson/Choices/issues/457).

I'm going to update Choices.js ...
