### ISSUE TITLE
init() throws error

### ISSUE THREAD

**Issue by dgt41** [jshjohnson/Choices#63]
Trying a simple destroy() and then init() won't work...

http://codepen.io/dgt41/pen/amXoQL

**Comment by jshjohnson** [comment]
Hi @dgt41,

This should be resolved as of [version 2.4.0](https://github.com/jshjohnson/Choices/releases/tag/v2.4.0).

Thanks

**Comment by dgt41** [comment]
WOW, that was fast!

Thanks 👍
