### ISSUE TITLE
issue with search when result is empty.

### ISSUE THREAD

**Issue by Gougoul** [jshjohnson/Choices#635]
I run following sample :

var choice = new Choices('.elt1');
var lastElement = '';
var x = choice.passedElement;
x.addEventListener('search', function(event) {
	var data = event.detail.value;
	if (lastElement && data.startsWith(lastElement)) 
		return;
  choice.ajax(function(callback) {
  fetch('/list.jset?q='+data)
    .then(function(response) {
		lastElement = data;
        response.json().then(function(data) {
	for (var pos = 0;pos < data.length; pos++) {
        	callback(data[pos], 'value', 'label');
	}
      });
    });
  });

}, false);

in the case where the query returns at least one element, everything is fine.
If it returns [] (empty list), then the choice blocks and can't used anymore...

Any idea why ?

**Comment by Gougoul** [comment]
Nobody has an answer about that or what ?

**Comment by tinovyatkin** [comment]
Ajax was removed in latest version along with a lot of internal refactoring - could you try the latest version please?

**Comment by Gougoul** [comment]
In the last version it works :).. But I have another bug... :(
