### ISSUE TITLE
selectedState does not exist

### ISSUE THREAD

**Issue by St-Permiakov** [jshjohnson/Choices#637]
Related to #367 
As stated there, selectedState css-class does not appear on selected option.
So either documentation is incorrect or it's a bug.

**Comment by mroseboom** [comment]
Hey there, any update on this?

**Comment by tinovyatkin** [comment]
@jshjohnson Do you want that to be implemented or removed from documentation?

**Comment by jshjohnson** [comment]
I think it can be removed - I don't see any distinction between this and the `highlighted` state

**Comment by St-Permiakov** [comment]
It most assuredly cannot.
Highlighted state appears on hover and selected should appear on currently selected items. Those are completely different use cases.

**Comment by jshjohnson** [comment]
@St-Permiakov you could use the 'highlighted' state for that situation

**Comment by mroseboom** [comment]
@jshjohnson At this moment it isn't implemented or i'm missing someting?

**Comment by tinovyatkin** [comment]
@mroseboom it's not implemented in code base in current version.

**Comment by St-Permiakov** [comment]
Does it appear on selected item without user hovering it?
How can I distinguish selected item when I'm hovering it?
And what if I'm supposed to make selected item visually disabled (that was my use case actually)?

**Comment by tinovyatkin** [comment]
@jshjohnson the implementation will be trivial and I can easily add that, however, @St-Permiakov use case probably will anyway require overriding template rendering. 

Is that feature were never implemented or were removed in past version without updating documentation?

**Comment by St-Permiakov** [comment]
Well, the only reason why I created this issue was impossibility to distinguish hovered and selected states for styling. That's what that selectedState was supposedly for. If there is any other way...

**Comment by tinovyatkin** [comment]
@St-Permiakov with Choices 8 released today:

```js
const example = new Choices(element, {
  callbackOnCreateTemplates: () => ({
    item: (classes, item) =>
      const i = Choices.defaults.templates.input.call(this, classes, item);
     if(item.selected) i.classList.add('.is-selected');
return i;
  }),
});
```

**Comment by stasguma** [comment]
@tinovyatkin For me works the second example with a `choice` function. Thanks a lot.
I'll correct you a little.
In this part `classList.add(".is-selected")` we don't need a dot before `is-selected`.

It would be better if it worked without a workaround

**Comment by tinovyatkin** [comment]
@stasguma glad it works for you, fixed an example, thank you!

**Comment by jshjohnson** [comment]
I've addressed this bug here: https://github.com/jshjohnson/Choices/pull/754 - note only a "choice" has a "selected" state. An item does not 👍
