### ISSUE TITLE
Add way to build a really lightweight version or make it more modular

### ISSUE THREAD

**Issue by philippkuehn** [jshjohnson/Choices#64]
You talk about a lightweight version but I think it's way to bloated for simple use cases (for example if you just want to use a single select input with search functionality). 

**Status quo:**
chosen.min.js | _28kb_
selectivity.min.js | _50kb_
choices.min.js | _61kb_
select2.min.js | _67kb_

It would be nice if it is possible to build an own custom build or (better) you make it modular like selectivity.js.

**Comment by jshjohnson** [comment]
Hi @philippkuehn,

I am currently investigating ways of reducing the codebase by using Webpack 2 - I'm also looking at producing an ES6 version which does not have the added weight polyfills/transpiled code.

With that said, I think it is unfair to compare Select 2 and Chosen with libraries such as Choices and Selectivity as the former rely on jQuery to function. jQuery minified alone weighs ~80kb. It's like comparing two light cars without engines with two slightly heavier cars with engines!

Thanks,
Josh

**Comment by jshjohnson** [comment]
Update: With Webpack 2 Choices is reduced to 55kb!
