### ISSUE TITLE
problems to import using RequireJs

### ISSUE THREAD

**Issue by herbertpimentel** [jshjohnson/Choices#65]
when we try to use choices.js with requirejs the lib is loaded but, no return is provided.

To demonstrate the problem I have created a sample project to show how I am trying to use choices with requirejs

https://github.com/herbertpimentel/choicesjs_test

to run this you just need:

Install bower globally using npm

```sh
> npm install -g bower 
```

Install the bower dependences

```sh
>bower install 
```

As I hove you will see choices is successful loaded but I receive a message TypeError: Choices is not a constructor... when I try to use it.

maybe it is something with webpack export. I am very curious about it

**Comment by jshjohnson** [comment]
Hey @herbertpimentel,

Thanks for the heads up. This should now be resolved if you install v2.4.1.

Thanks,
Josh
