### ISSUE TITLE
Not working in IE 8 

### ISSUE THREAD

**Issue by xexes** [jshjohnson/Choices#652]
library not working in IE 8, 9 and 10
for 8 is  SCRIPT1010:   the problem is "default" param

for 9 and later is SCRIPT5007   Plik: choices.js, Row: 135, Column: 3 Unable to get 'id' property for undefined or empty reference

**Comment by jshjohnson** [comment]
This library only supports ES5 JavaScript. If you need to support older browsers, you will need to use polyfills. See here: https://github.com/jshjohnson/Choices#browser-compatibility
