### ISSUE TITLE
How to implement multi select input with remove button.

### ISSUE THREAD

**Issue by nazariydolfin** [jshjohnson/Choices#657]
How do I implement this? Your documentation just gives the options and what they are responsible for, and the web-site with examples does not have code snippets that are responsible for the examples, so I am struggling to implement this.

Appreciate any help.

**Comment by jshjohnson** [comment]
If you view source on the demo page you can see how each instance is created

**Comment by nazariydolfin** [comment]
I was about to say that I will look at source. Thanks. Closing this now. Is there any plan to make code snippets next to the examples, or at least mention that at the top. Just a suggestion.
