### ISSUE TITLE
[Wordpress]: Ajax Sub-category dropdown based on parent

### ISSUE THREAD

**Issue by VQH-cmd** [jshjohnson/Choices#659]
I am stucking at this step.
I'd like someone to resolve this issue.
## Image Example
![SearchBox](https://raw.githubusercontent.com/VQH-cmd/-issues/master/Choices/%23001/img.png)
--------
![WP Cat](https://raw.githubusercontent.com/VQH-cmd/-issues/master/Choices/%23001/img-01.png)
## The Issue:
- I see Choices.js has [Ajax function](https://github.com/jshjohnson/Choices#ajaxfn).
- But I do not know how to apply it in this situation.
- The idea:
	- When I select "City A" in the [City] < select >;
		- In [District] < select > only show value of sub-category base on it's parent (City A) [District A-D01, District A-D02]; 
		- When I select "District A-D01" in the [City] < select >;
			- In [Ward] < select > only show value of sub-category base on it's parent (District A-D01) [Ward A-D01-W01, Ward A-D01-W02];
- The Category tree:
	- City A:
		- District A-D01
			- Ward A-D01-W01
			- Ward A-D01-W02
		- District A-D02
			- Ward A-D02-W01
			- Ward A-D02-W02
	- City B:
		- District B-D01
			- Ward B-D01-W01
			- Ward B-D01-W02
		- District B-D02
			- Ward B-D02-W01
			- Ward B-D02-W02

## [The Source Code:](https://github.com/VQH-cmd/-issues/blob/master/Choices/%23001)
- [FrontEnd.php](https://github.com/VQH-cmd/-issues/blob/master/Choices/%23001/frontend.php)
- [Ajax.php](https://github.com/VQH-cmd/-issues/blob/master/Choices/%23001/ajax.php)
- [Javascript.php](https://github.com/VQH-cmd/-issues/blob/master/Choices/%23001/js.js)

## The Goal:
- [ ] **DO NOT** use or **mention** any **Wordpress plugin**.
- [ ] Use **Vanilla Javascript** (**plain JavaScript**) only (NO jQuery,... !).
- [ ] Resolve the issue above with the available [Source Code](https://github.com/VQH-cmd/-issues/blob/master/Choices/%23001).

**Comment by jshjohnson** [comment]
This isn't really an issue with the library - StackOverflow would be a better place for this 👍
