### ISSUE TITLE
Input field not auto focus on dropdown shown on iOS

### ISSUE THREAD

**Issue by taiwabisabi** [jshjohnson/Choices#679]
On iPad and iPhone, the input is not focused when you click and open the select dropdown ad there is no search text placeholder, either. 
The user have be click on the input to be focused and to see the keyboard.

I already try to trigger a focus() on the input with `showDropdown` event by it's not working.
It seems that focus() on safari iOS have some issue, maybe some polyfills to correct the issue ?

Is someone find how to fix that ?

**Comment by SalTor** [comment]
@taiwabisabi Did you resolve this?

**Comment by taiwabisabi** [comment]
> @taiwabisabi Did you resolve this?

@SalTor no, sorry!
