### ISSUE TITLE
Setting addItems to false disables the input

### ISSUE THREAD

**Issue by jbanety** [jshjohnson/Choices#68]
Hi,

I don't want to my users being able to add items.
But if I set `addItems` to `false`, the select is disabled.

Is it possible to allow selecting an option but not to add items ?

Thanks for your great lib.

**Comment by jshjohnson** [comment]
Hi @jbanety,

Could you provide your full config please? 🙂

Thanks

**Comment by jbanety** [comment]
I think I misunderstood the "terminology".
"Items" is the real user choice (e.g. selected="selected").

So If I set addItems to false, the select is disabled.

I thought that it was to allow users to "create" new option.

Sorry.
