### ISSUE TITLE
Only show clear results x when there's input to clear

### ISSUE THREAD

**Issue by bronzehedwick** [jshjohnson/Choices#684]
As a usability enhancement, I propose only having the clear results "x" button for single selects only become visible/accessible once there's an option chosen to clear.

This should help reduce confusion/clutter around the x when no option is selected.

**Comment by tinovyatkin** [comment]
Do you mean this 'X'?
![Screenshot 2019-10-24 at 22 21 05](https://user-images.githubusercontent.com/5350898/67538260-b439b780-f6ac-11e9-9d98-05adbae57350.png)

but it how it work now...

**Comment by bronzehedwick** [comment]
Yes, that's the X I'm referring to.

The current behavior is different from what I'm describing.

Right now, the X is always visible. I'm proposing only showing the X when a selection has been made.

**Comment by bronzehedwick** [comment]
Clarification: this behavior I'm describing only happens when there's a placeholder value set. If there is no placeholder value, the "x" button is not visible when there is no selection.
