### ISSUE TITLE
callbackOnChange : only trigger on user inputs (select elements)

### ISSUE THREAD

**Issue by chymz** [jshjohnson/Choices#7]
Me again for an enhancement ;)

callbackOnAddItem and callbackOnRemoveItem are called when choices are added to the select list.
I've made another callback which is called only on user inputs : https://github.com/chymz/Choices/commit/57c241aac06ac25c983eec83e149c836efbe29e1

Thanks !

**Comment by jshjohnson** [comment]
I'm loving all your feedback! So useful. I'll start integrating some of these enhancements ASAP.

Thanks!

**Comment by jshjohnson** [comment]
This has now been implemented (https://github.com/jshjohnson/Choices#callbackonchange).

Thanks!
