### ISSUE TITLE
How to make the others hide when choosing a particular option?

### ISSUE THREAD

**Issue by uCryNet** [jshjohnson/Choices#725]
How to make the others hide when choosing a particular option and dislpay message: 

> When this option is selected, others are not available

Screen: https://i.ibb.co/K6Xvqj0/Screenshot-20191030-205911.png

**Comment by tinovyatkin** [comment]
There are more than one way to do so, depending on your initial data structure.
As example, you may listen for `choice` event and set `maxItemCount` in case of that option select.

**Comment by uCryNet** [comment]
> There are more than one way to do so, depending on your initial data structure.
> As example, you may listen for `choice` event and set `maxItemCount` in case of that option select.
I just thought maybe there is a built-in method, as in select2. Thanks for the information

**Comment by uCryNet** [comment]
How can I find the selected item?
