### ISSUE TITLE
demo page is not working in IE11

### ISSUE THREAD

**Issue by tinovyatkin** [jshjohnson/Choices#732]
We definitely need to merge #715 earlier 😄 

1. Prettier resulted in extra comas that IE11 doesn't understand
2. Element.prototype.closest disappeared after all merging 👐

**Comment by tinovyatkin** [comment]
One more error after fixing all above:

![image](https://user-images.githubusercontent.com/5350898/68041960-21021280-fca8-11e9-9f57-aad4e6311448.png)


![image](https://user-images.githubusercontent.com/5350898/68041938-16e01400-fca8-11e9-8744-7ea04623e3d5.png)

**Comment by bronzehedwick** [comment]
I can confirm this bug: version 8+ is breaking in IE.
![Screen Shot 2019-11-15 at 10 47 35 AM](https://user-images.githubusercontent.com/637174/68957888-f8464680-0798-11ea-9f6c-d270c7827447.png)
