### ISSUE TITLE
Callback on search cleared

### ISSUE THREAD

**Issue by aletorrado** [jshjohnson/Choices#74]
Hi,

I need to be notified when the search term gets cleared, but Choices don't trigger `callbackOnSearch` when the search input is empty. I've already setted `searchFloor: 0`. How can I achieve this?

Thanks

**Comment by jshjohnson** [comment]
I should be able to put a fix in to ensure this works. I'll keep you updated.

Thanks

**Comment by jshjohnson** [comment]
This was harder than I first though as there are numerous ways of clearing the search input - I'll reopen if this gets enough traction from users but closing for now.

**Comment by 0190** [comment]
I was looking for a way to get alerted when the search input is cleared, as there's no obvious workaround.

Anyone who adds custom functionality to the select widgets would certainly benefit from a "search cleared" event or at least a status method checking whether the search is empty.

**Comment by edtownend** [comment]
@jshjohnson Any chance this could be reopened? I've implemented search in ajax and there's no way to know the search form has been cleared. Thanks!
