### ISSUE TITLE
If `option[placeholder]` is not set, `choices__placeholder` class is not assigned

### ISSUE THREAD

**Issue by kzkn** [jshjohnson/Choices#741]
If I use the new way to put a placeholder that is added by #617 , `choices__placeholder` class is not assigned to `<option>`. If I use the old way, not so on.

Version: 7.1.5
Source: https://gist.github.com/kzkn/12d2940840f9895acc94f3584805be82

**Comment by jshjohnson** [comment]
This has been fixed already and will included in the [next release](https://github.com/jshjohnson/Choices/releases/tag/untagged-8a12ba89f151ff8511f1) 👍
