### ISSUE TITLE
How to remove an option when choosing another option in lib?

### ISSUE THREAD

**Issue by uCryNet** [jshjohnson/Choices#742]
I need to, when choosing different options, an option from the selection menu removes another - a special option. The meaning and label are different for everyone. How to do this in lib?

Sandbox: https://codepen.io/CryNet/pen/ZEExbON?editors=1010

I am adding this code, but I do not know how to make it better:

```
        element.addEventListener('choice', (event) => {
          if (...) {
              ...
          } else {
            setTimeout(() => {
              event.target.closest('.choices').querySelector('#choices--unit-item-choice-1').remove()
              let lenghtItem = event.target.closest('.choices').querySelector('.choices__list.choices__list--dropdown .choices__list')

              if(lenghtItem.children.length === 0) {
                event.target.closest('.choices').querySelector('.choices__list.choices__list--dropdown').style.display = 'none'
              }
            }, 1);
          }
        })
```
**P.S.** _without setTimeout the code does not work for some reason (I do not understand why)_

I would like to know how this can be done well. Because every time during the event the same element must be deleted from the DOM-tree, and before that it is added again.

**Comment by tinovyatkin** [comment]
If you just need to conditionally _hide_ some options then easier way, probably, with current version will be moving that logic into `callbackOnCreateTemplates`:

```js
const choices = new Choices({ callbackOnCreateTemplates() {
  choice(...args) { // or item, depending on your use case
    if (shouldShow)
      return Choices.defaults.templates.choice.call(this, ...args);
    return document.createTextNode("");
  }
}
});
```
