### ISSUE TITLE
sortFilter doesn't work on Firefox

### ISSUE THREAD

**Issue by CathyMacars** [jshjohnson/Choices#75]
Hi!

I'm facing a problem on Firefox, where if I use `sorfFilter`:

```
const choices = new Choices( '.select' , {
	sortFilter: 'sortByAlpha'
});
```

It gives me the following error:

![screen shot 2016-11-08 at 5 22 08 pm](https://cloud.githubusercontent.com/assets/2156812/20113573/0df7cbf0-a5d8-11e6-9308-d226dede0169.png)

This error does not occur on Chrome or Safari, everything works fine on both.

**Comment by jshjohnson** [comment]
Hi @CathyMacars,

So the `sortFilter` config option is expecting a function not a string: https://github.com/jshjohnson/Choices#sortfilter

Choices sorts by alpha by default anyway so you can simplify your config to:

```js
const choices = new Choices( '.select');
```

Thanks
