### ISSUE TITLE
Show placeholder if no value is selected

### ISSUE THREAD

**Issue by philippkuehn** [jshjohnson/Choices#76]
If I want to use the placeholder option:
``` javascript
var choices = new Choices(element, {
  placeholder: true,
  placeholderValue: 'Please Choose…',
  removeItemButton: true,
});
```

the select is still empty:
![jmoqt7t60l](https://cloud.githubusercontent.com/assets/2500670/20137307/f6f58b3e-a679-11e6-9b75-3efd7dcc27e8.png)

But after I selected on item and removed it with the remove button the placeholder value is visible:
![inorkmfjeh](https://cloud.githubusercontent.com/assets/2500670/20137349/26cecdd4-a67a-11e6-8149-364e60732282.png)

Is this the expected behavior?

**Comment by jshjohnson** [comment]
Closed as this is related to [77](https://github.com/jshjohnson/Choices/issues/77)

**Comment by travist** [comment]
This may fix this issue. https://github.com/jshjohnson/Choices/pull/248
