### ISSUE TITLE
Release format

### ISSUE THREAD

**Issue by tinovyatkin** [jshjohnson/Choices#760]
New GitHub Action driven release is beautiful, but the **🔧  Maintenance** section header is repeated twice:
![Screenshot 2019-11-14 at 19 27 25](https://user-images.githubusercontent.com/5350898/68904714-f044c300-0714-11ea-8df6-5bc0b90d5bcc.png)

**Comment by jshjohnson** [comment]
Yeah this is a bug - see here: https://github.com/toolmantim/release-drafter/issues/293
