### ISSUE TITLE
Typing when focused should reflect on search input

### ISSUE THREAD

**Issue by groenroos** [jshjohnson/Choices#762]
When focusing on (only certain kinds of) Choices elements not via click (for example, by tabbing from another input), the first key the user presses will not be reflected in the search input - it will only open the dropdown.

While a key like `Enter` should only open the input, it feels like an alphanumeric key should be included in the filter input. This would effectively be the behaviour if you focus on the element via a mouse click, because this also will necessarily open the dropdown. Therefore, users using keyboard navigation suffer a degraded experience.

This is reproducible on [the demo page](https://joshuajohnson.co.uk/Choices/), on any Choices elements under the **Single select input** or **Form interaction** sections, and the *With remove button* and *Use label in event (add/remove)* in the **Multiple select input** section.

### Steps to reproduce
1. Focus on an element prior to the affected Choices element
2. Press Tab to focus on the Choices element
3. Press a letter or number on your keyboard

### Expected behaviour
The dropdown should open, with the pressed letter or number as the search field value

### Actual behaviour
The dropdown opens, but the search field is blank.

### Types affected
- `select-multiple` - only when `removeItemButton` is set to `true`
- `select-single` in all cases

### Environment
Chrome 78.0.3904.97 (Official Build) (64-bit), macOS 10.15.1.

**Comment by jshjohnson** [comment]
Thanks - I have aimed to fix this [here](https://github.com/jshjohnson/Choices/pull/767)
