### ISSUE TITLE
Choices does not work on ie11 due classList.add() multi arguments issue

### ISSUE THREAD

**Issue by hope55** [jshjohnson/Choices#764]
Current Choices.js version (9.0.1) does not work on ie11. (The Choices.js Demo page is also broken now in ie11). The reason is that one of the required classes will not be applied on dropdown div element. as ie11 does not support multiple arguments on classList.add().

This occures only once in the source code, here:

```javascript
dropdown: function dropdown(_ref13) {
    var list = _ref13.list,
        listDropdown = _ref13.listDropdown;
    var div = document.createElement('div');
    div.classList.add(list, listDropdown);
    div.setAttribute('aria-expanded', 'false');
    return div;
  },
```

Unfortunately I couldn't find any polyfill classList implementation that would work with multiple add() arguments. Most simple solution is to break that line in two:

```javascript
dropdown: function dropdown(_ref13) {
    var list = _ref13.list,
        listDropdown = _ref13.listDropdown;
    var div = document.createElement('div');
    div.classList.add(list);
    div.classList.add(listDropdown);
    div.setAttribute('aria-expanded', 'false');
    return div;
  },
```

This seems to be working on ie11.

**Comment by tinovyatkin** [comment]
polyfill.io [doing it correctly](https://github.com/Financial-Times/polyfill-library/blob/8db31f38485465887f98cb8468092c68a247072f/polyfills/DOMTokenList/polyfill.js#L34), but you need to polyfill DOMTokenList also:
https://polyfill.io/v3/polyfill.min.js?features=Element.prototype.classList

I'm using [dom4](https://github.com/WebReflection/dom4) and it also fixes multi-arguments.
