### ISSUE TITLE
How to make a jquery append() work with choices and having multiple <select>?

### ISSUE THREAD

**Issue by Lukaum** [jshjohnson/Choices#766]
i have a button that add a row with one select and one input, well i can't add a class at these selects inserted with jquery append(), because it only works on the first select. How can i do to enable the choices in all selects?

JS CHOICES
`document.addEventListener('DOMContentLoaded', function() {
  var cadProdcategoriasListar = new Choices('#cad_prod_categorias_listar, #cad_prod_marcas_listar, .cad_prod_opcoes_listar_js', {
    searchEnabled: true,
    searchResultLimit: 3,
    searchPlaceholderValue: 'Pesquisar',
    itemSelectText: '',
    shouldSort: false,
    shouldSortItems: false,
    loadingText: 'Carregando...',
    noResultsText: 'Nenhum resultado encontrado',
    noChoicesText: 'Nenhum item inserido no formulario'
  });
});`

JS THAT APPEND THOSE SELECTS
...
`        input += '<div class="form-group col-12 col-lg-5 col-xl-5 my-2 mx-auto">';
          input += '<label for="produto_opcao'+total+'">OPÇÃO '+total+'</label>';
          input += '<select name="opcoes[]" class="form-control cad_prod_opcoes_listar_js" required>';
            produtoOpcoes.forEach(function(o, index){
              input += '<option value="'+o["id"]+'">';
                input += o["nome"];
              input += '</option>';
            });          
          input += '</select>';
        input += '</div>';  `

**Comment by jshjohnson** [comment]
```js
const elements = Array.from(document.querySelectorAll('.your-class'));

const instances = elements.map((element) => {
  return new Choices(element);
});```

**Comment by Lukaum** [comment]
Works, but return a warning:  "Trying to initialise Choices on element already initialised".

`var adicionarOpcao = document.querySelector('#produto_adicionar_opcao');
var total_opcoes =  document.getElementsByClassName('.contar_opcoes_jquery').length;

adicionarOpcao.addEventListener('click', (e) => {
	e.preventDefault();

  produtoOpcoes = opcoes;
  total_opcoes = total_opcoes + 1;

  var criarDiv = document.createElement("div");
  criarDiv.classList.add('form-row', 'form_vs', 'contar_opcoes_jquery');

  var input = '<div class="form-group col-12 col-lg-5 col-xl-5 my-2 mx-auto">';
        input += '<label for="produto_opcao'+total_opcoes+'">*OPÇÃO '+total_opcoes+'</label>'; 
        input += '<select name="opcoes_cadastro['+total_opcoes+'][opcao]" class="form-control choices__input produto_opcao" required>';
          produtoOpcoes.forEach(function(o, index){
            input += '<option value="'+o["id"]+'">';
              input += o["nome"];
            input += '</option>';
          });          
        input += '</select>';
      input += '</div>';  

      input += '<div class="form-group col-12 col-lg-5 col-xl-5 my-2 mx-auto">';
        input += '<a class="deletar_opcao_jquery float-right px-0 mx-0" data-whatever="'+total_opcoes+'">X</a>';
        
        input += '<label>*VALOR DA OPÇÃO '+total_opcoes+'</label>';        
        input += '<input type="text" name="opcoes_cadastro['+total_opcoes+'][valor]" class="form-control" id="produto_opcao'+total_opcoes+'"';
          input += 'minlength="1" maxlength="100" data-validation-length="1-100" data-validation="custom" data-validation-regexp="^[a-zA-Z0-9áàâãéèêíïóôõöúçñÁÀÂÃÉÈÊÍÏÓÒÖÚÇÑ\\s\\)\\(\\,\\-\\.\\x22\\x5C]{1,100}$"';
          input += 'data-validation-error-msg="> O CAMPO VALOR DA OPÇÃO '+total_opcoes+' DEVE CONTER APENAS CARACTERES ALFANUMERICOS | CARACTERES MIN=1 MAX=100." ';
          input += 'required />';
      input += '</div>'; 

  criarDiv.innerHTML = input;
  
  document.querySelector('#campo_produto_adicionar_opcao').append(criarDiv);

  const produtoOpcao = Array.from(document.querySelectorAll('.produto_opcao'));
  const instancesProdutoOpcao = produtoOpcao.map((element) => {
    return new Choices(element);
  }); 
});
`
