### ISSUE TITLE
style collision with formio

### ISSUE THREAD

**Issue by tomhermans** [jshjohnson/Choices#771]
Wrote a component based on the choices.js plugin. Now the dev team comes back a lot of the styling collides with formio, which has a lot of the same stylenames..
Is this something I can easily fix without breaking future updates etc ?

**Comment by jshjohnson** [comment]
Yes - you can change the class names that Choices uses here: https://github.com/jshjohnson/Choices#classnames

**Comment by tomhermans** [comment]
Thanks Josh ! Totally missed that.

**Comment by jshjohnson** [comment]
:) No worries
