### ISSUE TITLE
Browser tests fail when testing IE

### ISSUE THREAD

**Issue by jshjohnson** [jshjohnson/Choices#778]
**Describe the bug**
Selenium action consistently fails when testing IE on Windows:

https://github.com/jshjohnson/Choices/pull/777/checks?check_run_id=318258430

**Comment by tinovyatkin** [comment]
@jshjohnson the whole page CSS is broken actually, that's why it can't do a screenshot. I'm out of bandwidth to peek into it right now but hopefully will do in a couple of days.

**Comment by jshjohnson** [comment]
<img width="1011" alt="Screenshot 2019-11-26 at 13 30 45" src="https://user-images.githubusercontent.com/3064889/69637722-1f323180-1051-11ea-82bf-4f9e58518433.png">

**Comment by jshjohnson** [comment]
This is now resolved 🎉
