### ISSUE TITLE
Drop-down list increase page height

### ISSUE THREAD

**Issue by uCryNet** [jshjohnson/Choices#780]
**Describe the bug**
If the select is at the bottom of the page, then the drop-down list can “pull” the page down

**Expected behavior**
He must not add height

**Screenshots**
<a href="https://ibb.co/0VKj4zf"><img src="https://i.ibb.co/gFdMqcD/1.png" alt="1" border="0"></a>
<a href="https://ibb.co/yS9Jc8b"><img src="https://i.ibb.co/NSvzdLH/2.png" alt="2" border="0"></a>

**Desktop:**
 - OS: Linux
 - Browser: Chromium, FireFox
 - Version: 78.0.3904.97, 70.0.1

**Comment by uCryNet** [comment]
** Possible Solution:
CSS:
```
.choices__list--dropdown {
  height: 0; /* added this */
}
```
JS:
```
_proto.show = function show() {
    this.element.classList.add(this.classNames.activeState);
    this.element.style.height = 'auto' // added this
    this.element.setAttribute('aria-expanded', 'true');
    this.isActive = true;
    return this;
  }
_proto.hide = function hide() {
    this.element.classList.remove(this.classNames.activeState);
    this.element.style.height = '0' // added this
    this.element.setAttribute('aria-expanded', 'false');
    this.isActive = false;
    return this;
  };
```

**Comment by ch3rn1k** [comment]
Another possible solution via only CSS:

`
.choices__list--dropdown {
  height: 0;
}
.choices__list--dropdown.is-active {
  height: auto;
}
`
