### ISSUE TITLE
Changelog & specific version over CDN

### ISSUE THREAD

**Issue by flackjap** [jshjohnson/Choices#781]
Hi,

It happened to me that I just noticed that the Choices select list on one my websites is not displaying placeholder values correctly anymore. The reason is that the sort function was renamed from 'sortFn' to 'sorter' (https://github.com/jshjohnson/Choices/pull/734). It didn't take me much time to locate the issue, since I was expecting that it must be something around that function, and since the bug happened without anyone touching the implementation on the website. I was qucik to figure out that it must be that the newer version of Choices caused an error somewhere.

1. The changelog

Anyhow, I tried looking up for the link or file named 'changelog' first, since I would expect to find something related to this problem in a list of changes, rather than going through the list of commits and pull requests. Of course, a moment later, I realised that there are 65 tagged releases, so I went there and quickly found out that some GitHub repos are actually using that sections as a changelog :) 
If it's possible, I would link those releases in the README.md file, and name it 'changelog', because I won't probably be the only one going that way.

2. Specific version over CDN

Again, I tried searching in README.md for a way to fixate the specific version for Choices, so that this doesn't happen again, but I couldn't find any example. Of course, the JSdeliver CDN seems like a popular thing, so it shouldn't be that hard for someone to find out how to request the specific version. (e.g. https://cdn.jsdelivr.net/npm/choices.js@9.0.0/public/assets/scripts/choices.min.js), but it would be nice to have that written in readme file for folks that are not that much into JS ecosystem.

**Comment by jshjohnson** [comment]
I've updated the README with versioned CDN links but I disagree with people not looking at releases for changes. Thanks for raising 👍
