### ISSUE TITLE
Class props are not available with es6 import

### ISSUE THREAD

**Issue by dreit-p** [jshjohnson/Choices#782]
I need to extend default template of choiceList and i try to follow to [callbackoncreatetemplates](https://github.com/jshjohnson/Choices#callbackoncreatetemplates) in docs. But when I import Choices.js via `import Choices from 'choices.js'` prop `Choices.defaults` is not available. If I use Choices.js via CDN then it works fine as in docs. 

How can I solve my problem via es6 import?

**Comment by tinovyatkin** [comment]
Do you have problems at the VSCode not recognizing it in IntelliSense, i.e. like this:

![2019-11-25 11 32 15](https://user-images.githubusercontent.com/5350898/69554006-7c59b480-0f77-11ea-928a-15d8ea5c1cd4.gif)

Or when you are creating your bundle with webpack/rollup?

It it's at bundling then try to use this:
```js
import Choices from 'choices.js/src/scripts/choices';
```

**Comment by dreit-p** [comment]
@tinovyatkin when i try to import with `import Choices from 'choices.js/src/scripts/choices';` i get the same error  `Cannot read property 'templates' of undefined`. By other words, `Choices.defaults` is not defined.

I've installed choices.js via yarn and the version is 7.1.15. I opened choices.js/src/scripts/choices.js and there is no mentions of the `defaults` prop.

**Comment by dreit-p** [comment]
The problems resolved by upgrade to 9.0.1. I've noticed the mentions of the `defaults` var there.
