### ISSUE TITLE
Multiple dependendable dropdown

### ISSUE THREAD

**Issue by Rajdev2011** [jshjohnson/Choices#786]
Hi 

I Have 2 drop downs country,state. 

user can select multiple countries and multiple states  

but need filtering like when multiple countries selected then we need to show states belongs to multiple countries only.

Can i know how we can achieve this

**Comment by jshjohnson** [comment]
You could have an [`addItem`](https://github.com/jshjohnson/Choices#additem) event listener for the countries instance which then uses [`setChoices`](https://github.com/jshjohnson/Choices#setchoiceschoices-value-label-replacechoices) to dynamically populate states

**Comment by jshjohnson** [comment]
There is an example of something similar on the demo page if you view the source: https://joshuajohnson.co.uk/Choices/ (see the cities/tube station example)

**Comment by Rajdev2011** [comment]
Thanks for your reply.  
Iam getting all countries and state on page load .Countries and states ( with country as select group) are multi select.
Lets say i selected country A and Country B .I will want to filter state droup to show States of Country A and Country B only
