### ISSUE TITLE
Typescript: value 'bottom' should be allowed

### ISSUE THREAD

**Issue by rkristelijn** [jshjohnson/Choices#790]
**Describe the bug**
When a user of the lib wants to set the default uncollapsed state fixed to bottom, typescript errors out.

**To Reproduce**
1. Create a choices
2. set position to bottom in script

**Expected behavior**

No errors

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 22

**Additional context**

**Comment by jshjohnson** [comment]
This will be fixed in the next release 👍
