### ISSUE TITLE
Bug : select-one is not focusable with Tab key

### ISSUE THREAD

**Issue by chymz** [jshjohnson/Choices#8]
Because `this.input` is hidden.

Dirty solution : https://github.com/chymz/Choices/commit/e8a5158db74c610575de768d65e7c96192015b42

**Comment by jshjohnson** [comment]
Could possibly get round this by giving the input a tabindex attribute.

**Comment by jshjohnson** [comment]
As of version 1.0.3, single select inputs are now focussable. I think this needs revisiting at some point as once a choice has been selected, the element loses focus (unlike the behaviour of normal select inputs). Happy to add you as a contributer if you have any ideas on getting around this!

**Comment by chymz** [comment]
Hi !
Thanks for your reactivity :)

On this issue we need to check/fix multiple problems:
- Keep focus if one item is selected
- If `search` is set to `false` focus is good, but we can't navigate with keyboard arrows. Also if we go to the next select with tab key, `hideDropdown()` is not called ?
	
I'll try to look this !
