### ISSUE TITLE
Trigger change event on passed element

### ISSUE THREAD

**Issue by jbanety** [jshjohnson/Choices#80]
Triggering the change event each time an item is added/removed by a user would be fantastic !
It also permit to bind event listener on the passed element. So callbacks could be added dynamically.

**Comment by jshjohnson** [comment]
Hey @jbanety,

There is a callback for that already! - https://github.com/jshjohnson/Choices#callbackonchange

Thanks

**Comment by jbanety** [comment]
Yes I know, but my Choices instances are generated dynamically from CMS.
Fields are in an XML file to define the form.
I can't set callbacks in XML.
So It would be simpler to trigger change event to the passed element to handle the event in a normal way.
It would work with third party script who listen to the select event by example

**Comment by jshjohnson** [comment]
Oh I see. Hmm, I'm not keen on that. I've been attempting to keep the file size of Choices as minimal as possible; adding duplicate functionality for edge-cases is going to make that difficult unfortunately!

**Comment by jbanety** [comment]
Yes I'm preparing a PR with only 20 lines added.
You'll see.
