### ISSUE TITLE
Fuse custom threshold

### ISSUE THREAD

**Issue by StephaneTrebel** [jshjohnson/Choices#83]
Since Choices bases its searches on Fuse, it could allow for some Fuse tweaks.
My main grip is `threshold` since it can give a weird user experience depending on its context, and the default one is 0.6 which is not even close to a "near perfect" search like we are accustomed to.

How about keeping the default, but allowing to pass a custom threshold in init options ?
Or, better, a subset of Fuse.js options could be passed on to fine tune the experience.

**Comment by jshjohnson** [comment]
Hi @StephaneTrebel,

i like the idea of being able to pass Fuse options via the config - that should be a simple change to make so would be happy to review a pull request :) 

Josh

**Comment by jshjohnson** [comment]
This has been resolved as of version [2.6.1](https://github.com/jshjohnson/Choices/releases/tag/v2.6.1).

Thanks
