### ISSUE TITLE
Is this repo still maintained?

### ISSUE THREAD

**Issue by alfonsoar** [jshjohnson/Choices#833]
Hi - again thank you for the awesome library! Wanted to know if this repo is still being maintained or if you guys are looking for new maintainers. Not seeing a lot of activity from the maintainers and bugs/feature request are starting to pile up.

**Comment by jshjohnson** [comment]
Hey - this is still maintained but I don't have much time at the moment so i'm less active than I was earlier in the year

**Comment by abarrak** [comment]
@jshjohnson If you could give insight on this or how to fix by contribution?
It's major functional blocker.
[1](https://github.com/jshjohnson/Choices/issues/522), [2](https://github.com/jshjohnson/Choices/issues/152), [3](https://github.com/jshjohnson/Choices/issues/830), [4](https://github.com/jshjohnson/Choices/issues/829).
Thanks.

**Comment by alfonsoar** [comment]
@jshjohnson are you open to recruiting additional maintainers for this project?

**Comment by alfonsoar** [comment]
closing since https://github.com/jshjohnson/Choices/issues/880

**Comment by Xon** [comment]
I've taken over maintenance, I've been looking through various backlogs and addressing issues. The v11.0.0 release has had a lot of code churn, but all the tests are working and I'm looking through for more bugs to fix.
