### ISSUE TITLE
callbackOnChange not fired when value set by setValueByChoice

### ISSUE THREAD

**Issue by jbanety** [jshjohnson/Choices#85]
When I programmatically set select value with `setValueByChoice` method the onChange is not fired.
Only the onAddItem callback is triggered.
Quote from doc : 
> Usage: Function to run each time an item is added/removed by a user.

**Comment by jshjohnson** [comment]
Hi @jbanety,

That is intentional, the onChange is only fired by a user change, not a programmatic change. As you are setting it pragmatically, you'll know that the state has changed so can run your code immediately after.
