### ISSUE TITLE
Compability with Alpine.js

### ISSUE THREAD

**Issue by Briareos17** [jshjohnson/Choices#868]
**Describe the solution you'd like**
Have ability to integrate Choices with Alpine.js like Vue do.

**Comment by greenwebsas** [comment]
Include your select item in a div like this

  <div x-data  x-init="new Choices($refs.your_id); " ...

and add on select item

x-ref="your_id"

Works also with livewire

**Comment by abishekrsrikaanth** [comment]
@greenwebsas, I am trying to get this to work with Alpine and Livewire. Would you be ok to share your code?

**Comment by greenwebsas** [comment]
![Capture](https://user-images.githubusercontent.com/67318148/86609029-9b0f3780-bfab-11ea-8646-a06f608c9fc6.JPG)

**Comment by umarsyarif** [comment]
> I have another issue when trying to use choices with livewire. When i changing value in choices select, livewire property gets {value: 1} except of simple 1

I had the same problem. did you get the solution? @Briareos17

**Comment by Fak3** [comment]
I have the same issue with alpinejs. Have anyone managed to solve this?
Reported in separate issue #1222
