### ISSUE TITLE
Uncaught TypeError: Cannot read property 'type' of null(…)

### ISSUE THREAD

**Issue by NekoStudio** [jshjohnson/Choices#87]
Hello. Not working plug in the console such error

`Uncaught TypeError: Cannot read property 'type' of null(…)`

**Comment by jshjohnson** [comment]
Hi,

I need more information than that. May I have your config please? A JSBin would be even better...

**Comment by NekoStudio** [comment]
Sorry. I solved the problem. Incorrectly prescribed `elements` in `const choices = new Choices(elements);`
Another question, if you can) 
Possible instead
```
const choices = new Choices('.select', {
        maxItemCount: 5,
});
```

Replaced by

```
$(".select").Choices({
  maxItemCount: 5
 });
```
?
Thank you.

**Comment by jshjohnson** [comment]
Hi @NekoStudio,

To achieve what you suggested, I would need to create a jQuery wrapper for Choices. As the main purpose of Choices is that it doesn't require jQuery as a dependency, I don't plan to do that.

You can however do something like this though:

```js
var $select = $('.select');

var choices = new Choices($select[0], { ... });
```

**Comment by NekoStudio** [comment]
Thank you very much)
