### ISSUE TITLE
How to hide placeholder from the list?

### ISSUE THREAD

**Issue by lavezzi1** [jshjohnson/Choices#89]
Hello everyone,

I want to hide the placeholder from the list (choices list) is this possible?

**Comment by jshjohnson** [comment]
Hi,

Could you send a screenshot to illustrate what you mean please? Thanks :)

**Comment by lavezzi1** [comment]
@jshjohnson I want to hide this item 'This is placeholder' because it looks very weird. 
![screen shot 2016-12-15 at 16 22 07](https://cloud.githubusercontent.com/assets/10686894/21216619/bed46db2-c2e2-11e6-99b2-239cb8637503.png)

**Comment by jshjohnson** [comment]
So the example you set is using the following HTML:

```html
<select class="form-control" data-trigger name="choices-single-default" id="choices-single-default" placeholder="This is a search placeholder">
  <option selected disabled>This is a placeholder</option>
  <option value="Dropdown item 1">Dropdown item 1</option>
  <option value="Dropdown item 2">Dropdown item 2</option>
  <option value="Dropdown item 3">Dropdown item 3</option>
</select>
```

To remove the `This is a placeholder`, you just need to remove 

```html 
<option selected disabled>This is a placeholder</option>
```

Thanks

**Comment by lavezzi1** [comment]
@jshjohnson I didn't say that I want to remove it, I want to HIDE it. I want to keep placeholder.

**Comment by jshjohnson** [comment]
Ah apologies. That's currently not possible but is in the works [here](https://github.com/jshjohnson/Choices/issues/77).
