### ISSUE TITLE
Server-side search API

### ISSUE THREAD

**Issue by SamMousa** [jshjohnson/Choices#893]
**Is your feature request related to a problem? Please describe.**
I'm looking to prevent the loading of a large list of options in cases where the user is expected to always enter a search term to narrow down the list.

**Describe the solution you'd like**
I'm looking for some documentation that tells me how to best implement this using Choices.js, one option seems to be set `searchChoices` to false, and implement my own filtering in the search event.

It is however unclear how this would work, especially since the search event has a `resultCount` payload, which seems to suggest it is fired after searching.

**Describe alternatives you've considered**
None yet, I'm not so much worried about solving the problem, but more about solving it in a way that is "recommended" ie that makes Choices work with me instead of against me.

**Additional context**
I'm up for making a (documentation) PR if given some pointers as to what you think is the best solution.

Personally I'd always prefer to do rough searching on the server side and then run all results through the client side filter logic as well. This means we can see the server side filtering purely as an optimization. Also we should (document how to) implement caching (don't send the exact server query twice; optionally don't send more specific queries if we have the result of a generic query that should be a superset etc).

**Comment by uteq** [comment]
There appears to be an option to do this:

Check out: Options from remote source at https://joshuajohnson.co.uk/Choices/

**Comment by SamMousa** [comment]
No that's not the same as an API. I can already load choices from a remote; the issue is searching them.
Suppose I have 1.000.000 options and I'd like to search them, this can be done by using an API that filters the results, this is something ChoicesJS could support out of the box.
The example you mentioned just uses fetch to get the whole data set once.

**Comment by bjornpost** [comment]
I think the code as outlined here might help: https://github.com/jshjohnson/Choices/issues/806

As you can see, there's an issue that causes the search box to freeze for a tiny bit after each keystroke (which is annoying).

**Comment by SamMousa** [comment]
Thanks!
