### ISSUE TITLE
Bug : 'value' of choice can be integer in selects

### ISSUE THREAD

**Issue by chymz** [jshjohnson/Choices#9]
And `trim()` can throw an error if the array of choices have integers as values.

- https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/choices.js#L704
- https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/choices.js#L1014

**Comment by jshjohnson** [comment]
This has now been resolved as of verson 1.0.3:

- https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/choices.js#L798-L799
- https://github.com/jshjohnson/Choices/blob/master/assets/scripts/src/choices.js#L1122

Thanks
