### ISSUE TITLE
How to validate select?

### ISSUE THREAD

**Issue by lavezzi1** [jshjohnson/Choices#90]
Hello,

Can I validate your select using plugins like https://github.com/ansman/validate.js or https://github.com/skaterdav85/validatorjs ?

Or maybe you recommend something different. I just need to validate select on empty value, if nothing change then show error.

**Comment by jshjohnson** [comment]
Hi @lavezzi1,

Could you perhaps give me a code example of how you would like to validate? Would it be when the user types? 

There is `callbackOnChange` method that is useful for validation. Example:

```js
var example = new Choices(element, {
  callbackOnChange: function(value) {
    if(!value) {
      // handle error
    } else {
      // handle success
    }
  }
});
```
