### ISSUE TITLE
setChoiceByValue -With remote data and with seacrh event

### ISSUE THREAD

**Issue by 7even-ux** [jshjohnson/Choices#903]
I use Choices with remote - with search event as  the list has a lot of records. I would like to use setChoiceByValue for a selected option that depends by the value of an input.
I could not find any docs that can help me to achieve this without setChoices, and this will freez my page until it search  the value in Json.

I have searched all the events and there is no "onload" event . I could use is to programmatically choose item like i use search and works very fast.

```
`
element.addEventListener('search', function (event) {  
            let request = Url + "q=" + event.detail.value;
            fetch(request)
                .then(function (response) {
                   {
                        response.json().then(function (data) {
                            choice.setChoices(data, 'id', 'label', 'value', true);
                        });
                    }
                })
             
		});
});  `
```

**Comment by notflip** [comment]
@7even-ux Did you find a solution to this?
