### ISSUE TITLE
CSS Classes not prefixed with plugin name

### ISSUE THREAD

**Issue by itaditya** [jshjohnson/Choices#91]
When I integrate your plugin, it overwrites some classes of my custom css (eg. container).
All the plugin's css classes must be prefixed with **choices-** , eg: `.choices-container` , so that there is no overwriting.I am willing to make a PR regarding this issue.

**Comment by jshjohnson** [comment]
You can actually change the prefix to whatever you like! Just download Choices, run `npm install`, change the prefix name in the Choices SCSS file and run `npm run css:build`. Thanks :)

**Comment by jshjohnson** [comment]
See: https://github.com/jshjohnson/Choices/blob/master/assets/styles/scss/choices.scss

**Comment by itaditya** [comment]
What about css file, because I'm not using SASS in my project

**Comment by jshjohnson** [comment]
The SCSS file will compile to CSS

**Comment by itaditya** [comment]
I installed your plugin with bower , will this work with bower too ?

**Comment by jshjohnson** [comment]
The same tasks will need be run regardless of whether you installed with Bower or NPM
