### ISSUE TITLE
Support page up/down to select first/last options

### ISSUE THREAD

**Issue by haggen** [jshjohnson/Choices#97]
Page up and down should jump, respectively, to the first and last options in the dropdown. On macOS it should be command+left/up and command+right/down.

**Comment by jshjohnson** [comment]
Like the idea :) Will be happy to review any pull requests if people want this

**Comment by haggen** [comment]
I'm working on it. Also, `Command`+`Left`/`Right` is equivalent to `Home` and `End` keys, so scratch that, only `Command`+`Up`/`Down` should work.

**Comment by haggen** [comment]
I just regretted that I said I was working on it.

**Comment by jshjohnson** [comment]
Thanks for the PR - in response to your question, I need to know the direction to determine whether we should scroll to the top of the element (scrolling up) or to the bottom of the element (scrolling down). There is probably a more concise way of doing this though...
