### ISSUE TITLE
Change event's value should be null when item is removed

### ISSUE THREAD

**Issue by kayue** [jshjohnson/Choices#98]
I am hoping to get the latest value of the choices by listening to the change event:

```javascript
select.addEventListener('change', (event) => {
  // this.change.emit(event.detail);
});
```

This work mostly fine, except when user click the remove item button, the change event's `value` is still the previous value instead of `null`.

Is this an expected behaviour? Would it be better if it returns `null`?

-------

- https://github.com/jshjohnson/Choices/blob/2af4c51949680e8f90572bca83aceb419e81835d/assets/scripts/src/choices.js#L922

**Comment by jshjohnson** [comment]
Hi @kayue,

It should return the value of the item being removed - this appears to be a bug. Let me investigate.

Thanks

**Comment by jshjohnson** [comment]
Just investigated this - the correct value is being returned. So to clarify, the change event will return the value being removed or added.
